### ISSUE TITLE
V2.1 comments

### ISSUE THREAD

**Issue by DavidG-Aus** [kangyu-california/PersistentWindows#1]
Hi Kang Yu,

I have just downloaded V2.1 and ran it but I am not sure if it is the correct version running.
I can see a Persistent Windows icon in the System Tray but not in the Task Manager?
When I right click the icon in Sys Tray it offers Diagnostics and Shutdown. Diagnostics opens a small blank window (on the 3rd monitor) with the title MainWindow.
Somewhere you need to indicate which version is running.
It would also be nice if a small confirmation dialog pops up when you first run the program.
Regards,
DG

**Comment by kangyu-california** [comment]
The task name of this app has been renamed to "PersistentWindows" since V2.1, previously it was "Ninjacrab.PersistentWindows.SystrayShell" which is not very intuitive to find in task manager.

Starting from V2.3, the version number is displayed in tooltip of systray icon. The version info is also available by querying file properties of PersistentWindows.exe in explorer (aka file manager).

The diagnostics window displays debug information only for debug build,  The debug info is intentionally hided in release build.

The tool can be launched as automatic startup task without user acknowledge, so I prefer no dialog popup.

Hope these will clarify the issues you may have.

**Comment by DavidG-Aus** [comment]
I do not see either "Ninjacrab..." or "PersistentWindows" in my task list ??
Even if the debug info is hidden, the window title could give the program name and version. "Main Window" looks a bit unfinished.
Is it possible to distinguish whether it has been launched as a startup task or manually? I just find it a bit uncomfortable when I launch an EXE file and nothing appears to happen. Sort of feels like malware.
Thanks for the work on this utility.

**Comment by kangyu-california** [comment]
Please try V2.4 which pop up a splash window at program start.
The PersistentWindows task is there, you probably want to sort task name first to be able to see it steadily.
This utility is not created with GUI feature to play with, it is supposed to work on the major purpose of restore misplaced windows.

**Comment by DavidG-Aus** [comment]
Ah, I found it on the Details tab of the Task Manager.  I was looking in Processes 
and Services.

Incidentally I found three entries in Details because it had run it three times to 
admire the Splash screen ;-)  You should probably prevent it running multiple times.

Many thanks.

Cheers,
DG





Please try V2.4 which pop up a splash window at program start.
The PersistentWindows task is there, you probably want to sort task name first to be able to 
see it steadily.
This utility is not created with GUI feature to play with, it is supposed to work on the major 
purpose of restore misplaced windows.
-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

-----------------------------------------------------------
  David Griffiths           david@digitalgraphics.com.au
  Digital Graphics P/L      http://www.digitalgraphics.com.au
  Sydney, Australia         +61 2 4567 8999
-----------
Australian agents for:
 E-LAB computers - AVR Pascal and In Circuit programmers
 Logical Systems - programming adapters
 Intronix - LogicPort 34 channel Logic Analyser

**Comment by kangyu-california** [comment]
Single instance run limitation has been implemented starting from V2.5

**Comment by DavidG-Aus** [comment]
Very good.

thanks,
DG



Date sent:	Thu, 30 Jan 2020 12:43:14 -0800
