### ISSUE TITLE
Incompatibility with Keypirinha since 5.18

### ISSUE THREAD

**Issue by xpliz** [kangyu-california/PersistentWindows#100]
Since upgrading to version 5.18 Keypirinha get's pushed to the bottom/below/underneath of all opened windows instead of the top. Also setting Keypirinha to keep on top of everything doesn't change a thing. 

I thought it was my weird setup and I've tried default portable version of Keypirinha with fresh settings but it's the same. 

Reverting back to 5.17 of PersistentWindows "fixes" this problem. 

I've also tried unreleased 5.19 version of PersistentWindows with the same problem.

**Comment by kangyu-california** [comment]
Fixed in 5.20

**Comment by xpliz** [comment]
I can confirm v5.20 works with Keypirinha. Thank you for such fast fix.
