### ISSUE TITLE
Chatty (app): Windows move when reopening them

### ISSUE THREAD

**Issue by C0Nd3Mnd** [kangyu-california/PersistentWindows#102]
When using [Chatty](https://chatty.github.io/) and opening a window, then moving it, closing it and opening that same window again, it resets to the position (after about a second) that PersistentWindows remembered.

Here's an example:

https://user-images.githubusercontent.com/47672946/112204808-63691e00-8c14-11eb-94c8-2175201e7879.mp4

The problem is that when I'm trying to use the application fast that the window moves around which might cause me to accidentally press a button I didn't intend to press or whatever.

It's a Java application (don't know if that makes any difference).

**Comment by C0Nd3Mnd** [comment]
@kangyu-california That works fine, however only if I always use Ctrl + Shift. Is there a way to permanently exclude a window (even then, that will disable restoring functionality when it's actually needed)?

**Comment by kangyu-california** [comment]
Its very difficult to specify an arbitary window using config.

**Comment by kangyu-california** [comment]
Will try to cut the latency from 1s to .5s in next release to make window recovery appear more smooth

**Comment by C0Nd3Mnd** [comment]
Would it be possible to limit restoring windows to when the computer wakes up from sleep (or when the monitors were turned off)?

**Comment by kangyu-california** [comment]
Will add a new command switch to disable real time single window restore, as the feature is necessary for other users.

**Comment by kangyu-california** [comment]
Fixed in 5.21
In case the issue still exist (especially after PC sleep), run PW with -fix_unminimized_window=0
