### ISSUE TITLE
"off screen" window fixed in error

### ISSUE THREAD

**Issue by jgwallace3** [kangyu-california/PersistentWindows#103]
I use World of Warcraft in windowed mode and position it so the windows titlebar is slightly off screen. PW insists on 'fixing it' to a small window size every time I minimize then swap to it. Trying the 'control+' (or is it 'control+shift+' ?) when moving it -- to have PW ignore it -- has no effect.

Can there be an easier way to have PW ignore a specific window's placement or ignore slightly off-screen windows?

Attached relevant 9999 events

[PW 9999 event.zip](https://github.com/kangyu-california/PersistentWindows/files/6222021/PW.9999.event.zip)

**Comment by jgwallace3** [comment]
And... trying it with moving the WOW window onto the screen, I'm finding that it is being restored incorrectly from a minimized state. I -do- manually resize the window and PW seems to be unaware of that.

The 9999 event record has no real info in it.

**Comment by kangyu-california** [comment]
Try  undocumented command switch
-offscreen_fix=0

**Comment by jgwallace3** [comment]
Ok, will do! Also the 2nd comment was completely related to the off-screen issue as well. Will test!

**Comment by jgwallace3** [comment]
Tested. The offscreen_fix command switch worked for me. Closing issue.
