### ISSUE TITLE
PW resizes Double Commander window on every (fresh) start

### ISSUE THREAD

**Issue by MisterT87** [kangyu-california/PersistentWindows#105]
Hey Guys and again thank you again for this App :)

**Issue:** Everytime when I start Double Commander (fresh start) PW will resize that window from maximized to smaller window.

But I also have to tell: Double Commander is a beta and due to a bug Double Commander itself need sometimes more time to start -> then PW resize the window
If Double Commander starts properly and fast -> PW wont resize the window.

Event Log: [https://pastebin.com/67YBn4R1](https://pastebin.com/67YBn4R1)

ctrl + shift + move to ignore that window didnt work for me here :(
But there was also an error when ignoring a Window...

Event Log: [https://pastebin.com/RgL4kuaR](https://pastebin.com/RgL4kuaR)

Stay healthy and have a nice day ! :)

**Comment by kangyu-california** [comment]
Fixed in 5.21

**Comment by MisterT87** [comment]
@kangyu-california can confirm -> issue solved (solved also 2 other issues) :)

but another question (just need to know): the "ctrl + shift + move" feature for to disable auto restore - is it only working for current windows session or does PW know it also after an windows reboot (like capture windows to disk) ?

**Comment by kangyu-california** [comment]
Ctrl+Shift+move only works for current PW session, i.e. the trick won't persist across reboot.
