### ISSUE TITLE
Right click menu on system tray icon needs version number

### ISSUE THREAD

**Issue by MFHFozzy** [kangyu-california/PersistentWindows#106]
Theres no easy, intuitive way to find what version is currently running, other than quitting and restarting.
The number of times i have accidentally made a new snapshot due to double clicking the system tray icon when i didnt want to is...embarrassing.

**Comment by kangyu-california** [comment]
The version number is shown when mouse is hovering on the tray icon.
Left click icon is not so popular on windows, compared to right click icon, so I repurposed left click to snapshot feature

**Comment by kangyu-california** [comment]
You may also find out version number by hovering mouse on PersistentWindows.exe in file explorer.

**Comment by kangyu-california** [comment]
Close the issue as version display function is already provided
