### ISSUE TITLE
V3.8 - Tool is not working for me

### ISSUE THREAD

**Issue by tranb3r** [kangyu-california/PersistentWindows#11]
My setup:
- main display: 3840x2160 (125%), quite slow to wake from stand by
- second display : 2560x1440 (125%), faster to wake from stand by

Most of the time, windows positions are not properly restored:
- some windows of the main display are resized to the second display size
- some windows of the second display are moved to the main display

Can you help me ? What kind of information should I provide ?

Thanks

**Comment by kangyu-california** [comment]
Working on it, should make a new release in a couple of days. Please revert back to previous working release for now

**Comment by tranb3r** [comment]
FYI: 3.6 is working much better for me.

**Comment by kangyu-california** [comment]
V3.9 should fixed the problem

**Comment by tranb3r** [comment]
V3.9 is much better yes. Thank you

**Comment by kangyu-california** [comment]
V3.10 fixed missing restore issue in sleep/wakeup scenario
