### ISSUE TITLE
keeps moving windows in task view to wrong display

### ISSUE THREAD

**Issue by darchon7** [kangyu-california/PersistentWindows#118]
persistentwindows is moving windows in Task View to the wrong display (i have 2 monitors) which i think it shouldn't be touching.

[persistentwindowslog.txt](https://github.com/kangyu-california/PersistentWindows/files/6586903/persistentwindowslog.txt)

**Comment by kangyu-california** [comment]
Assuming event log "restore minimized window "Window""  indicates the true issue,
there are two workarounds to resolve this.
1. Run PW with -fix_unminimized_window=0
2. Selectively disable restore for individual window by Ctrl-Shift moving it.

Both workarounds are documented in online help.

If the workaround doesn't address the issue, please provide more information about the "Window" process to help me reproduce the issue.

**Comment by darchon7** [comment]
tx, that seems to have fixed it.
