### ISSUE TITLE
App crash after switching on primary monitor.

### ISSUE THREAD

**Issue by mirij100** [kangyu-california/PersistentWindows#120]
I am using maximalized the application VideoRedo6 on primary monitor (resolution 2560x1440 and is zoomed 175%).
When I switched on primary monitor this application crash at 08.07.2021 19:28:15. It does not happens regulary, only sometime.
I attached events 9990-9999 from event log from minute 19:28.
[After_switching_on_primary_monitor_08d_07m_2021y_19h28m.zip](https://github.com/kangyu-california/PersistentWindows/files/6786543/After_switching_on_primary_monitor_08d_07m_2021y_19h28m.zip)

PersistentWindows is version 5.25.7840.20783.

**Comment by kangyu-california** [comment]
PW caught runtime exceptions to avoid hard crash,
what is the English translation of event 9999 at 19:28:17?
the message might be critical to root cause the crash.

![image](https://user-images.githubusercontent.com/59128756/125004198-de144880-e00d-11eb-8d65-f7dc6d1475ce.png)

**Comment by mirij100** [comment]
Czech: "Neplatný popisovač okna"
English: "Invalid window handle"

**Comment by kangyu-california** [comment]
The "Invalid window handle" error is very rare, it means some window become invalid (destroyed) during PW restore, and the destroy event is not delivered to PW.

Note there are a collection of issues here, 
1. App is not expected to destroy any window when user flip on/off display 
2. Windows OS often deliver event to PW very late.

I am hesitate to create a new release just to mask problem of other parties.

If you are really annoyed by this issue, one possible workaround is to extend restore latency from 500ms to a larger value (such as 2000ms ?) in PersistentWindowProcess.cs (line 26)
       private const int RestoreLatency = 500; // default delay in milliseconds from display change to window restore

**Comment by mirij100** [comment]
Today crash happened again, at 10.07.2021 13:11:16 at switching primary monitor on.
I think, events 9990-9999 looks differently now.
[After_switching_on_primary_monitor_10d_07m_2021y_13h11m.zip](https://github.com/kangyu-california/PersistentWindows/files/6795128/After_switching_on_primary_monitor_10d_07m_2021y_13h11m.zip)

**Comment by kangyu-california** [comment]
The log shows PW is still alive as of 13:11:22,
Could it be some other app crashed? 

events 9990~9999 are printed by PW, 
if PW ever crashed, you should look for app event printed by OS instead, which usually contains ".Net error" in message body.

By any means, please provide ALL event log around crash time, 
Also please provide a screen shot when the crash happens.

**Comment by kangyu-california** [comment]
Just noticed the issue is VideoRedo6  crashes.
Are you sure this related to PW?
Please stop or pause PW to make sure the issue is related to PW

**Comment by mirij100** [comment]
I removed by ctrl+shift+moving VideoRedo6 from PW.
But today application VideoRedo6, after I activate it, crash again.

O course, I am not sure whether is problem in VideoRedo6 or in PW (even when is "removed from control").
But I can't live without PW. I try live with occassional VideoRedo6 crash.
