### ISSUE TITLE
Issue on zoomed monitor.

### ISSUE THREAD

**Issue by mirij100** [kangyu-california/PersistentWindows#122]
Hello.

I am using Win10 20h2. Primary monitor has resolution 2560x1440 with zoom 175%, secondary monitor has resolution 1920x1080 with zoom 125%: 
![image](https://user-images.githubusercontent.com/41241053/127675776-ea2e4796-f2fa-452e-8fba-9e39bb343594.png)

When PersistentWindows restore windows then some on them are little moved to up and maybe right (maybe about 10 pixel). And even maximized window is little moved, for example my maximized Google Chrome (on monitor with zoom 175%):
![image](https://user-images.githubusercontent.com/41241053/127677139-03c4ead6-aa57-42a0-8116-de0b7be03c2d.png)

And here is the new created instance of correctly maximized Google Chrome without shift:
![image](https://user-images.githubusercontent.com/41241053/127677828-5a9e39ad-3931-4d4f-9ef5-5f09b58cea49.png)

This bug is not related only for maximized windows but for another windows too.

PersistentWindows 5.25.7840.20783.

**Comment by kangyu-california** [comment]
There was a similar issue #56 which exposed a bug that Windows API MoveWindow() does not always work as expected.
It is very hard for PW to correct this.

**Comment by kangyu-california** [comment]
Let me know if you have event 9999 like "restore snap window chrome..." 
That event is related to the fix I put in release 5.5 last year to correct MoveWindow() API misbehavior

If Microsoft has fixed that issue in I may need to add a switch to disable that fix.

**Comment by mirij100** [comment]
No, there is not "restore snap window chrome...". Only "restore snap window Nastavení", but this is different application (it's windows settings).

I have Win10 20H2.

All 9999 events are here:
[PW5.25_events.zip](https://github.com/kangyu-california/PersistentWindows/files/6911091/PW5.25_events.zip)

**Comment by kangyu-california** [comment]
Event log shows no chrome window specific event.

It appears Windows does not work very well with 175% scale factor, as evidenced by following event
"top left of Rect (-1097, 0), 2560 x 823 is off-screen.", the rectangle size 2560 x 823 does not conform to any scale factor.

There is nothing I can do from PW side to fix this.
I would recommend using 125% or 150% scale factor.
