### ISSUE TITLE
Repetitive counter-acting user input when coming out of screen lock

### ISSUE THREAD

**Issue by stefaanMLB** [kangyu-california/PersistentWindows#126]
I've been using PersistentWindows for a while to alleviate a disturbing problem in Windows linked to the use to 2 different-resolution screens with the larger main screen waking up slower than the secondary screen.
One annoying feature of PersistentWindows though is that it counteracts my (window dragging and resizing) user input for the +/- 10 first seconds after I have logged in.
f.i. when I minimize a window after loging in, PersistentWindows will restore it.  When I minimize it again, PersistentWindows will restore it again.  The typically happens up to 3 times.
I can understand that this happens once, but 2 and 3 times is very annoying.  It look like the delay counter is reset after every restore.  Why would PersistentWindows have to 'restore' a window more than once after one single wakeup or within a timeframe of some seconds ?
Can PersistentWindows not differentiate between windows misbehavior and user input ?

**Comment by kangyu-california** [comment]
Try pre-release 5.27

**Comment by stefaanMLB** [comment]
Seems solved now.
Thanks !
