### ISSUE TITLE
Remote desktop spans two monitors after restore

### ISSUE THREAD

**Issue by shawnz** [kangyu-california/PersistentWindows#127]
Hi there, thank you for this much-needed software.

I have noticed after installing the latest version 5.27, restoration of fullscreen remote desktop windows has a strange issue. The window becomes maximized in such a way that it spans both of my monitors, with black bars on the left and right.

Thanks, Shawn

**Comment by kangyu-california** [comment]
Fixed in pre-release 5.28

**Comment by shawnz** [comment]
Thank you for the quick response!
