### ISSUE TITLE
WinGet and/or Chocolatey Packaging

### ISSUE THREAD

**Issue by kylemd** [kangyu-california/PersistentWindows#131]
This app is a godsend to those using a laptop as their desktop machine. Thank you so much!

I can see that releases are very constant - would you consider adding it to WinGet or Chocolatey? Both have tools to update the packages automatically via GitHub Actions.

[WinGet Create](https://github.com/microsoft/winget-create)
[Auto Update Manifests](https://github.com/vedantmgoyal2009/winget-pkgs-automation)

[A Practical Example/Guide](https://www.techwatching.dev/posts/wingetcreate)

 [Auto Submit Chocolatey Packages](https://github.com/kai2nenobu/my-chocolatey-packages/actions/runs/212866242/workflow)

**Comment by kangyu-california** [comment]
As Microsoft start to address the issue in Windows 11, the demand for PW will be fading, and I am anticipating fewer new releases in the future.

But thanks for the appreciating and suggestion, I will try to create WinGet package for PW late on.

In the meantime, I would encourage users to try the  built-in upgrade feature in PW.
![image](https://user-images.githubusercontent.com/59128756/136437015-67703120-7a3c-4d2e-ab15-f56512b35b7b.png)
You may even run PW with -auto_upgrade=1, so no worries about not getting the latest release.

Cheers!

**Comment by AndersMad** [comment]
> As Microsoft start to address the issue in Windows 11

@kangyu-california Just wanna say thanks a lot for this time saving tool!! + I have to comment on above: Its now mid august 2022 and I rebooted my Windows 11 (3 * 4K on DP - did not start PW) and windows and tools was just all over the place! So maybe MS has "started" adressing it - but its still for s... 😬 Just alone waking from idle monitors off + wake from sleep - I can se PW doing a lot of work..
