### ISSUE TITLE
PersistenetWindows unable to install..

### ISSUE THREAD

**Issue by Selfknowledge** [kangyu-california/PersistentWindows#133]
Hi,
Just trying to install the Persistent Windows to avoid having to constantly re-arrange applications on my monitors.
When I download any versions/releases of the program, unzip it, i click on the .exe file as instructed, I then get prompted by Windows Defender SmartScreen that it's by an unrecognised app but continue to proceed by clicking 'run anyway'. 
The loading symbol appears on the trackpad cursor for a few seconds then disappears and nothing happens.
I use windows 10. Tried restarting the computer but to no avail. 
Any advice appreciated.

**Comment by Selfknowledge** [comment]
Thanks for your reply. 
Yes that's right, failed to launch and no splash window.
The event viewer logs 3 files: 'information' and two 'errors' all of which are shown in the picture...

![Capture](https://user-images.githubusercontent.com/93372916/139509029-df57d766-7df5-4e8c-a97d-eb554ed8e3ad.JPG)
..

**Comment by kangyu-california** [comment]
It is recommended to unzip to a permanent folder instead of a temporary folder, because Windows OS might delete it during  automatic disk cleanup without notification.
![image](https://user-images.githubusercontent.com/59128756/139509584-35676c32-0c63-41d2-ad1c-43ae59d7e6cf.png)

**Comment by Selfknowledge** [comment]
Ah, I didn't realise it was going to temp. Seems to be working now, thanks!
