### ISSUE TITLE
VMware Workstation

### ISSUE THREAD

**Issue by Nick135** [kangyu-california/PersistentWindows#140]
When the VMware is minimized, the "PersistentWindows" has no effect and after Monitor switch off/on and maximize VMware, the Window is on an other Display. (Same as "PersistentWindows" is not running)

When the VMware is maximized and Monitor switch off/on the window came back to the main Display, but has the size of the second one (Resize is not triggered) and the main problem is, that after that the menu bar of the VMware is missing.

OS:			Windows 10 Pro | Version 10.0.19043 Build 19043
VMWare:		16.2.1 build-18811642

**Comment by kangyu-california** [comment]
First half of the issue is fixed in pre-release 5.32
Second half of the issue is not caused by PW.

**Comment by Nick135** [comment]
No effect on first half (VMware is minimized, but in Full Screen Mode)
![image](https://user-images.githubusercontent.com/14072733/148639096-e6116189-e1e5-43cd-a739-1ef5e1dae568.png)
-
![image](https://user-images.githubusercontent.com/14072733/148638713-35ba453b-ed7e-4b60-ae47-61a32417f185.png)

If only the VMware Player is maximized, but not in "Full Screen Mode", the change has an effect and fixed an issue.


Hier a image to demonstrate how it looks like, wenn the VMware is not minimized:
- VMware fill the complete Display, but the size is still from the smaler one.
- Menu bar is no longer displayed (Menu bar is not pin, so it auto hide and appears when you move your mouse to the top of the display)
![image](https://user-images.githubusercontent.com/14072733/148638841-df42bbd3-7d1e-4317-81a7-3116a065971f.png)

**Comment by kangyu-california** [comment]
PW support full screen mode recovery only for Microsoft Remote Desktop (mstsc.exe). 
VMware full screen window is implemented quite differently and is therefore not supported by PW.

The menu bar disappearing issue can be reproduced on Windows 11 as well (without running PW), I would suggest raise the issue to VMware and/or Microsoft to get proper attention.
