### ISSUE TITLE
Restore from disk button grayed out on start

### ISSUE THREAD

**Issue by TryhardOne** [kangyu-california/PersistentWindows#145]
Hey there, yesterday after restarting my PC I noticed the "restore from disk" button was grayed out.
My first thought was that due to windows updates something was deleted.

However, today, after saving the windows to disk again yesterday, the button was grayed out again.

I restarted PersistentWindows, and now the restore button works again, with the corresponding saved windows.

**Comment by kangyu-california** [comment]
PW upgrade won't delete or overwrite captures saved on disk.
Each unique display configuration (display scale factor, monitor count/resolution/relative location) must be individually saved to disk to enable corresponding restore menu.

The issue sounds like a reliability issue of 3rd party plugin LiteDB.dll,
To verify the required db entry does exist, you may download a utility called "LiteDB Studio" from github, and open C:\Users\\<user_id>\AppData\Local\PersistentWindows\PersistentWindows.1.1.0.0.db,
you should be able to see multiple db entries (each corresponding to a unique display configuration)
![image](https://user-images.githubusercontent.com/59128756/154146367-384684e8-e4b0-412a-8cb1-90fa8968ab3b.png)

I will try to upgrade LiteDB.dll version from 5.0.9 to 5.0.11 in next release.

**Comment by TryhardOne** [comment]
> PW upgrade won't delete or overwrite captures saved on disk. Each unique display configuration (display scale factor, monitor count/resolution/relative location) must be individually saved to disk to enable corresponding restore menu.
> 
> The issue sounds like a reliability issue of 3rd party plugin LiteDB.dll, To verify the required db entry does exist, you may download a utility called "LiteDB Studio" from github, and open C:\Users\<user_id>\AppData\Local\PersistentWindows\PersistentWindows.1.1.0.0.db, you should be able to see multiple db entries (each corresponding to a unique display configuration) ![image](https://user-images.githubusercontent.com/59128756/154146367-384684e8-e4b0-412a-8cb1-90fa8968ab3b.png)
> 
> I will try to upgrade LiteDB.dll version from 5.0.9 to 5.0.11 in next release.

yes, but there is only one entry.

**Comment by kangyu-california** [comment]
I figured out where the bug is (in my code).
Restart PW is the recommended workaround for now

**Comment by TryhardOne** [comment]
> I figured out where the bug is (in my code). Restart PW is the recommended workaround for now

awesome! Thanks for the ongoing fast support as well! : 3

**Comment by kangyu-california** [comment]
Fixed in 5.34
