### ISSUE TITLE
PW sets the "Always On Top" window flag on windows to false that were set to true

### ISSUE THREAD

**Issue by ziplock9000** [kangyu-california/PersistentWindows#150]
I use PowerToys to set Alarms & Clock to be always on top.
This initially works, but after a few minutes it stops working and Alarms & Clock goes behind other windows.

However, if I stop PW, this does not happen.
My conclusion is that PW periodically enumerates windows and for some reason sets the AoT window flag to false.

The behaviour is consistent after a few tries.

**Comment by kangyu-california** [comment]
PW does not periodically clear AoT flag by itself.
As mentioned in help, PW allows user to override AoT flag (of window X) by ctrl click another window Y.
