### ISSUE TITLE
screen reset

### ISSUE THREAD

**Issue by Fryerjoe** [kangyu-california/PersistentWindows#152]
I have stopped using persistentwindows however occasionally both monitors go black for 1-2 secs and then come back on. This did not happen before using persistentwindows. I would love some help troubleshooting this issue. Thanks.

**Comment by kangyu-california** [comment]
There is no way PW would still affect system behavior once stopped.
It sounds to me either you have a loose video cable connection or has recently updated OS/driver.

**Comment by Fryerjoe** [comment]
> 

Thank you for responding, I will reset everything to be sure. I did move the whole PC around the same time I started having issues.
