### ISSUE TITLE
Feature Request: add an options window on the contextual menu

### ISSUE THREAD

**Issue by TwiggyWan** [kangyu-california/PersistentWindows#153]
Hello,

first of all congratulations for that very useful piece of software that works quite well!

I would like to have some option to tick to easily run the program on startup instead of fiddling with the task manager as well as control any of the switches featured in Help.md.

For example something like that : 
https://i.imgur.com/WkxKlCZ.png
https://i.imgur.com/5k0G2ZF.png

Would it be possible?

Thank you

**Comment by kangyu-california** [comment]
Thanks for the suggestion,

Adding option dialog requires additional effort to save the options on hard drive.
In my opinion using task manager and command line option is good enough for power users.

Although I am not an UI expert, I am open to pull request for any UI enhancement like option dialog.

**Comment by TwiggyWan** [comment]
Fair points. If I have some time i'll snoop around. Cheers
