### ISSUE TITLE
Tray application contents move towards the top left

### ISSUE THREAD

**Issue by Imperium4** [kangyu-california/PersistentWindows#155]
This is hard to explain, so this is a video of what happens:

![prPor4vxfV](https://user-images.githubusercontent.com/14152101/164977268-c5f65d48-7cfa-4a69-b8cb-542b3cf3805d.gif)

Basically after the screen has **been shutdown to inactivity at least once**, when something is prompted from the tray icons it will automatically move them to the top left of the screen.

This happens with steam contents as well, like Servers or opening the app will automatically move to the top left.

Restarting said application works, and using the **-ignore_process "GoogleDriveFS.exe"** works perfectly fine.

**Comment by Imperium4** [comment]
Is there any plans to have a release soon to test the new changes?

**Comment by kangyu-california** [comment]
Try 5.35
https://github.com/kangyu-california/PersistentWindows/releases/tag/5.35

**Comment by Imperium4** [comment]
I did, the -nogui worked, and the contents of Google Drive (the one on the first post) worked, however, Steam and Steam Servers did not work

![78675l1DXh](https://user-images.githubusercontent.com/14152101/166520642-42a1741e-ba32-4ee1-a03a-57079ce2550c.gif)

I removed the previous version before pasting the newer one into the same directory.

**Comment by kangyu-california** [comment]
close as I don't have bandwidth to support gaming scenarios
