### ISSUE TITLE
Xplorer2 app window not restoring

### ISSUE THREAD

**Issue by jgwallace3** [kangyu-california/PersistentWindows#156]
Windows program xplorer2 (https://www.zabkat.com) does not restore to the correct monitor. An event is captured, but the window does not move as expected. I primarily use it on monitor1 (and have 'captured' it there), but it is up on monitor3 on window restore and doesn't move.

Text from the event log. Let me know if you need other details.

Log Name:      Application
Source:        Application
Date:          2022-04-26 09:50:04 AM
Event ID:      9999
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      OFFICE
Description:
The description for Event ID 9999 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows: restore minimized window "xplorer² * - [Downloads @ C:\] # Install software @ R:\"

The message resource is present but the message was not found in the message table

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application" />
    <EventID Qualifiers="0">9999</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-04-26T13:50:04.2241723Z" />
    <EventRecordID>62100614</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>OFFICE</Computer>
    <Security />
  </System>
  <EventData>
    <Data>PersistentWindows: restore minimized window "xplorer² * - [Downloads @ C:\] # Install software @ R:\"
</Data>
  </EventData>
</Event>

**Comment by kangyu-california** [comment]
Xplorer2 seems to has its own mind on where to place the window when unminimized.
To workaround this, you may try snapshot feature of PW.

**Comment by jgwallace3** [comment]
It does seem to be a bit rogue. I will follow up with developer. TY for looking.
