### ISSUE TITLE
Why is startup artifically slowed?

### ISSUE THREAD

**Issue by MarioVolarevic** [kangyu-california/PersistentWindows#159]
Hello, 

Everything works great with the application, but I noticed that startup with the splash screen and progress bar is slow.
I checked the code and it seems that increments and duration are hardcoded so it's always a fixed amount of time (several seconds) to start the application.

Is there a special reason for that?
Because I recompiled the code with a shorter duration (less than a second) and everything is still working ok.

**Comment by kangyu-california** [comment]
The splash window has a progress bar elapsing for 5 seconds, so that user who cares has enough time to read and interact with it.
You may run PW with -splash=0 to totally bypass the splash window.

**Comment by MarioVolarevic** [comment]
Great, thank you for the hint.
