### ISSUE TITLE
Restored Window have a weird black bar at bottom and cut from top

### ISSUE THREAD

**Issue by KhalilSecurity** [kangyu-california/PersistentWindows#161]
I love this app, it fixes the window location issue I started getting when I used DisplayPort instead of HDMI, I have been having this issue randomly where the restored window would have a weird black bar at bottom and cut from top, no way to fix it whatsoever except moving all tabs to a new Window. I use Brave browser. Video:
https://user-images.githubusercontent.com/51271290/173171243-5958d1dd-0db5-4596-8cc0-f4b0ac2b2905.mp4

**Comment by kangyu-california** [comment]
Although the Brave browser issue is not reproducible on my PC, I have seen similar issue on Opera browser for sure.
I guess the problem is missing synchronization between PW move window and Browser draw window.
To workaround the issue, please run PW with -halt_restore 3 to hold restore until 3 seconds has lapsed.

**Comment by KhalilSecurity** [comment]
Thanks so much for your response, so do I change task scheduler arguments from
-delay_start 10
to
-delay_start 10 -halt_restore 3
or am I doing it wrong

**Comment by kangyu-california** [comment]
The command line looks good

**Comment by KhalilSecurity** [comment]
for some reason with both flags, the app keep crashing and doesn't move windows, I think syntax is not correct

**Comment by kangyu-california** [comment]
it was my bad, -halt_restore is not applicable for your situation.
please try "-prompt_session_restore", this switch will pop up a dialog asking user to confirm, I think this should help to avoid the conflict between PW moving window and Brave repaint window.

**Comment by KhalilSecurity** [comment]
Thanks Kangyu, the prompt will really kill the vibe of the app so I guess I will stuck for black bar for now :(

**Comment by kangyu-california** [comment]
Try https://github.com/kangyu-california/PersistentWindows/releases/tag/5.36

**Comment by KhalilSecurity** [comment]
For some reason the new version doesn't move the windows at all, did you see other reports?

**Comment by kangyu-california** [comment]
5.36 delays automatic restore when OS is busy moving windows, so as to make sure PW will have the final say of window location. Theoretically the new version is more robust,  it fixes some crash and restore failure when Brave window is snapped to screen edge.

**Comment by kangyu-california** [comment]
The issue is not reproducible on my environment, but I have found a weak spot in the code which could cause unsuccessful restore, please try
https://github.com/kangyu-california/PersistentWindows/releases/download/5.36_patch/PersistentWindows5.36.patch.zip

**Comment by KhalilSecurity** [comment]
Thanks for keep trying this, I also forgot to mention before last patch the icon used to turn red sometimes, it's not paused or anything but just red background
Last version: Window in secondary screen goes over window in 1st screen and 2nd screen becomes empty (no restore)
with Patch: Window in secondary screen goes over window in 1st screen but gets minimized 🗡️ and 2nd screen becomes empty (no restore)
![2022-06-20 04_16_31-](https://user-images.githubusercontent.com/51271290/174564981-2bfd1733-e0b9-46a4-97bc-5d037438e3a2.jpg)

**Comment by kangyu-california** [comment]
As documented in [readme,](https://github.com/kangyu-california/PersistentWindows#readme) color change of PW icon during auto restore is a feature to help user identify the critical moment to avoid hazard mouse/window movement.

A new scratch build was made, please try
https://github.com/kangyu-california/PW_scratch_release/releases/download/5.36_patch2/PersistentWindows5.36.patch.zip

To help me diagnose a bug, please run Event Viewer, locate to "Windows Logs" -> "Application" section, then search for Event ID 9990 and 9999, and copy paste the content of these events to new issue report

![image](https://user-images.githubusercontent.com/59128756/174691260-70b0dfb3-ac66-4123-b7e7-01cd4e86d24c.png)

**Comment by KhalilSecurity** [comment]
I meant the icon stays red not just momentarily, I will try the new build no but I also thing 5.36.patch is working fine now, even though it acted up first, for sure it worked this morning (slightly slower but works), thanks so much

**Comment by kangyu-california** [comment]
My experience is PW may stuck at busy status (red icon) when restoring previous layout if your running Microsoft Visual Studio Code window has a pending update mark. The root cause is unknown, simply proceed to update VScode will let PW resume to normal again.

Same story could happen due to unresponsive window of any app such as vscode.
