### ISSUE TITLE
thinkorswim windows are being wrongly moved after coming out of idle

### ISSUE THREAD

**Issue by darchon7** [kangyu-california/PersistentWindows#163]
I already have "-fix_unminimized_window=0" running as a parameter in my task scheduler but am finding 1 of my thinkorswim windows being wrongly maximized in my 2nd monitor after coming out of idle.

attached are logs.

[persistentwindowslog.txt](https://github.com/kangyu-california/PersistentWindows/files/8952698/persistentwindowslog.txt)
.

**Comment by kangyu-california** [comment]
PersistentWindows: No need to restore Display_Loc0x0_Res3840x2160 display session
PersistentWindows: Restore aborted for Display_Loc0x0_Res3840x2160

**Comment by darchon7** [comment]
I installed the new version. its still happening. when I capture a snapshot and restore it either via snapshot or from/to disk, it restores it correctly. I don't know why I doesn't do it properly after coming out of idle though. I am running it with the highest privileges with task scheduler.

new logs attached.

[persistentwindowslog.txt](https://github.com/kangyu-california/PersistentWindows/files/8953743/persistentwindowslog.txt)
.

**Comment by kangyu-california** [comment]
All 9999 events look OK

The issue might have the same cause as #161, for which you may try following patch
https://github.com/kangyu-california/PW_scratch_release/releases/download/5.36_patch2/PersistentWindows5.36.patch.zip

If the issue is still reproducible, please include event 9990 as well, it is OK to upload 9999 and 9990 events in separate files.

**Comment by darchon7** [comment]
yup I think that patch fixed it. thanks

here are logs.

[persistentwindowslog.txt](https://github.com/kangyu-california/PersistentWindows/files/8953809/persistentwindowslog.txt)
!

**Comment by astraetech** [comment]
Hi, 

I applied the patch 5.36.8206.xxxx and still have those problems with Thinkorswim and FactSet windows on one of the monitors.

Some excerpts from logs:


PersistentWindows: no qualified position data to restore minimized window "/VXMU22:XCBF,  -  Main@thinkorswim [build 1974]"
PersistentWindows: no qualified position data to restore minimized window ",  -  Main@thinkorswim [build 1974]"

PersistentWindows: avoid restore unresponsive window TradingView.Desktop_1.0.13.3080_x64__n534cwy3pjxzj


8/1/2022 9:35:43 AM
PersistentWindows: Restore finished in pass 4 with 14 windows recovered for display setting Display_LocM3840x1_Res2560x1440__Display_LocM3215xM1439_Res2560x1440__Display_Loc0x0_Res2560x1440__Display_Loc3840xM1020_Res1728x3072

8/1/2022 9:35:34 AM
PersistentWindows: Start restoring window layout back to 8/1/2022 9:30:05 AM for display setting Display_LocM3840x1_Res2560x1440__Display_LocM3215xM1439_Res2560x1440__Display_Loc0x0_Res2560x1440__Display_Loc3840xM1020_Res1728x3072

I can't post full logs unfortunately. It would be great if you could look into this.  Thank you for developing this app!

**Comment by kangyu-california** [comment]
"no qualified position data to restore minimized window"
This event means the subject window is already minimized when all the four screens are turned on for the first time, so when you click the window to unminimize it, PW has no knowledge of its previous unminimized location.

Just adjust window once, PW should remember it.

**Comment by astraetech** [comment]
All windows positioned on the portrait screen (there is only 1 portrait) are in normal size and not minimized. After waking up from screen off state they are moved partly off screen and i have to pull them out manually. Furthermore, those windows that are shifted off screen do not not show up in logs (I just included the ones above as they are the only error i could find). Persistent Windows with or without the patch didn't change the situation. Maybe there would be any way to extend the waiting period or something like that? I think it takes a long time to wake up all 4 screens and reorder windows. Apologies for the hassle.

**Comment by kangyu-california** [comment]
It could be that these thinkorswim windows are not covered by PW because they are sub-window (such as dialog), in that case, just move them by once, PW will start to cover them.
Another possibility is thinkorswim app manages window position by itself, counter the action taken by PW. There is not solution for this situation.
A third possibility is PW finished restore too soon, I just created 5.37 pre-release, and you may try that one by running it with new switch   -slow_restore
