### ISSUE TITLE
Non-PWA version of Facebook messenger window does not restore

### ISSUE THREAD

**Issue by chorong761** [kangyu-california/PersistentWindows#164]
Version 5.35, Windows 11

The non-PWA version of facebook messenger would not restore to its previous location. Not sure what else to include here.

**Comment by kangyu-california** [comment]
possibly the same issue as #161 #163, which has been addressed in latest commit (not released yet)
please try following patch to verify
https://github.com/kangyu-california/PW_scratch_release/releases/download/5.36_patch2/PersistentWindows5.36.patch.zip

**Comment by chorong761** [comment]
Hi, I've tested with the version you provided but it seems to have the same issue.

**Comment by kangyu-california** [comment]
I installed facebook messenger (downloaded from https://www.messenger.com/desktop), and the window restores normally on my PC.

Is there any chance that auto restore is disabled by accident in one of the following ways?
1. Ctrl-Shift move a window will disable it's auto restore
2. PW was run with command line -ignore_process "messenger"

If it is not the case, you may manually restore a previously captured snapshot to workaround it.

**Comment by kangyu-california** [comment]
close as not reproducible
