### ISSUE TITLE
"Capture Windows To Disk" Does Not Pop Up a Window

### ISSUE THREAD

**Issue by andre259** [kangyu-california/PersistentWindows#167]
When I right-click the tray icon and click "Capture Windows To Disk", no window pops up, as the help indicates that it should.

Windows 10 build 18363

**Comment by kangyu-california** [comment]
The capture/restore is unnamed by default, i.e. there is no need to assign a name, hence no dialog.
For pro user who want multiple captures for current display config, hold ctrl key pressed while clicking capture/restore menu will bring up a dialog asking for a name.
