### ISSUE TITLE
5.38 broken

### ISSUE THREAD

**Issue by darchon7** [kangyu-california/PersistentWindows#170]
I used to use 5.36 patch successfully but updating to 5.38 has broken functionality and my windows are no longer moving to my 2nd monitor.
[persistentwindowslog.txt](https://github.com/kangyu-california/PersistentWindows/files/9432095/persistentwindowslog.txt)

**Comment by kangyu-california** [comment]
5.36 patch fix has negative impact on restore speed, so it is turned off by default since 5.37.
To turn on the patch fix, please run PW with command option  "-slow_restore"

**Comment by darchon7** [comment]
it didn't work. I used "-fix_unminimized_window=0 -slow_restore"
[persistentwindowslog.txt](https://github.com/kangyu-california/PersistentWindows/files/9436481/persistentwindowslog.txt)

**Comment by darchon7** [comment]
ok it works now with that parameter. thanks!
