### ISSUE TITLE
V4.0 problems

### ISSUE THREAD

**Issue by DavidG-Aus** [kangyu-california/PersistentWindows#18]
I am running V4.0 and there are two problems:
1. The save window sizes to disk does not work. I do the save, move the windows around and then do 'Read from disk' and nothing happens.  ??
2.  3 or 4 times in the last week, the PC has woken from sleep and the windows are on the wrong screens :-(

Cheers,
DG

**Comment by kangyu-california** [comment]
Hi David,

The bug in V4.0 (failure to access database on hard drive) has been fixed in V4.1
The database method provides additional backup option to play with.
Please try latest V4.2 and thanks for your feedback.

Kang

**Comment by DavidG-Aus** [comment]
I just installed V4.2.  I now get a pop up when restoring from disk - but nothing actually happens :-(

**Comment by kangyu-california** [comment]
The database backup step is also manual.
Please "Save windows to disk" first.

**Comment by DavidG-Aus** [comment]
Yes I did that.

DG




Date sent:	Sat, 25 Apr 2020 22:37:50 -0700

**Comment by DavidG-Aus** [comment]
Should I expect the timestamp on LiteDB.xml to change - it isn't.

DG





The database backup step is also manual.
Please "Save windows to disk" first.
-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

-----------------------------------------------------------
  David Griffiths           david@digitalgraphics.com.au
  Digital Graphics P/L      http://www.digitalgraphics.com.au
  Sydney, Australia         +61 2 4567 8999
-----------
Australian agents for:
 E-LAB computers - AVR Pascal and In Circuit programmers
 Logical Systems - programming adapters
 Intronix - LogicPort 34 channel Logic Analyser

**Comment by kangyu-california** [comment]
the .db file is located at <user>/appdata/local/temp dir, you can examine its content by downloading litedb studio tool from github

**Comment by DavidG-Aus** [comment]
What is the DB file called?  I am not seeing any file get updated in the temp dir.

DG



Date sent:	Sat, 25 Apr 2020 23:04:30 -0700

**Comment by kangyu-california** [comment]
there should be 2files persistentwindows.db  and persistentwindows.db.log

**Comment by DavidG-Aus** [comment]
Yes there is but they haven't been updated since 19th and 23rd April. The log is 
zero length.

DG



Date sent:	Sat, 25 Apr 2020 23:34:00 -0700

**Comment by kangyu-california** [comment]
Hi David,

The instability issue in prior V4.x should have been fixed in V4.3 release

Thanks for the feedbacks.
Cheers.
