### ISSUE TITLE
windows not moving back to 2nd monitor

### ISSUE THREAD

**Issue by darchon7** [kangyu-california/PersistentWindows#180]
i'm currently running 5.38.8263.40891

with parameters:

-fix_unminimized_window=0 -slow_restore

and its not moving windows to my 2nd monitor after coming out of being powered off.

[persistentwindowslog.txt](https://github.com/kangyu-california/PersistentWindows/files/9596033/persistentwindowslog.txt)

**Comment by kangyu-california** [comment]
For some reason, one of the monitors keeps on loop between on and off with interval less than one second, the frequent switching will confuse PW for sure.
Please try following switch
-halt_restore <seconds> | Delay auto restore by the specified seconds, in case the monitor fails to go to sleep due to fast off-on-off switching.



</body>
</html>

**Comment by darchon7** [comment]
this sometimes works and at other times doesn't.
[persistentwindowslog.txt](https://github.com/kangyu-california/PersistentWindows/files/9661478/persistentwindowslog.txt)

**Comment by kangyu-california** [comment]
I have found a case (when root causing #184) where none of -halt_restore or -slow_restore works,
and have to come up with a new command option
-delay_auto_restore 5
where you need to adjust the 5 second delay according to your setup.

The new command option helps PW to compete with Windows OS to make the final restore move.

Attached is the patch for test
[PersistentWindows5.39_patch6.zip](https://github.com/kangyu-california/PersistentWindows/files/9736346/PersistentWindows5.39_patch6.zip)

**Comment by darchon7** [comment]
tried the new patch with new parameter. works most times but not 100%, usually doesn't work after coming out of long idle periods.

[persistentwindowslog.txt](https://github.com/kangyu-california/PersistentWindows/files/9771531/persistentwindowslog.txt)

**Comment by kangyu-california** [comment]
I used to turn on "Require Sign-in when PC wakes up from sleep", so that PW would hold auto restore until user has signed-in, this  introduces additional delay to make sure PW is restoring on a stable display setup.
