### ISSUE TITLE
Remote desktop maximized on multiple monitors

### ISSUE THREAD

**Issue by kangyu-california** [kangyu-california/PersistentWindows#184]
### Discussed in https://github.com/kangyu-california/PersistentWindows/discussions/183

<div type='discussions-op-text'>

<sup>Originally posted by **Demon1986** September 29, 2022</sup>
at work i run dual screens maximized. i tried this to help with the window going to "Restored" when the monitor comes back from sleep.
however, it doesn't seem to do as i had expected, and there doesn't seem to be any other shortcuts for capture, other than click on the icon, wich only works when the session is minimized, or in a restored state.

how the hell do i solve this?</div>

**Comment by kangyu-california** [comment]
the remote desktop session window is minimized by OS when screen goes to sleep,
PW has no idea of whether the window minimization is done by OS or by user,
so the auto capture is done too early in this case.

The workaround is to try the new attached patch and run PW with "-delay_auto_capture 5" command option (value 5 means 5 seconds), which should be enough to prevent PW from capture OS initiated rdp minimization.

Note the previous "-delay_capture" option has been renamed to "-delay_manual_capture", which only works for snapshot capture and capture to hdd command.

[PersistentWindows5.39_patch1.zip](https://github.com/kangyu-california/PersistentWindows/files/9700625/PersistentWindows5.39_patch1.zip)

**Comment by Demon1986** [comment]
i did try manually minimize after capture, and then restore it, with the same result. i will try the "new" patch in the morning, once i get to work. i'll keep u posted.

**Comment by kangyu-california** [comment]
The bug has been root caused due to missing capture of unminimized full-screen window, which has been fixed in the attached patch. 
[PersistentWindows5.39_patch3.zip](https://github.com/kangyu-california/PersistentWindows/files/9719563/PersistentWindows5.39_patch3.zip)

Please stop using -delay_auto_capture which is a wrong fix.

-delay_manual_capture is still needed to capture full-screen window, applicable for both capture to snapshot and capture to disk.

Thanks for the good catch.

**Comment by Demon1986** [comment]
while it seems that it at least doesn't override my capture now, it still seems to turn on my screens after a while (even with halt_autorestore) not sure if it's something to do with the delay before the screens come back online. there's deffently an odd behaviour in Windows 11, where if i snap the window to a side of the screen, it will not maximize rdp properly. a workaround would be to somehow minimize rdp when the screens go offline, and obviously restore when they come back.

i am not using any delay_auto_capture, only manual. i cannot seem to get the splash to go away with the -splash=0. maybe the help sections is wrong?

**Comment by kangyu-california** [comment]
There is no need to minimize rdp window (before monitor goes to sleep),
as auto-restore should be able to handle full-screen window correctly.

The issue I can reproduce is that when PW restores the full screen rdp window,
Windows OS immediately revert the action.

To mitigate the interference from OS, I have just added a new command option
-delay_auto_restore <seconds>
In my dual monitor setup, 5 seconds delay works well.

The -halt_restore option only works if the monitor fails to go to sleep due to fast off-on-off cycling.

Here is the new patch with -delay_auto_restore option
[PersistentWindows5.39_patch5.zip](https://github.com/kangyu-california/PersistentWindows/files/9729435/PersistentWindows5.39_patch5.zip)

**Comment by kangyu-california** [comment]
"-splash=0" is treated as one word, note there is no space character before and after '='

**Comment by Demon1986** [comment]
after a while of screen off, it does the exact same thing, not sure if it's because one monitor is connected via VGA and the other via a DP to HDMI cable.

also if i have -splash=0 in the start command, the program refuses to run. checking the event viewer, i get an instance of event id: 1026 from .net runtime. i'll post the exception info below. a event id: 1000 application error, pointing to kernelbase.dll, and exception code: 0xe0434352 (probably related to the other error)

`System.FormatException
   ved System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   ved System.Number.ParseInt32(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   ved Ninjacrab.PersistentWindows.SystrayShell.Program.Main(System.String[])
`

**Comment by kangyu-california** [comment]
The exception means the command line has syntax error that the delay value in seconds is missing for
either -delay_auto_restore or -halt_restore

Here is the updated patch
[PersistentWindows5.39_patch6.zip](https://github.com/kangyu-california/PersistentWindows/files/9736346/PersistentWindows5.39_patch6.zip)

**Comment by Demon1986** [comment]
i will try again on monday, when i'm back to work. funny how it launches fine without the -splash=0 in the args.

**Comment by Demon1986** [comment]
sad to say, that even though i got the args working, the app still wakes my screens randomly, and when they do, the rdp is in restored mode. i even tested with the wireless mouse turned off, same thing. i think possibly it's because the screens wake up at different intervals, because they are 2 different screens, with 2 different connections to th pc.

**Comment by kangyu-california** [comment]
Based on your description, It seems your office PC does not require login, or you leave the PC running without lock it.

PW would hold auto restore until user login. This helps to avoid unnecessary restore which may have side-effect of waking up monitor.

**Comment by Demon1986** [comment]
Yes. computer never goes to sleep, and that's how i prefer it to be. right now i am using the 'Blank' screensaver. i would like for things to work with just turning the screens off, and not putting the pc to sleep. there's gotta be a way to fix this, and not having to use a workaround.

**Comment by kangyu-california** [comment]
PW uses mouse simulation method to recover full-screen window (from "restored" status), which requires user to NOT use mouse during that critical moment.

**Comment by kangyu-california** [comment]
"-delay_auto_restore 8" works for me, as my monitor needs that long to "warm up", which also helps PW to compete with Windows OS to make the final mov.

**Comment by Demon1986** [comment]
it may work fine if it's you who wakes up the monitor(s), but here, they sorta wake up on their own, even with the mouse off. this behaviour doesn't happen when PW is not running, so it's gotta be something with the app.

**Comment by kangyu-california** [comment]
There are two issues per previous discussion
1. Auto restore does not recover full-dual-screen remote desktop window
2. When one screen goes to sleep, auto restore is triggered, which may triggers screen wakeup somehow when some special  window is moved. This problem has no silver bullet, as PW has no idea whether user is still sitting there and waiting for auto restore, although PW has already implemented some tricks to disable unnecessary auto restore, those tricks obviously has failed in your case. The workaround is to run following patch with "-enable_auto_restore_by_manual_capture" command option,   user need to explicitly instruct PW to turn on auto restore for current display configuration by doing manual capture/restore (either to disk or snapshot).

[PersistentWindows5.39_patch11.zip](https://github.com/kangyu-california/PersistentWindows/files/9826797/PersistentWindows5.39_patch11.zip)

**Comment by Demon1986** [comment]
well, at least now the windows are restored properly (finally) but the screens are still waking up without any activity. so far so good.
