### ISSUE TITLE
Code signing possible?

### ISSUE THREAD

**Issue by kuoirad** [kangyu-california/PersistentWindows#185]
I make use of Persistent Windows on my work machines, all of which have Software Allowlisting software (Carbon Black App Control) set up on them as well.  It would be helpful in dealing with new releases and Carbon Black if you could sign your code, then I could mark you as an approved publisher and Carbon Black wouldn't alert on your "new" releases when I install them.

There appears to be an analog to Let's Encrypt for code signing now called SigStore (https://sigstore.dev) - free signing certs for developers.

Is signing your code something you would consider?

Thanks!

**Comment by kangyu-california** [comment]
github.com already provides its own code signing service (based on gpg/ssh),
I will try to use the code signing service later when I got time.

Currently all code pushed to master is authenticated by Two-Factor Authentication policy enforced by github.com
it is pretty safe to assume that all the code commit is already authenticated.

**Comment by kangyu-california** [comment]
Current 2FA verification is safe enough
