### ISSUE TITLE
Difficulty bringing windows to the top

### ISSUE THREAD

**Issue by tsyrstad73** [kangyu-california/PersistentWindows#186]
Setup: 2 monitors, primary using DP, secondary using HDMI.

Issue: when I click a window to bring it to the foreground or click its button on the taskbar, it does not move to the top. Solution is to either first click the current top window, then the one I want or, if it's via a minimized window, multiple clicks of its button on the taskbar.

**Comment by kangyu-california** [comment]
This issue is related to z-order restore (for snapshot), the root cause is still unknown.
With latest windows update (21H2), I don't have this issue anymore on my PC.

If the issue still manifest on your side with latest Windows update, please try the attached patch.
You will need to press Ctrl key when activating a window, the program will additionally call SetForegroundWindow() API to try to bring the window to foreground.

**Comment by kangyu-california** [comment]
Try following workarounds from easy to hard level,
1. Manual fix: select "pause auto restore" menu by right click PW icon before launching the game, and after game play, select "resume auto restore".
2. Auto mode fix: run PW with -fix_zorder=0
3. Advanced auto mode fix: run attached PW patch with -ignore_process "ffxiv.exe"   (I don't play ffxiv game, the program file name is my guess)

[5.39 patch](https://github.com/kangyu-california/PersistentWindows/files/9750506/PersistentWindows5.39_patch7.zip)

**Comment by kangyu-california** [comment]
Finally I am able to reproduce the issue, but it is not caused by or related to PersistentWindows,
you may test my finding without runing PW.
When switching ffxiv out of full-screen mode, the window under the ffxiv window is hard to bring to top.
I believe this is caused by ffxiv instead.

**Comment by kangyu-california** [comment]
By default PersistentWindows would not affect the z-order related behavior, that means whether a window can be brought up to top is totally dependent on Windows OS and other window which has overlay area with the target window. What PersistentWindows does is observe and record what HAS happened, and restore the location when required, without affecting z-order by default.

The multi-taskview setup is impressive, I have played a little bit with that setup on my PC,
my PW command line option is "-delay_auto_restore 5 -fix_zorder"
which seems to work fine.

Here is a new patch which fixed some full-screen gaming related issues.
[5.39_patch9](https://github.com/kangyu-california/PersistentWindows/files/9805179/PersistentWindows5.39_patch9.zip)
