### ISSUE TITLE
Icon disappears

### ISSUE THREAD

**Issue by mycanaletto** [kangyu-california/PersistentWindows#189]
Hi,

Hello,

The icon always seems to be red and it is not possible to get the menu that appears fleetingly and disappears.

Click and double click ok. But not the other functions.

**Comment by kangyu-california** [comment]
Are you running Windows 10?
I am only able to reproduce the issue on Windows 7.
The menu disappear issue might be related to an old hack which I have just removed from  [latest patch](https://github.com/kangyu-california/PersistentWindows/files/9984221/PersistentWindows5.39_patch189.zip)

I am not sure why icon also disappear though.

**Comment by mycanaletto** [comment]
Yes I am on Windows 10

It's not the icon that disappears, but when I right-click I can't see the menu.

On the other hand with a click it restores a state well

**Comment by mycanaletto** [comment]
I just replaced with the latest patch, I now see the menu... !
