### ISSUE TITLE
Ignore notification area

### ISSUE THREAD

**Issue by mateuszkozakiewicz** [kangyu-california/PersistentWindows#190]
Hello,
I use a tool (StartAllBack) to move taskbar to the top, it also moves notification area to the top right corner instead of bottom right.
PersistentWindows seems to have a major issue with that and tries to restore the notification area to the top left corner all the time and it creates visual glitches where the notification area jumps from one corner of the desktop to another when animation ends.
I tried adding explorer.exe to the exceptions but it didn't help, not sure if this is the correct process though.

How do I make PersistentWindows ignore the notification area?

`C:\apps\PersistentWindows5.39\PersistentWindows.exe -splash=0 -ignore_process 'explorer.exe'`

Doesn't work

```
The description for Event ID 9999 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows: Auto fix invisible window "Notification Center"


The message resource is present but the message was not found in the message table
```

Thanks!

**Comment by kangyu-california** [comment]
Could not reproduce the issue "notification area jumps from one corner to another", which OS are you running (Windows11 or Windows 10)?
It would be great to have a screen picture to illustrate the issue.

To avoid undesirable "PersistentWindows: Auto fix invisible window Notification Center" behavior, please run PW with -fix_offscreen_window=0

**Comment by mateuszkozakiewicz** [comment]
Hello! Here are ss of the original issue, by default notification area opens in top right:
![Screenshot_20221118_093302](https://user-images.githubusercontent.com/8735263/202657733-37daf3ad-e343-4777-adf4-35e28d40706d.png)
However when using PersistentWindows the notification area opens on the left top:
![Screenshot_20221118_093337](https://user-images.githubusercontent.com/8735263/202657825-0f99e2a9-a0fd-4e27-bce7-c28feba876c8.png)
Then jumps to the bottom left:
![Screenshot_20221118_093321](https://user-images.githubusercontent.com/8735263/202657872-a7120701-b208-4bc6-9689-a6f1b50190ed.png)
These are the settings I use in the 3rd party tool (StartAllBack):
![Screenshot_20221118_093401](https://user-images.githubusercontent.com/8735263/202657925-00c06f22-989d-4005-b9a0-d6d941428ddb.png)

Anyway using `-fix_offscreen_window=0` helps!
Thank you :)
