### ISSUE TITLE
Minimized Windows Open Automatically

### ISSUE THREAD

**Issue by Mind777** [kangyu-california/PersistentWindows#191]
When switching between monitors, sometimes minimized windows unminimize by themselves even though they were previously minimized.

Is there any way to stop this behavior?

**Comment by kangyu-california** [comment]
This could happen if user minimized a window then immediately switch display, before PW get a chance to catch the minimized state.
Please try following patch
[PersistentWindows5.39_patch190.zip](https://github.com/kangyu-california/PersistentWindows/files/10050918/PersistentWindows5.39_patch190.zip)

If the patch does not work, please elaborate on the issue with details like which app window has this issue.
A picture of screen shot would be great.

**Comment by Mind777** [comment]
Thank you for the patch. Will test and let you know.

**Comment by Mind777** [comment]
Had a chance to test this out. 

Switching back from my 4k tv to my 1080p monitor, the NornVPN app opened automatically.

It wasn't opened prior to switching displays, so not sure why it opened by itself?

**Comment by Mind777** [comment]
With some further testing, windows explorer is resizing correctly now. It may have been the 3-5 second latency you mentioned.

Is there a way to reduce this latency, so resizing is captured quicker?

I will add NordVPN as an exclusion, and see if any other windows unminimize automatically. I'm wondering if a reduced capture latency would help with this also?

**Comment by kangyu-california** [comment]
The latency is  needed to reject massive window moves initiated by Windows OS rather than the user.
You may try "-delay_auto_capture 1" to shorten the capture latency to 1 second.

**Comment by Mind777** [comment]
Thanks, I will try changing the delay.

Could you explain what the following doing as i wasn't quite sure from the faw?

-redraw_desktop (why would i need to redraw the desktop)
-fix_zorder=1 (?)
