### ISSUE TITLE
PW minimises window after I maximised it

### ISSUE THREAD

**Issue by SaturnusDJ** [kangyu-california/PersistentWindows#197]
I tried out some driver versions for 5600XT by using Display Driver Uninstaller. Went back to what I had. Since then (maybe an update of PW came out?), when PW runs, this game PUBG, is being minimised (after it is started) when I click on it from the taskbar or use alt tab to maximise it. It take 3-4 attempts before it stays full screen.

Tried:
`-fix_unminimized_window=0`
`-slow_restore`
`-fix_zorder=1`
`-redraw_desktop`
`-delay_auto_capture 1.0`

Using `-delay_auto_restore 2.5` results in very strange behaviour like minimising after being in PUBG already for 30 seconds. That and/or `fix_zorder` resulted in random change of foreground applications.

Log of the original incident:
```
PersistentWindows: Display settings changed Display_Loc0x0_Res2560x1440
PersistentWindows: Start restoring window layout back to 5-1-23 22:40:38 for display setting Display_Loc0x0_Res2560x1440
PersistentWindows: keep minimized window PUBG: BATTLEGROUNDS
PersistentWindows: batch restore z-order failed
PersistentWindows: Display settings changed Display_Loc0x0_Res2560x1440
PersistentWindows: Start restoring window layout back to 5-1-23 22:40:38 for display setting Display_Loc0x0_Res2560x1440
PersistentWindows: Restore finished in pass 2 with 0 windows recovered for display setting Display_Loc0x0_Res2560x1440
```

Is it normal that it is 'restoring' stuff?
(I only need it to restore windows when the monitor is coming back from sleep, which messes up the windows by moving them to other displays that sleep less deep or so. No restores needed when just using the pc.)

I went back to version 5.39, and that works okay.

**Comment by kangyu-california** [comment]
You may want to keep PUBG window from PW restore by using -ignore_process command option.

-ignore_process "TsIGame.exe"

**Comment by SaturnusDJ** [comment]
Thank you! I will try that and report back this week.

**Comment by SaturnusDJ** [comment]
This worked, however I tried on 5.39, and one time I was away from the pc with PUBG open, then on login it was on another monitor...which is expected behaviour with that command option of course!
Trying 5.40 now.

I had some other situations were windows in the taskbar preview would render on other monitors and only when clicking those windows they would be restored to the proper monitor. Probably unrelated to this issue, but will have a look.

**Comment by SaturnusDJ** [comment]
Some strange behaviour as well on 5.40. The PUBG window gets moved to other monitors sometimes. Not sure if related to PW.

**Comment by kangyu-california** [comment]
PW is mainly crafted to improve office productivity, please bear with its limited support for gaming scenarios.

**Comment by SaturnusDJ** [comment]
I understand. Thanks for the work!
Usage is pretty good lately. PUBG window still moves to other monitors often, but again, not sure if this has to do with PW. The game is known for weird behaviour.
