### ISSUE TITLE
Photoshop palletes dont return to 2nd screen (and other apps)

### ISSUE THREAD

**Issue by laptop-doug** [kangyu-california/PersistentWindows#198]
PersistentWindows running.  Photoshop running
Move one or more of the 'palletes' to the second monitor.
unplug 2nd monitor / replug
pallets are remain on main monitor. 
Win7, laptop with second monitor running from usb  C. 

Actual 'windows' (has a button in Task Bar)  will return to the 2nd monitor.  

![image](https://user-images.githubusercontent.com/105393749/211180753-cf703453-2d38-4856-9d37-9bc424f88d32.png)

**Comment by kangyu-california** [comment]
By default PW only tracks and restores top level windows to reduce CPU usage.
For child windows like photoshop palletes, user need to explicitly move them by mouse to instruct PW to start tracking them.

**Comment by kangyu-california** [comment]
Should not be an issue if user wait a few seconds to give PW time to capture moved windows, the default auto capture latency is normally 3-4 seconds.
User can override the default capture latency using -delay_auto_capture command option which is documented in online help page.
