### ISSUE TITLE
Switching focus from fullscreen HDR content

### ISSUE THREAD

**Issue by Darkthefox** [kangyu-california/PersistentWindows#20]
Some background on the issue.  I am not sure if this is specific to the monitors I have but when I open a full screen game that supports HDR the monitor will go blank for a few seconds. I assume this is some kind of state change to support HDR but I know very little about display tech.  The normal operation is that when you alt+tab from the game to a different window the game will minimize.  With PersistentWindows running it will save the state before bringing the game into focus and then because of the monitor going through it's state change this will cause PersistentWindows to restore everything to before that state change which then leaves the game minimized.  Also sometimes the reverse happens where focus cannot be changed to a different window.  Sometimes this will also cause a problem where PersistentWindows will continuously restore over and over again leaving the pc in a black screen loop.  This loop only happened to me once and I have been unable to reproduce it.

**Comment by Darkthefox** [comment]
Here is a video showing the issue.
[https://youtu.be/ZhJ4k0q7NtQ](url)

**Comment by kangyu-california** [comment]
This issue has been speculatively fixed by release V4.8, please try and let me know how it works.

**Comment by Darkthefox** [comment]
The issue is still present.

**Comment by kangyu-california** [comment]
The failure to restore window when switching to/from video game mode has been tentatively fixed in V4.10
There should be no endless restore loop now.
There is still a small chance for PersistentWindows to switch from video game mode back to work mode, if that happened, just press alt-tab or ctrl-escape again.

**Comment by Darkthefox** [comment]
Issue is resolved!  Thank you for maintaining this application!
