### ISSUE TITLE
Not starting after logging into Windows 11.

### ISSUE THREAD

**Issue by HazeyDays** [kangyu-california/PersistentWindows#200]
Been trying to get this to start with windows to no avail.
I've added it via shell:startup and even through task scheduler (task I created is no longer there).
Worked fine with Windows 10 before upgrading to 11 with shell:startup.

**Comment by HazeyDays** [comment]
So I created a new task, and restarted. It loaded with windows. I'm pretty sure I followed the full instructions the first time, so I'll leave it at the moment and see if it still works a week from now.

**Comment by kangyu-california** [comment]
Occasional start task failure after reboot is documented in README page, the workaround is to use -delay_start command option.

**Comment by HazeyDays** [comment]
> Occasional start task failure after reboot is documented in README page, the workaround is to use -delay_start command option.

Ok, I must have missed that step the first time I tried it. Actually, after I first posted, I then came upon the README and saw the delay start command tip. It's been working since! Anyway, I appreciate the reply.
