### ISSUE TITLE
Discord display area migrates top-left

### ISSUE THREAD

**Issue by lxsli** [kangyu-california/PersistentWindows#203]
![image](https://user-images.githubusercontent.com/88806/215791049-e4b04905-a81e-4967-885d-a0a651a73bd9.png)

I have a large main monitor, with Chrome, Steam and whatnot that is restored perfectly.
I have a smaller monitor to the left, 1680x1050, with Discord maximised.
After a restore, the Discord display area migrates up and left, leaving a black border on the bottom and right edges. Un-maximising the window has no effect. Nor does resizing it or snapping it to an edge.

Anything you can recommend please? Happy to tinker with command line options etc.

**Comment by kangyu-california** [comment]
The issue looks exactly like #201, which I am also not able to reproduce.

You may try either one of the following command line options
-delay_auto_restore 3
or
-ignore_process "Discord.exe"

**Comment by lxsli** [comment]
`-delay_auto_restore 3` seems to be working for now! Thank you!
