### ISSUE TITLE
'Capture Windows To Disk' crash

### ISSUE THREAD

**Issue by SAISOP** [kangyu-california/PersistentWindows#204]
The program crashes as I try to save capture on disk.

I have both files
c:\windows\system32\wbem\wmic.exe
c:\windows\system32\wbem\en-US\wmic.exe.mui

Event Viewer has nothing on ID 9990/9999

What I do get in Event Viewer is two errors:

Log Name:      Application
Source:        .NET Runtime
Date:          7.2.2023 14.49.15
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:
Description:
Application: PersistentWindows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Diagnostics.Process.StartWithCreateProcess(System.Diagnostics.ProcessStartInfo)
   at Ninjacrab.PersistentWindows.SystrayShell.Program.GetProcessInfo()
   at Ninjacrab.PersistentWindows.SystrayShell.Program+<>c.<CaptureToDisk>b__26_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

Log Name:      Application
Source:        Application Error
Date:          7.2.2023 14.49.15
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:
Description:
Faulting application name: PersistentWindows.exe, version: 5.40.8379.25233, time stamp: 0x639501a2
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2364, time stamp: 0x5b7d4d22
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process id: 0x23a0
Faulting application start time: 0x01d93af2906ee182
Faulting application path: D:\Programs\PersistentWindows\PersistentWindows.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 01671999-2214-4c2a-ae74-865f032e91e7
Faulting package full name: 
Faulting package-relative application ID:

**Comment by SAISOP** [comment]
C:\WINDOWS\system32>wmic.exe process get commandline,processid /format:csv
'wmic.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by SAISOP** [comment]
Node,CommandLine,ProcessId
RUDY,,0
RUDY,,4
RUDY,,148
RUDY,,548
RUDY,,728
RUDY,,820
RUDY,,828
RUDY,,892
RUDY,,900
RUDY,,320
RUDY,,632
RUDY,,692
RUDY,,808
RUDY,,1076
RUDY,,1180
RUDY,,1248
RUDY,,1280
RUDY,,1352
RUDY,,1440
RUDY,,1484
RUDY,,1656
RUDY,,1764
RUDY,,1888
RUDY,,2004
RUDY,,1432
RUDY,,608
RUDY,,2116
RUDY,,2152
RUDY,,2344
RUDY,,2540
RUDY,,2684
RUDY,,2768
RUDY,,2888
RUDY,,2984
RUDY,,3392
RUDY,,3400
RUDY,sihost.exe,3720
RUDY,C:\WINDOWS\system32\svchost.exe -k UnistackSvcGroup,3748
RUDY,taskhostw.exe USER,3856
RUDY,,3904
RUDY,taskhostw.exe {222A245B-E637-4AE9-A93F-A59CA119A75E},3940
RUDY,,4020
RUDY,C:\WINDOWS\Explorer.EXE,1864
RUDY,,3676
RUDY,C:\WINDOWS\system32\svchost.exe -k ClipboardSvcGroup -p,4424
RUDY,"C:\WINDOWS\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe" -ServerName:App.AppXywbrabmsek0gm3tkwpr5kwzbs55tkqay.mca,4736
RUDY,,4800
RUDY,,4808
RUDY,,4980
RUDY,C:\Windows\System32\RuntimeBroker.exe -Embedding,4464
RUDY,,5188
RUDY,,5196
RUDY,,5204
RUDY,,5212
RUDY,,5220
RUDY,,5236
RUDY,,5244
RUDY,,5256
RUDY,,5264
RUDY,,5276
RUDY,,5284
RUDY,,5292
RUDY,,5300
RUDY,,5308
RUDY,,5324
RUDY,,5404
RUDY,,5540
RUDY,,5604
RUDY,,5924
RUDY,"C:\Program Files (x86)\F-Secure\SAFE\fshoster32.exe" --app --namespace default --id 1,6200
RUDY,,6404
RUDY,,6576
RUDY,"C:\WINDOWS\SystemApps\Microsoft.Windows.Search_cw5n1h2txyewy\SearchApp.exe" -ServerName:CortanaUI.AppX8z9r6jm96hw4bsbneegw0kyxx296wr9t.mca,6708
RUDY,,6828
RUDY,,6956
RUDY,C:\Windows\System32\RuntimeBroker.exe -Embedding,7532
RUDY,"C:\Program Files\Classic Shell\ClassicStartMenu.exe" -autorun,8824
RUDY,C:\Windows\System32\RuntimeBroker.exe -Embedding,8904
RUDY,C:\Windows\System32\RuntimeBroker.exe -Embedding,2592
RUDY,"C:\Program Files\Common Files\Common Desktop Agent\CDASrv.exe" ,9304
RUDY,,9668
RUDY,"D:\Programs\vibranceGUI\vibranceGUI.exe" -minimized,10232
RUDY,,9296
RUDY,,9284
RUDY,D:\Programs\DisplayCAL\DisplayCAL-apply-profiles.exe --task,9516
RUDY,"C:\Users\v_v\AppData\Local\FluxSoftware\Flux\flux.exe" /noshow,9872
RUDY,,9384
RUDY,"C:\Program Files (x86)\Skillbrains\lightshot\5.5.0.7\Lightshot.exe" ,5864
RUDY,"C:\Program Files (x86)\Common Files\Java\Java Update\jusched.exe" ,9988
RUDY,"C:\WINDOWS\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\TextInputHost.exe" -ServerName:InputApp.AppXjd5de1g66v206tj52m9d0dtpppx4cgpn.mca,10040
RUDY,\??\C:\WINDOWS\system32\conhost.exe 0x4,7764
RUDY,,10268
RUDY,,10648
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" ,10552
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=crashpad-handler "--user-data-dir=C:\Users\v_v\AppData\Local\Google\Chrome\User Data" /prefetch:7 --monitor-self-annotation=ptype=crashpad-handler "--database=C:\Users\v_v\AppData\Local\Google\Chrome\User Data\Crashpad" "--metrics-dir=C:\Users\v_v\AppData\Local\Google\Chrome\User Data" --url=https://clients2.google.com/cr/report --annotation=channel= --annotation=plat=Win64 --annotation=prod=Chrome --annotation=ver=109.0.5414.120 --initial-client-data=0x10c,0x110,0x114,0xe8,0x118,0x7ffc16306b58,0x7ffc16306b68,0x7ffc16306b78,6544
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=gpu-process --gpu-preferences=UAAAAAAAAADgAAAYAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAEgAAAAAAAAASAAAAAAAAAAYAAAAAgAAABAAAAAAAAAAGAAAAAAAAAAQAAAAAAAAAAAAAAAOAAAAEAAAAAAAAAABAAAADgAAAAgAAAAAAAAACAAAAAAAAAA= --mojo-platform-channel-handle=1732 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:2,4688
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --mojo-platform-channel-handle=2148 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:8,2668
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=utility --utility-sub-type=storage.mojom.StorageService --lang=en-US --service-sandbox-type=service --mojo-platform-channel-handle=2408 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:8,5424
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --extension-process --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=5 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=62402694 --mojo-platform-channel-handle=2528 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,6380
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --extension-process --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=6 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=62445372 --mojo-platform-channel-handle=4884 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,5116
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --extension-process --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=7 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=62457392 --mojo-platform-channel-handle=5024 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,4792
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --extension-process --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=8 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=62473467 --mojo-platform-channel-handle=5232 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,4032
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --extension-process --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=9 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=62496437 --mojo-platform-channel-handle=5344 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,10300
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --extension-process --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=10 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=62508823 --mojo-platform-channel-handle=5496 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,1032
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --extension-process --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=11 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=62521080 --mojo-platform-channel-handle=3428 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,10488
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --extension-process --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=12 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=62534499 --mojo-platform-channel-handle=5844 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,9824
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --extension-process --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=13 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=62566445 --mojo-platform-channel-handle=5240 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,11192
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --extension-process --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=14 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=62585588 --mojo-platform-channel-handle=5072 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,3224
RUDY,"C:\Windows\ImmersiveControlPanel\SystemSettings.exe" -ServerName:microsoft.windows.immersivecontrolpanel,976
RUDY,C:\WINDOWS\system32\ApplicationFrameHost.exe -Embedding,10492
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=23 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=63928015 --mojo-platform-channel-handle=8112 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,12564
RUDY,,12936
RUDY,C:\Windows\System32\oobe\UserOOBEBroker.exe -Embedding,13252
RUDY,"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=renderer --lang=en-US --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=27 --time-ticks-at-unix-epoch=-1675916043193394 --launch-time-ticks=67911290 --mojo-platform-channel-handle=9016 --field-trial-handle=1948,i,5184791081288275511,3922248382068119726,131072 /prefetch:1,13048
RUDY,,11920
RUDY,,3308
RUDY,,12060
RUDY,"C:\WINDOWS\SystemApps\Microsoft.Windows.Search_cw5n1h2txyewy\SearchApp.exe" -ServerName:CortanaUI.AppX8z9r6jm96hw4bsbneegw0kyxx296wr9t.mca,5004
RUDY,C:\WINDOWS\system32\DllHost.exe /Processid:{973D20D7-562D-44B9-B70B-5A0F49CCDF3F},12132
RUDY,"C:\Windows\System32\wbem\WMIC.exe" ,11876
RUDY,\??\C:\WINDOWS\system32\conhost.exe 0x4,4820
RUDY,,11672
RUDY,,3656
RUDY,,10796
RUDY,,13196
RUDY,,13296
RUDY,,4592
RUDY,,3980
RUDY,,12176
RUDY,,1304
RUDY,,9416

**Comment by kangyu-california** [comment]
> C:\WINDOWS\system32>wmic.exe process get commandline,processid /format:csv
> wmic.exe' is not recognized as an internal or external command,
> operable program or batch file.

Looks like your PATH env variable initially does NOT contain C:\Windows\System32\wbem
That may explain why PW crashes.

Now it seems you have corrected the PATH issue

> RUDY,"C:\Windows\System32\wbem\WMIC.exe" ,11876

If you restart PW, the crash should be gone

**Comment by SAISOP** [comment]
You are correct. The first reply I deleted was from CMD. The latest reply was from within WMIC.exe itself. Now I added the webm directory to PATH and PW is working as intended. Thank you for your help.
