### ISSUE TITLE
steam defaults to windowed more than 1920x1080 everytime i open it from task bar

### ISSUE THREAD

**Issue by rtzon59** [kangyu-california/PersistentWindows#209]
after booting from pc sleep mode,after launching the steam,after clicking open the steam program in the right bottom win10 task bar steam defaults to windowed more than 1920x1080 every time.after adjusting its size and capturing windows to disk only saves until i restart the pc.when restarted same thing all over again.is there a fix for this?

**Comment by kangyu-california** [comment]
You may run PW with -ignore_process "steam" command option to exclude steam window from being restored by PW.

**Comment by rtzon59** [comment]
> You may run PW with -ignore_process "steam" command option to exclude steam window from being restored by PW.

can you tell me where do i input the command? like pw exe  properties?

**Comment by kangyu-california** [comment]
If you run PW from task scheduler, the command option is in the edit task action dialog. See home page of PW, and search "command option" for details.

If you run PW by double click the exe file, you may create a shortcut of the exe, then edit the property of the shortcut like following. Then you launch PW by double click the shortcut instead.
![image](https://user-images.githubusercontent.com/59128756/220190991-65feb364-e053-44b6-9fea-4fa5152321c7.png)

**Comment by rtzon59** [comment]
> If you run PW from task scheduler, the command option is in the edit task action dialog. See home page of PW, and search "command option" for details.
> 
> If you run PW by double click the exe file, you may create a shortcut of the exe, then edit the property of the shortcut like following. Then you launch PW by double click the shortcut instead. ![image](https://user-images.githubusercontent.com/59128756/220190991-65feb364-e053-44b6-9fea-4fa5152321c7.png)

thank you for the fast reply. is it just the -ignore_process "steam" or -ignore_process "steam.exe"  or something? 
i run the program through task sch. 
theres 2 option in the edit task action dialog, do i put it on the bottom or the top? 
thank you
