### ISSUE TITLE
Always-on-top status appears to be set after restore

### ISSUE THREAD

**Issue by jmorgannz** [kangyu-california/PersistentWindows#21]
Hi there,
There appears to be some kind of usage of the windows always-on-top flag for windows that are restored.
After a restore, certain windows are stuck as always on top, and I cannot lower them behind other windows I want in the foreground unless I minimize them.
This is very annoying, to the point that I can't use PersistentWindows.
I'd rather manually reposition my windows each time, as if a window is 'stuck' as always on top, it appears the only way to fix it is to destroy and recreate the window by closing the app in question.

Right now one of my Firefox windows, and one of my Edge are stuck just like this.
Very annoying.

**Comment by kangyu-california** [comment]
working on it, thanks for the feedback

**Comment by jmorgannz** [comment]
Awesome, thanks for the info. I'll revert to 4.20 - the magic number.

**Comment by kangyu-california** [comment]
Fixed in Version 4.22

**Comment by jmorgannz** [comment]
Awesome. Will try it out now!

**Comment by kangyu-california** [comment]
The issue still exist, will create new release soon.

**Comment by kangyu-california** [comment]
Restore z-order feature has been disabled in Release 4.23 by default
Thanks for testing and enjoy the new version!

**Comment by jmorgannz** [comment]
Hey, 4.23 works great!
