### ISSUE TITLE
5.41 does not start, crashes error .NET

### ISSUE THREAD

**Issue by HugoBo-SS** [kangyu-california/PersistentWindows#215]
Windows 10 Enterprise  V10.00  Build 1904

event error:

Приложение: PersistentWindows.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.ComponentModel.Win32Exception
   в System.Drawing.Icon.Initialize(Int32, Int32)

Сведения об исключении: System.Reflection.TargetInvocationException
   в System.RuntimeMethodHandle.SerializationInvoke(System.IRuntimeMethodInfo, System.Object, System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext ByRef)
   в System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(System.Object, System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)
   в System.Runtime.Serialization.ObjectManager.FixupSpecialObject(System.Runtime.Serialization.ObjectHolder)
   в System.Runtime.Serialization.ObjectManager.DoFixups()
   в System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(System.Runtime.Remoting.Messaging.HeaderHandler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser, Boolean, Boolean, System.Runtime.Remoting.Messaging.IMethodCallMessage)
   в System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(System.IO.Stream, System.Runtime.Remoting.Messaging.HeaderHandler, Boolean, Boolean, System.Runtime.Remoting.Messaging.IMethodCallMessage)
   в System.Resources.ResourceReader.DeserializeObject(Int32)
   в System.Resources.ResourceReader.LoadObjectV2(Int32, System.Resources.ResourceTypeCode ByRef)
   в System.Resources.RuntimeResourceSet.GetObject(System.String, Boolean, Boolean)
   в System.Resources.ResourceManager.GetObject(System.String, System.Globalization.CultureInfo, Boolean)
   в Ninjacrab.PersistentWindows.SystrayShell.Properties.Resources.get_pwIcon()
   в Ninjacrab.PersistentWindows.SystrayShell.Program.Main(System.String[])

and

Имя сбойного приложения: PersistentWindows.exe, версия: 5.41.8454.35994, метка времени: 0x63f83635
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.2364, метка времени: 0x5b7d4d22
Код исключения: 0xe0434352
Смещение ошибки: 0x000000000002cd29
Идентификатор сбойного процесса: 0x3c8
Время запуска сбойного приложения: 0x01d9486be11e34b5
Путь сбойного приложения: E:\TEMP\PersistentWindows5.41\PersistentWindows.exe
Путь сбойного модуля: C:\Windows\System32\KERNELBASE.dll
Идентификатор отчета: 65bd2ae5-344b-4ba2-a5a2-9208707ac71c
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:

**Comment by kangyu-california** [comment]
you may continue to run older versions of PW using following command line argument
-check_upgrade=0

**Comment by kangyu-california** [comment]
5.41 was built with VisualStudio 2022, the .exe seems to have compatibility issue with Windows10 Enterprise.

Attached is a VS2019 build
[PersistentWindows5.41p1.zip](https://github.com/kangyu-california/PersistentWindows/files/10834587/PersistentWindows5.41p1.zip)

**Comment by BrotherErryn** [comment]
Same issue with this build (Win 10 Pro), can confirm that 2019 build starts fine.
