### ISSUE TITLE
5.41: alt-tabbing from a full-screen window sometimes causes the window to not be visible upon alt-tabbing back

### ISSUE THREAD

**Issue by Alethon** [kangyu-california/PersistentWindows#218]
Discovered while playing Elden Ring in full-screen mode (required for HDR support). Window appears to either be resized to an incredibly small size and/or moved off-screen, since HDR causes the screen brightness to apparently dim when the window gains focus but is not visible on screen. Proposed solutions include adding configuration options to either
1. ignore full-screen windows
2. support an exclusion list

User is willing to implement

**Comment by kangyu-california** [comment]
There are two ways to exclude a window from restore by PW, 
1. move the window with CTRL SHIFT pressed.
2. run PW with -ignore_process "foo.exe" command option

To further debug the issue, you may run PW with -debug_process "foo.exe" option, and observe event 9990,9999 in event viewer
