### ISSUE TITLE
Monitors Turn Back on after Going to Sleep

### ISSUE THREAD

**Issue by VanFinale** [kangyu-california/PersistentWindows#221]
So I'm having a weird issue where the software turns my monitors back on after going to sleep. Monitors go to sleep and stay asleep while Persistent Windows is not running but keep turning themselves back on while it is running.

There were 5 events that happened the last time it happened within 10 seconds of each other.

-PersistentWindows: Display settings changed Display_Loc0x0_Res2560x1440 @12:22:42
-PersistentWindows: no need to restore fresh session Display_Loc0x0_Res2560x1440 @12:22:42
-PersistentWindows: Display settings changed Display_Loc0x0_Res2560x1440__Display_Loc2560x0_Res2560x1440 @12:22:43
-PersistentWindows: Start restoring window layout back to 3/22/2023 12:21:38 AM for display setting Display_Loc0x0_Res2560x1440__Display_Loc2560x0_Res2560x1440 @12:22:44
-PersistentWindows: Restore finished in pass 2 with 2 windows recovered for display setting Display_Loc0x0_Res2560x1440__Display_Loc2560x0_Res2560x1440 @12:22:49

OS: Windows 10 pro Version 22H2 build 19045.2788

**Comment by kangyu-california** [comment]
My reasoning is that either the monitor or the OS generates transient off-on-off event sequence while the monitor is going off, triggering auto restore which eventually caused the monitor to awake.

The fix is to run PW with -delay_auto_restore 5 where you can adjust the delay value accordingly.
