### ISSUE TITLE
Feature request: Disable Ctrl click the window function

### ISSUE THREAD

**Issue by sovalyeler** [kangyu-california/PersistentWindows#222]
Hi. Thanks for this awesome program, been using it for nearly couple of years now.
I have a request for you. I switch between browsers a lot and copy & paste stuff between them. Sometimes I do that very fast, without realizing that I'm still pressing ctrl key. And while doing that and some other stuff fast, I try to close a tab by pressing ctrl+w. At that times, an automatic window switching might occur. Which disrupts my work flow, even makes me accidentally close a tab that I don't want to close. I couldn't figure out the reason behind this window switching up until today when I read about "Manipulate the window z-order" in help page. Is it possible to disable that feature? Or disable ctrl modifier key for PW?

**Comment by kangyu-california** [comment]
Please try the new [patch](https://github.com/kangyu-california/PersistentWindows/files/11114340/PersistentWindows5.41p222.zip)

**Comment by kangyu-california** [comment]
Try latest 5.43_0914 patch hidden in the 5.43 release page

**Comment by kangyu-california** [comment]
Try [PersistentWindows5.43_0919.zip](https://github.com/kangyu-california/PersistentWindows/files/12666966/PersistentWindows5.43_0919.zip)
If this patch still does not fix the issue cleanly, run the patch with command option
-foreground_background_dual_position=0
