### ISSUE TITLE
Support for iconified windows

### ISSUE THREAD

**Issue by Vampire** [kangyu-california/PersistentWindows#223]
It would be nice if iconified windows would be supported.

What I mean is for example Slack, Discord, Team, Outlook, jEdit, Process Manager, ShareX and others.
All these can be iconified into the icon tray.
Some by clicking their tray icon to iconify and also deiconify,
some by closing with Alt+F4 or x-button to iconify and clicking the tray icon to deiconify,
some only by closing with the x-button to iconify (Alt+F4 would quit) and clicking the tray icon to deiconify,
some by minimizing to iconify and clicking the tray icon to deiconfiy,
some by closing to iconify and double-clicking the tray icon to deiconify,
some by pressing ESC to iconify and clicking the tray icon to deiconify.

If I'm docked and have three displays available I for example have on one monitor 2-3 chat applications arranged to keep an eye on them.
But if I'm undocked and only have the laptop display at my disposal, I want most of these chat windows to be iconfied.

So it would be super nice if iconified windows would also be supported.
As there is no standard way how it works, I envision some necessary training or configuration per application that should be supported for this,
so that you can configure how to iconfiy and deiconify a specific application and then it can be managed.

**Comment by kangyu-california** [comment]
let's rephrase the request as supporting automatic window minimization in PW.

First of all PW is not designed to make its own mind on where window should be positioned. 
User needs to make the move first to let PW remember window position in current display configuration, and PW will automatically restore window position (including minimize/maximize status) when display config is changed back, such as dock/undock a laptop.

So I would think the request is very difficult to implement and unnecessary as well.

**Comment by Vampire** [comment]
Then you might misunderstood my request. :-)

When I switch from three displays to just the laptop display, I manually iconify some windows to save space.
I'd love if PW would recognize that and de-iconfiy those windows if I switch back to three displays and re-iconfiy if I switch back to just the laptop display again.

The settings I described are just because there is no standard way to iconify / deconify but an application-specific behavior to just hide or show the windows at certain conditions.

**Comment by kangyu-california** [comment]
You may use WIN D hot key (show desktop) to minimize all windows.

**Comment by Vampire** [comment]
I know that shortcut, thanks.
But unfortunately it is not in any way related to the feature I requested here.

**Comment by kangyu-california** [comment]
> When I switch from three displays to just the laptop display, I manually iconify some windows to save space.
User need to minimize the window in laptop-only mode manually (only once), and PW will remember the minimized status in that mode.
PW also provides "capture to disk" feature to reduce manual work.

> I'd love if PW would recognize that and de-iconfiy those windows if I switch back to three displays and re-iconfiy if I switch back to just the laptop display again.
Isn't this already achieved? PW is designed to restore window automatically when user switch display config.

**Comment by Vampire** [comment]
Sorry for the late reply.
Your two sentences in the last comment make me thing you still misunderstood.
iconfiy != minimize
![image](https://github.com/kangyu-california/PersistentWindows/assets/325196/2c1f9e17-9288-40a4-9b75-2b4dc84090a7)
1 is minimized, what you talk about
2 is iconified, which I talk about in this issue
