### ISSUE TITLE
Taskbar button of minimized windows is not restored to the correct display

### ISSUE THREAD

**Issue by Vampire** [kangyu-california/PersistentWindows#224]
I have a separate taskbar per display and have the taskbar button of a window where the majority of the window is displayed with these Windows settings:
![image](https://user-images.githubusercontent.com/325196/230041143-badee5a3-42ac-493d-bf40-cc67606ae13a.png)

Now if display configuration changes, the minimized window is displayed on the taskbar of the main display.
As soon as I restore the window it immediately jumps to the display where it should be, including the taskbar button.

So I guess the unminimized position is restored, and on restoring this unfolds.
I guess you might need to restore and then re-minimize a windows if it is already minimized and its unminimized position should be moved to a different display.

While cluttering the taskbar of the main display, it also feels bad that the window jumps to a different display on restore.

**Comment by kangyu-california** [comment]
While the request make some sense, please be aware that there is no standard API to manipulate minimized window icon position on taskbar.
I feel that the request could be better served with using Virtual Desktop feature of Windows 10, so that there is no more need to minimize any window, just switch between virtual desktops.

**Comment by Vampire** [comment]
That's unfortunatley not an option.
I need those windows minimized on the same desktop to keep an eye on them, for example if a number or icon or title string change suggests that there is some update to look at, and to occasionally restore it to use it together with the other windows on the same desktop.
Having the windows on another virtual desktop would plainly be unusable.

I am aware - or actually assumed - that there is no standard API.
That is why I mentioned the restore-move-reminimize_if_on_different_display procedure.
That during restoring this would cause the windows to shortly appear and then be minimized again would be fully acceptable for me.
Much more acceptable than that the window suddenly hops onto a different display as soon as I restore it like it is currently.
If you think other users might not like the hopping on restore but prefer the hopping during usage, then please make it an optional setting so that the user can choose.

**Comment by kangyu-california** [comment]
Can you try attached patch fix with new command option -accurate_taskbar_minimized_window=1
[patch](https://github.com/kangyu-california/PersistentWindows/files/11246616/PersistentWindows5.41p224.zip)

**Comment by Vampire** [comment]
That version does not work out too nice.
The window with which I tested was now on the right screen, also task-bar wise, but it was not minimized anymore.
And additionally various windows that were iconfiied suddenly half-way popped up on the main monitor, like TeamViewer, Sharepoint, XWin Msg Window, and a couple of others, most not even in any usable state but only the window decorations and a white content.

**Comment by kangyu-california** [comment]
Sorry for the flawed patch, here is a new one to try [patch2](https://github.com/kangyu-california/PersistentWindows/files/11264771/PersistentWindows5.41p224_2.zip)

**Comment by kangyu-california** [comment]
Final fix verified on my local setup [PersistentWindows5.41p224_3.zip](https://github.com/kangyu-california/PersistentWindows/files/11357824/PersistentWindows5.41p224_3.zip)

**Comment by kangyu-california** [comment]
Latest patch with unintended side-effects fixed
[PersistentWindows5.41p224_4.zip](https://github.com/kangyu-california/PersistentWindows/files/11391195/PersistentWindows5.41p224_4.zip)

**Comment by Vampire** [comment]
Sorry for the late reply, I just put the latest version from the release page in place and will test on Monday.
Will let you know if still something behaves strange. :-)

**Comment by Vampire** [comment]
Seems to work fine from a quick test, thanks
