### ISSUE TITLE
Windows 10 Virtual Desktop Switching Problems

### ISSUE THREAD

**Issue by natyusha** [kangyu-california/PersistentWindows#229]
When using multiple virtual desktops and navigating between them with the default windows hotkeys (Ctrl+Win+Left or Ctrl+Win+Right) there is an issue present only while persistent windows is open. This issues require the hotkeys for switching virtual desktops to be pressed in quick succession and then the Ctrl key to remain held down afterwards. Or to just switch virtual desktops too quickly.

As an example for reproducing this create 4 empty virtual desktops each with a notepad window preset then switch to the first (leftmost) one. Now hold down the Ctrl and Win keys then quickly double tap the right arrow key but do not release with Ctrl and Win keys. Eventually (within 1 second of holding down the Ctrl and Win keys) the virtual desktop will switch without having hit an arrow key again. This can also be triggered by simply switching back and forth too many times too quickly.

Interestingly, switching very slowly between desktops (feels like a little more than 500ms per hotkey press) does not trigger this issue.

**Comment by kangyu-california** [comment]
Could be the same issue as #222,
can you please try the [patch](https://github.com/kangyu-california/PersistentWindows/files/11114340/PersistentWindows5.41p222.zip)

**Comment by natyusha** [comment]
The patch resolved the issue. Thanks for the quick response and the great program.
