### ISSUE TITLE
No notification when new update is released

### ISSUE THREAD

**Issue by camsung** [kangyu-california/PersistentWindows#23]
Is it possible to have a notification whenever there is a new version available? Right now I have to manually check every time. Thanks!

**Comment by morrisonbrett** [comment]
Yep. Just go the upper right of this GitHub repo and select 'Watching'.

![image](https://user-images.githubusercontent.com/1159718/86516367-d0156180-bdd4-11ea-8fe9-c6f3e7d5b2a1.png)

**Comment by camsung** [comment]
Ah ok! This is the first time I've used Github so I didn't know about that. I've been searching forever for a solution to my windows moving to my main monitor after my screens sleep and this is the only fix that actually worked. Thanks so much for developing it!

**Comment by kangyu-california** [comment]
Hi camsung,

I am glad this utility works for you.

@morrisonbrett  Thanks for providing the tip!

**Comment by kangyu-california** [comment]
automatic update check is implemented in Release 5.0
