### ISSUE TITLE
Can you make it automatically unlock and then relock the taskbar afterwards?

### ISSUE THREAD

**Issue by i-report-bugs** [kangyu-california/PersistentWindows#236]
It seems the app can't restore the taskbar to the proper monitor when it's locked but I always accidentally resize it myself so I keep it locked.

Is there maybe a way you can unlock the taskbar first when it's locked and then relock it once it's moved to the proper monitor?

**Comment by kangyu-california** [comment]
Please try this [patch](https://github.com/kangyu-california/PersistentWindows/files/11710438/PersistentWindows5.42_p236.zip)
