### ISSUE TITLE
Persistent windows crashing

### ISSUE THREAD

**Issue by bmanctc** [kangyu-california/PersistentWindows#237]
I just noticed that it wasnt working so tried updating to the latest version, As soon as it starts it crashes. I will get the event viewer information. windows is updated, I just rebooted and tried starting with same results, I have it starting in task scheduler as well. 
Let me know what other information you need. I didnt have any event id of 990 so I just gave you the ones of the app crashing. 
[PW crash.txt](https://github.com/kangyu-california/PersistentWindows/files/11735884/PW.crash.txt)

Thank you for your help,

**Comment by kangyu-california** [comment]
The crash is due to github release page format change, which affect PW versions older than 5.41.
Please manually upgrade to latest version.

**Comment by bmanctc** [comment]
my apologies, I see it was still using the older version, I will make sure it is using the new version., Thank you!!!!
