### ISSUE TITLE
PersistentWindows doesn't restore windows to correct position after turning monitor off and then on again.

### ISSUE THREAD

**Issue by xXRaptorSc0pezXx** [kangyu-california/PersistentWindows#238]
I currently have 2 monitors connected to my PC: my main monitor (1440p) and a CRT TV (720p) which I use to watch old anime. When I turn off my main monitor, and then turn it back on, all my Windows have been resized to be really small as if they are sized to fit on the 720p monitor and they appear minimized in the upper left hand corner of my main monitor's screen instead of just being at the last size/position I had them at before turning off the monitor. This happens regardless of if the 2nd monitor is on or off when the first monitor is turned off.

Having all windows switch to appear on whatever monitor is active is just something Windows does and isn't something you can turn off, so PerisistentWindows should recognize when this is happening and restore windows to their correct positions upon turning the main monitor back on.

**Comment by kangyu-california** [comment]
I have no idea why PW does not work for you, although your display configuration is not very common.

As suggested in [readme](https://user-images.githubusercontent.com/59128756/190280503-a96ce57f-a6f0-4aad-9748-221bbb4f9207.png), please run Event Viewer, locate the "Windows Logs" -> "Application" section, then search Event ID 9990 and 9999, for example
PersistentWindows: Start restoring window layout back to 7/4/2023 11:48:25 PM for display setting xxxxx
PersistentWindows: Restore finished in pass 3 with 1 windows recovered for display setting xxxxx

These event logs provide vital information for diagnosis

**Comment by kangyu-california** [comment]
Please try [the latest patch](https://github.com/kangyu-california/PersistentWindows/files/12065409/PersistentWindows5.42_p240.zip)

**Comment by xXRaptorSc0pezXx** [comment]
I am already using the latest patch (5.42)

**Comment by kangyu-california** [comment]
The latest patch is a link you can download, it was generated yesterday

**Comment by xXRaptorSc0pezXx** [comment]
Oh okay. I'll try it out

**Comment by kangyu-california** [comment]
Run with admin privilege also helps.

**Comment by xXRaptorSc0pezXx** [comment]
YESSSSS IT SEEMS TO BE WORKING!!! If it starts being weird again I'll let you know, for now seems to be working fine though. Thanks!!
