### ISSUE TITLE
New update leaves user on the wrong virtual desktop

### ISSUE THREAD

**Issue by jmorgannz** [kangyu-california/PersistentWindows#241]
It seems like it is a new feature of PersistentWindows to quickly switch between virtual desktops in order to restore each set of windows on each desktop.
This is annoying to have happen when you come back to your PC and wake up the sleeping monitor - but I understand it.
Even though I understand it is the only way to properly restore windows on multiple VD's, it is annoying enough that it alone is considering making me stop using PW and just letting windows be misremembered.

However, the main issue is that it keeps leaving the wrong virtual desktop selected.
I always work on the left-most (primary) virtual desktop, and occasionally switch to the others for particular work.

Since the latest update, PW will consistently leave me on VD #6 (where #1 is the first), requiring me to manually switch back to VD #1 after each time PW restores window positions.

**Comment by kangyu-california** [comment]
The new behavior is necessary to fix #224, 

To disable the new behavior, run PW with following command argument
-accurate_taskbar_minimized_window=0

**Comment by jmorgannz** [comment]
> The new behavior is necessary to fix #224,

Thanks, appreciate that. 
However leaving the user on a random VD which they did not start on is a bug as far as I'm concerned.

**Comment by kangyu-california** [comment]
Try this [patch](https://github.com/kangyu-california/PersistentWindows/files/11988636/PersistentWindows5.42_p241.zip) which disables #224 fix in VD context

**Comment by jmorgannz** [comment]
Yes the patch works - so it's basically automatically applying -accurate_taskbar_minimized_window=0 correct?  
Can't PW just save the currently active VD when it saves window positons, then when it reapplies them, also recall the saved active VD?

**Comment by kangyu-california** [comment]
Some move window command has the side-effect of activating VD, this could be fixed by replace with command without activating the window (thus the VD), please try [patch2](https://github.com/kangyu-california/PersistentWindows/files/11992621/PersistentWindows5.42_p241_2.zip)

**Comment by jmorgannz** [comment]
Seems to work.
I can't tell if it's moving windows on the other VDs, but it isn't switching VDs during restore process now.

**Comment by kangyu-california** [comment]
@sovalyeler  one more patch [PersistentWindows5.43_p241.zip](https://github.com/kangyu-california/PersistentWindows/files/12098768/PersistentWindows5.43_p241.zip)

**Comment by kangyu-california** [comment]
The latest patch [PersistentWindows5.43_p239_240_241.zip](https://github.com/kangyu-california/PersistentWindows/files/12139138/PersistentWindows5.43_p239_240_241.zip)

**Comment by jmorgannz** [comment]
Hi,
I just let PersistentWindows update to the latest version today as it prompted me (I was still on one of the patched ones provided in this thread)

Straight away the problem has regressed back to how it was before. Soon as I wake up my monitor, windows restore position and I am left on a random VD that is not the one I was on previously.

I am not using the -accurate_taskbar_minimized_window=0 command line. I removed it when you supplied  PersistentWindows5.42_p241_2.zip - which seemed to work without it.

I thought that the fixes done would have been included in the latest release.  
I am now on 5.43.8598.19088

**Comment by kangyu-california** [comment]
The fix in 5.42/5.43 is still incomplete,
please try the latest patch
https://github.com/kangyu-california/PersistentWindows/files/12328561/PersistentWindows5.43_0812.zip
