### ISSUE TITLE
"About" window or some indication of the currently running version

### ISSUE THREAD

**Issue by anenviousguest** [kangyu-california/PersistentWindows#247]
As great as PersistentWindows is, I think it's UI is missing any indication of what version I'm currently running. IIRC it's only shown in the splash screen at startup, but this is it. 

I had few occurrences in the past where I wanted to see if i'm running the latest patch version and had to stop-start the app just to see a splash screen, which is a rather clumsy workaround.

**Comment by kangyu-california** [comment]
The version info is displayed when moving mouse over the PersistentWindow icon in the System Tray area on taskbar.

![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/31d946a9-06d3-47fe-9625-e26c04bec4e6)

**Comment by anenviousguest** [comment]
lol, indeed! Closing the ticket then.

Thank you!
