### ISSUE TITLE
Certain apps do not seem to get restored to positioning. 

### ISSUE THREAD

**Issue by Doxmia** [kangyu-california/PersistentWindows#25]
Hey, glad that someone picked up the PersistentWindows project - I like the saving state option you added, it's very helpful. 

I use Sticky notes for little things (the built-in Windows version) and I've noticed that they do not restore their positioning (even when manually saving).

**Comment by Doxmia** [comment]
As an update to this, "Discord" also does not seem to be restored to it's previous position. (This is running Persistent Windows as Admin or not).

**Comment by kangyu-california** [comment]
Thanks for the feedback. 
These issues will be addressed in future release 4.28

**Comment by kangyu-california** [comment]
Hey,

Not sure which version and which OS do you encounter this problem.

I have tested 4.27 which restores sticky notes windows without problem on windows 10.

**Comment by Doxmia** [comment]
I am using the version 5.26. I am using Windows 10 Pro 1909. OS build 18363.900.

Most apps seem to move correctly, so far (from what I use day to day) it has only been my Sticky Notes and Discord window. I can repeat it on demand with the manual snapshot/manual restore nor does it work from wakeup.

**Comment by Doxmia** [comment]
Sorry I meant 4.26. I tried upgrading to 4.27 and Sticky notes s till don't get restored (neither does Discord). One thing I have noticed as well with the manual save to disk/restore is that sometimes it just completely fails - the notification pops up but it just doesn't restore **any** Windows for some reason. Maybe like 25% of attempts? I don't really use that feature often myself, just thought it was an odd quirk.

**Comment by kangyu-california** [comment]
Try 4.28
I am still not convinced about this issue. Sticky notes does not seem to have any difference from other window.

**Comment by Doxmia** [comment]
That seemed to have fix Discord but sticky notes still don't get restored. Not sure if it matters but I have multiple sticky notes open. In settings my Stick Notes is version 3.1.53.0 (not sure if that matters or not). 

I've tried quitting Sticky Notes then opening it while Persistent Windows is running, nothing I do seems to move the notes back to their original places. In the old Persistent Windows there used to be a console that would show movements, is there any way I can pop that up to see if mine is showing anything useful?

**Comment by kangyu-california** [comment]
My sticky notes version is 3.7.140.0, you may upgrade from window store.

The console UI feature has been removed, also the .log file dump is disabled for released build.

Ordinary users can retrieve a summary of restore in event viewer. (search for event 9990)

As for power users,  they can always compile a debug version and check .log file by themself.

**Comment by Doxmia** [comment]
I updated and looks like Sticky notes is good! With Discord working it looks like this issue is good on my end, I'll close this off!

Thanks again.
