### ISSUE TITLE
New Outlook

### ISSUE THREAD

**Issue by PaleMoonRanch** [kangyu-california/PersistentWindows#251]
I just switched to "New Outlook" and PersistentWindows is not remembering its last window location.

**Comment by kangyu-california** [comment]
Not reproducible. Please wait 3 seconds or more to make sure PW captures the new location.

**Comment by PaleMoonRanch** [comment]
I'm not talking child windows.  I've left Outlook open for hours.  I keep it on screen 2.  Every time I close it and reopen it moves to screen 1.  Only started after I turned on "new Outlook".

**Comment by kangyu-california** [comment]
The new outlook window is no different from other windows from PW's perspective.
It restores fine on my desktop.
![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/bd16a373-acf8-48f3-a700-4481cfc58e62)
