### ISSUE TITLE
creating task in Task Scheduler by clicking auto_start_pw.bat fails

### ISSUE THREAD

**Issue by rml9ty** [kangyu-california/PersistentWindows#252]
Upon running the file as administrator I'm getting the following error:

_Processing -File 'C:\Program' failed because the file does not have a '.ps1' extension. Specify a valid Windows PowerShell script file name, and then try again._

(The file "auto_start_pw_aux.ps1" is in the same folder.)

Using the most current version, 5.43. I'm on Windows 11 22H2 build 22621.2134.

**Comment by kangyu-california** [comment]
Try latest 5.43_0914 patch hidden in the 5.43 release page

**Comment by yCodeTech** [comment]
@kangyu-california Norton 360 anti-virus completely removes some of the files as it's reporting that they have "bad" reputation with the file being released "less than a week ago". I doubt it's a less than a week, considering the date stamp on this thread. Is there anything we can do?
