### ISSUE TITLE
Fullscreen game minimizes on launch when PW is running

### ISSUE THREAD

**Issue by Presuffix** [kangyu-california/PersistentWindows#253]
When Persistent Windows is running, Mass Effect Legendary Edition keep minimising on launch. The game keeps running, but it minimises on launch and when trying to get it to appear. This does not happen when i quit Persistent Windows. 
So far this is the only game that exhibits this behaviour for me. It is the steam version, which opens the EA Desktop app, then the mass effect legendary full-screen launcher. It is only when starting Mass Effect 1 from that launcher, after which it enables HDR mode, that Mass Effect minimises. 
This is on windows 10 (22H2, 19045.3448, up to date), with a RTX 3080 (nvidia drivers 537.34, up to date), and Persistent Windows (5.43, up to date).

**Comment by kangyu-california** [comment]
Try [PersistentWindows5.43_0919.zip](https://github.com/kangyu-california/PersistentWindows/files/12666966/PersistentWindows5.43_0919.zip)
If this patch still does not fix the issue cleanly, run the patch with command option
-foreground_background_dual_position=0

**Comment by Presuffix** [comment]
That seems to have fixed it. Didn't need to run it with command options. Just unzipped it, ran it, and now Mass Effect 1 Legendary Edition no longer minimises when I launch it. I hope it sticks. Thanks!

**Comment by Presuffix** [comment]
I wanted to let you know that while the original issue is fixed - the game no longer minimises on launch - it has resurfaced in another form: when I alt-tab out and go back to the full-screen game, it doesn't let me load the game. I have even retried it with the command option active, but the issue persists.

**Comment by kangyu-california** [comment]
You may try command option -ignore_process "the_game.exe" on the latest patch 
[PersistentWindows5.43_0925.zip](https://github.com/kangyu-california/PersistentWindows/files/12718500/PersistentWindows5.43_0925.zip)

Substitute the right exe name in the command option

**Comment by Presuffix** [comment]
This seems to work for now. I added the argument and alt-tabbing in and out works fine while PW is running. Thanks!
