### ISSUE TITLE
Fullscreenizer bug

### ISSUE THREAD

**Issue by milkev** [kangyu-california/PersistentWindows#254]
**Description**
Using [Fullscreenizer](https://github.com/KasumiL5x/Fullscreenizer) and Persistent Windows in conjunction causes applications forced into borderless windowed to revert back to their original window size instead of filling up the screen. This issue does not happen when Persistent Windows is closed.

**Expected Behaviour**
Fullscreenizer still makes games fill up the screen when Persistent Windows is installed.

**Possible solution**
Add a way to exempt certain programs from being effected by Persistent Windows.

**Steps to repeat**
1. install & open both Persistent Windows & Fullscreenizer
2. open a game in windowed mode (such as minecraft which does not have a borderless fullscreen option)
3. use fullscreenizer to force the game into borderless windowed mode
4. focus the game

Before using fullscreenizer;
![image](https://github.com/kangyu-california/PersistentWindows/assets/22010128/fd440683-d797-4c18-bad1-090986a79c8c)

After using fullscreenizer (with persistent windows open); 
![image](https://github.com/kangyu-california/PersistentWindows/assets/22010128/8d888e7d-6f57-4208-abe4-5b9efc680883)

**Comment by kangyu-california** [comment]
[PersistentWindows5.43_0919.zip](https://github.com/kangyu-california/PersistentWindows/files/12666966/PersistentWindows5.43_0919.zip)
If this patch still does not fix the issue cleanly, run the patch with command option
-foreground_background_dual_position=0

**Comment by milkev** [comment]
this patch seems to fix it perfectly!

thank you so much <3
