### ISSUE TITLE
Why on earth did you put a nag screen when the program starts?

### ISSUE THREAD

**Issue by masterofobzene** [kangyu-california/PersistentWindows#257]
Why not making it silent-run?

Yes, I know there is a command to run silently, but why on earth did you make that as "optional" instead of the standard behaviour?

**Comment by kangyu-california** [comment]
The splash window exists for multiple reasons.
1. It helps first time user to accept the idea of systray app without main window.
2. It serves as an appreciation to all contributors of this project.
