### ISSUE TITLE
win11无法执行创建任务计划程序的脚本，代码版本5.43

### ISSUE THREAD

**Issue by BugIsNull4396** [kangyu-california/PersistentWindows#260]
提示信息如下：
![image](https://github.com/kangyu-california/PersistentWindows/assets/83123094/f91d1d33-4137-4a9c-92d4-7761e485719a)

**Comment by kangyu-california** [comment]
please follow the installation instruction in readme, do not execute the .ps1 file directly

**Comment by kangyu-california** [comment]
take a look at #284, task scheduler does not like specific user name
