### ISSUE TITLE
Taskbar icons disappear after windows come back from sleep or screen off

### ISSUE THREAD

**Issue by KhalilSecurity** [kangyu-california/PersistentWindows#263]
I like to start by extending my thanks to you for maintaining this must-have app for Windows. Since your whole app is built on fixing Window positions after Windows comes back from sleep or screen off, and I really trust your knowledge. I wanted to ask you on a related note if you have feedback on a similar Windows bug that also happens when Windows comes back from sleep or screen off. 
In addition to the windows positions bug, this bug causes taskbar icons to disappear when Windows wakes up from sleep or screen off. The only fix for it is to CRTL+SHIFT+ESC and restart Explorer.exe!! Microsoft engineers don't seem to have a fix for it yet, but there has been a huge discussion on MSFT forums regarding it 
https://answers.microsoft.com/en-us/windows/forum/all/icons-keep-disappearing-from-taskbar-windows-11/9164a1af-b558-4ab7-ab21-2ff5d2347838?page=1

Have you personally been affected by this issue? Did you find anything to could lead to this by working in your app and Windows libraries/dlls/ etc?

Thanks

**Comment by kangyu-california** [comment]
Windows 10 does not seem to be affected, although occasionally I need to restart PW to make its icon visible after reboot.

I did a little bit research on how to recover taskbar icons. This one might be what you want, although the problem it solves is the inverse of what you are asking for.
https://techforpassion.blogspot.com/2014/04/refresh-tray-icons-how-to-remove-dead-tray-icons-after-killing-program.html
