### ISSUE TITLE
Minimized windows being automatically maximized after screen unlock

### ISSUE THREAD

**Issue by shatteredhalo** [kangyu-california/PersistentWindows#264]
I am on version 5.46 of Persistent Windows.

I'm experiencing an issue where I will minimize one or more windows, lock my screen using WinKey + L, and upon unlocking my screen, Persistent Windows is maximizing those windows again. I am waiting well beyond the default capture time of 3-4 seconds and yet PW does not remember they are minimized and it will maximize them even if minutes have passed since they were minimized prior to screen lock and then unlock. 

The only way I've found to get Persistent Windows to "let go" of the affected minimized windows and stop automatically maximizing them again, is to close and reopen PW.

**Comment by kangyu-california** [comment]
Please try latest 5.47

**Comment by shatteredhalo** [comment]
Version 5.47 seems to have fixed this issue for now after a couple days observation. I will report back if I notice it cropping up again. Thanks!
