### ISSUE TITLE
Mouse movement issue on startup

### ISSUE THREAD

**Issue by mhwikicn** [kangyu-california/PersistentWindows#265]
After upgrading to 5.46, my mouse moves extremely slow/unresponsive while PersistentWindows starting.  Eventually the mouse goes back to normal after the program loading window shows up.  This happenes to both my laptop and desktop, all running Windows 10 22H2.

**Comment by the-real-vortex-v** [comment]
I was getting this issue tonight randomly. Start up wasn't my issue. I reinstalled the version before 5.46 and now it's stopped. I think something was hammering disk IO or some such.

**Comment by kangyu-california** [comment]
Apologies for insufficient test for 5.45/5.46, please try latest 5.47

**Comment by mhwikicn** [comment]
> Apologies for insufficient test for 5.45/5.46, please try latest 5.47

Issue is gone now, thanks!
