### ISSUE TITLE
Windows Terminal un-maximizes when simply left-clicked

### ISSUE THREAD

**Issue by Vampire** [kangyu-california/PersistentWindows#266]
I updated to 5.47 today from some earlier version.
I have Windows Terminal maximized on one monitor and a Chrome window maximized on a second monitor.
Focus is on the Chrome windows.
Now I just left-click the Windows Terminal to bring the focus to it.
This suddenly makes the Windows Terminal un-maximize.
If I "Pause auto restore" the behaviour stops, if I reenable it happens again.

When I restart PW, the behavior also does not happen initially.
But if I then unmaximize Windows Terminal and maximize it again, the behavior starts to happen again.

This is also a side-effect of the new `foreground_background_dual_position` feature.
If I disable it, it does not start to happen.

**Comment by kangyu-california** [comment]
Taking vacation now. Will look into it in Dec

**Comment by Roccoderra** [comment]
Hi, I have - probably - the same issue but with 3ds Max 2022.3
When left clicking on the 3dsMax window or in other cases still in the program doing modelling, and then suddenly Max goes down to the taskbar and then immediately disappears. Task manager shows that it became a Background Process and the only option is to end the task. 
It does this randomly, no other app is affected by this behavior.
https://gyazo.com/a21ed6c701a45b70d5a07499de04a2f1

Event Viewer shows this:
https://gyazo.com/31e1b6149f501af25d43ae045226f6b4

Above Vampire wrote he could disable that new feature, could you please explain how to do that in Powershell?

**Comment by Vampire** [comment]
However you start PW, add the parameter `-foreground_background_dual_position=0`

**Comment by Roccoderra** [comment]
Do you mean like this?

https://gyazo.com/2e27a29703a4d6bb17205a9504080fc0

**Comment by Vampire** [comment]
If PW works after rebooting you somewhere already autostart it. There you need to add the parameter.

**Comment by kangyu-california** [comment]
The bug has been fixed, please try [patch266](https://github.com/kangyu-california/PersistentWindows/files/13590888/PersistentWindows5.47_patch266.zip) so you don't have to deal with command options.

**Comment by kangyu-california** [comment]
Fixed in 5.48,  the dual position switching feature now requires Ctrl move/resize to activate.
