### ISSUE TITLE
Always move taskbar to 2nd monitor?

### ISSUE THREAD

**Issue by i-report-bugs** [kangyu-california/PersistentWindows#267]
Hello, I discovered that if I boot up my laptop without being connected to the external monitor, PersistentWindows will not restore the taskbar to the desired monitor when I plug the external monitor in later.

Would it be possible to make PersistentWindows always move the taskbar to a specified monitor as soon as the total number of displays changes?

It could come in the form of a launch flag so it doesn't affect the default behavior for other users

**Comment by kangyu-california** [comment]
The request is generalized as automatically restore from DB upon switching display.
This has been implemented in https://github.com/kangyu-california/PersistentWindows/releases/tag/5.49
The feature is on by default, user can turn off the feature using command option -auto_restore_new_display_session_from_db=0
