### ISSUE TITLE
windows11 auto start pw fail

### ISSUE THREAD

**Issue by jimmy8399** [kangyu-california/PersistentWindows#268]
![image](https://github.com/kangyu-california/PersistentWindows/assets/126844891/7938ba9d-c986-4624-860e-a4cf43c14b52)
i checking the readme , it still the same problem

**Comment by kangyu-california** [comment]
Not reproducible on my end. 
According to https://thedroidguy.com/how-to-fix-task-scheduler-error-0x80070057-problem-1154158, anti-virus software might be blocking the install script from running.

**Comment by jimmy8399** [comment]
no im not using ant antivirus atm

**Comment by kangyu-california** [comment]
Not reproducible.

**Comment by kangyu-california** [comment]
see #284, task scheduler does not like specific user name
