### ISSUE TITLE
Window snaps to the mouse position after moving

### ISSUE THREAD

**Issue by RARgames** [kangyu-california/PersistentWindows#269]
On win 10 sometimes, one of the windows (different programs) starts to snap to mouse position after dragging it somewhere else e.g.
I move the window to the right of the screen, then I click on the left part of the screen and the window move there for no reason. (It only happens to one of the windows at a time). Sometimes it snaps to the mouse position, sometimes it returns to its original position.

When I exit the PersistentWindows the issue is gone.

**Comment by kangyu-california** [comment]
The window move is the result of a new feature called "foreground background dual position switching", which allows user to restore a foreground window to its previous background position/size/z-order with just one mouse click in the blank area of desktop window.

To suppress the feature, modify mouse click by holding Ctrl Alt keys.
To permanently disable the feature, run PW w/ command line -foreground_background_dual_position=0

For more details about dual position, please refer to help web page

**Comment by RARgames** [comment]
Thanks for a quick reply!
I just don't need that feature and `-foreground_background_dual_position=0` makes the program work how I wanted.
