### ISSUE TITLE
Feature Request - Disable Notifications

### ISSUE THREAD

**Issue by CorneliousJD** [kangyu-california/PersistentWindows#27]
Well first I want to say TAHNK YOU for this program. It's working wonderfully so far! I had a few quirks with the original, and another fork, before I found this one, and I'm glad to see you still actively update it! 

The other fork I was using (https://github.com/lukefor/persistentwindows) did not show a notification upon logging back in and it engaging to restore the windows. 

A simple checkbox on the right click menu of the tray icon to enable/disable this notification may be nice. I'd prefer to not see it every time I log back in, but it's not a huge issue.

I also prefered the origianl icon to the new updated one, not that the icon would stop me from using this. Just tossing in my unwanted 2 cents ;) 

Thanks again for the hard work on this!

**Comment by kangyu-california** [comment]
Thanks for the feedback, the request will be addressed in next release (4.29), estimated date is around 7/25

**Comment by CorneliousJD** [comment]
Wonderful, thanks again, this app has really saved me a ton of time everytime I walk away and lock my PC and my DisplayPort monitor goes to sleep!

**Comment by kangyu-california** [comment]
Please try 4.29
