### ISSUE TITLE
Option to run as CLI with arguments to save/restore

### ISSUE THREAD

**Issue by jessicah** [kangyu-california/PersistentWindows#272]
I'd like to be able to run on demand from a script to immediately save/restore window positions, e.g. from an automation task that puts only a selection of multiple monitors to sleep, and restore after turning monitors back on.

**Comment by kangyu-california** [comment]
PW is designed to work out of box for most users without turning to CLI option.

If you really crave for CLI mode, try https://github.com/caoyue/WindowResizer
