### ISSUE TITLE
New Modern Icon

### ISSUE THREAD

**Issue by endrigocostaluiz** [kangyu-california/PersistentWindows#274]
Hello, the app worked perfectly for me, I am grateful for that.

I would like to indicate an update of the taskbar icon to be more harmonious with Win11,
Here are some options:

https://www.flaticon.com/free-icon/layout_721644?related_id=721644

https://www.flaticon.com/free-icon/window-display_8053601?term=window&page=1&position=86&origin=search&related_id=8053601

https://www.flaticon.com/free-icon/pop-up_4621078?term=window&page=3&position=52&origin=search&related_id=4621078

https://www.flaticon.com/free-icon/restore_4929693?term=window&page=6&position=45&origin=search&related_id=4929693

https://www.flaticon.com/free-icon/window_9168270?term=window&page=7&position=91&origin=search&related_id=9168270

**Comment by kangyu-california** [comment]
Thanks for the suggestion, I have played a little bit with those modern-looking icons, it seems the smooth looking curves do not look well when the icon is scaled down to standard size (32x32).

I just refined the original PW icon a little bit by smoothing out the color unevenness, and it looks not too bad on Windows 11
![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/f39b017e-beef-492d-9a69-ccc6e23e5671)

It has been a challenging task to design an icon that looks harmonious across all color schemes, especially for a programmer without graphic design background. Hence I encourage PW users to submit new icon designs to help improve the product.

**Comment by kangyu-california** [comment]
Try [PersistentWindows5.48_patch274.zip](https://github.com/kangyu-california/PersistentWindows/files/13773142/PersistentWindows5.48_patch274.zip)

User can replace the default PW icon by copy pwIcon.ico (or pwIcon.png) into 
C:\Users\\[User]\AppData\Local\PersistentWindows

**Comment by kangyu-california** [comment]
Closed in https://github.com/kangyu-california/PersistentWindows/releases/tag/5.49

**Comment by kangyu-california** [comment]
Just redesigned the icon,
Windows 10 ![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/eddd2abb-a257-493f-9729-058dec662dce)
Windows 11 ![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/d411c71e-1789-4250-9f47-bb388720ee06)

**Comment by kangyu-california** [comment]
Newly designed icon
![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/7443e478-6910-491d-b3af-f70c3a7157f1)
![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/3a71000e-972a-4331-87af-b1118d71c96c)

Please try the latest patch2 from https://github.com/kangyu-california/PersistentWindows/releases/tag/5.49_patch

**Comment by kangyu-california** [comment]
Fixed in https://github.com/kangyu-california/PersistentWindows/releases/tag/5.50
