### ISSUE TITLE
System tray minimized windows are not stored/restored

### ISSUE THREAD

**Issue by Templayer** [kangyu-california/PersistentWindows#279]
Hi! A great piece of software! And something that should have been a part of Windows itself by default!

You know what else should have been a part of Windows by default but isn't? Being able to minimize any window into the system tray.

For that, I am using another third-party utility. The somewhat niche problem here is that these two third-party applications do not work together.

The utility is called RBTray. I forgot which version, I had it installed since about 2017. Probably not the newer github fork.

It enables me to minimize any window into the system tray by RIGHT-clicking the standard minimize button.

Incredibly useful to declutter stuff.

Currently, I'm using it for four things: A command line (a bat file), a server application, Internet Lock and Fling (Fling has its own way to be minimized into the system tray, but its background tasks are stealing focus unless I use this third-party utility instead).

_EDIT: This also occurs for applications that do not need RBTray, like qbittorrent!!!_

![image](https://github.com/kangyu-california/PersistentWindows/assets/11728067/abb7e1e7-8649-4002-b614-e4646744d153)

It's something I cannot live without. :p 

### Now - steps to reproduce the problem:

1. We have an application we want to put into the system tray - it is currently at the size we want it to stay as:

![image](https://github.com/kangyu-california/PersistentWindows/assets/11728067/31b756b3-a12d-42f2-9e6f-0d3fc5b963c2)

2. We minimalize it to the system tray:

![image](https://github.com/kangyu-california/PersistentWindows/assets/11728067/67a8fbf6-2941-4038-9c95-dfcfe792b60e)

3. Now we just have to disconnect a DisplayPort monitor without any other screen being present, thus making every window tiny. Other windows are restored to their original glorious size by PersistentWindows. But the system tray ones, however, are not. Deminimalizing it by clicking on it on the system tray yields this result:

![image](https://github.com/kangyu-california/PersistentWindows/assets/11728067/6e8ecd93-a51d-4883-93ca-d9966fd9f791)

**Comment by Templayer** [comment]
Strange. After restarting the computer (and eventually unplugging and replugging a DisplayPort monitor), now it kinda works - upon being deminimized from the system tray, qbittorrent (i.e. not using RBTray), a CMD window and a server application all flicker in the low resolution and then their resolution is restored to how it was before the DisplayPort monitor was turned off, as it should be. 

![image](https://github.com/kangyu-california/PersistentWindows/assets/11728067/f95cc289-7fea-48e8-9119-20c50a8ca47f)

Now a question stands - why didn't it work at first?

Welp, spoke too soon. Because Fling, on the other hand, did not get restored:

![image](https://github.com/kangyu-california/PersistentWindows/assets/11728067/105d4f11-14d3-4254-8808-6cc1c43c68b5)

**Comment by Templayer** [comment]
> Welp, spoke too soon. Because Fling, on the other hand, did not get restored:
> 
> ![image](https://private-user-images.githubusercontent.com/11728067/295467450-105d4f11-14d3-4254-8808-6cc1c43c68b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Njc3NzUsIm5iZiI6MTcwNDg2NzQ3NSwicGF0aCI6Ii8xMTcyODA2Ny8yOTU0Njc0NTAtMTA1ZDRmMTEtMTRkMy00MjU0LTg4MDgtNmNjMWM0M2M2OGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA2MTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YjEwZDk1OGM5YzllNzQwNDgzOTQ1OTljZGJhMDU1ZjRjYmRhMzg3OWMxMjI1ZTNlOTk0YjA2YzJmMmM3MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.72dOv-ywMo05N-YC3ZYPm_Fn2hv2P0RRf0TZCgOKJYg)

Hmm, maybe Fling WAS restored to what has been stored before, and I just forgot to adjust the window after the next-to-last DisplayPort replugging. Welp, NOPE, checked the logs and no Fling restoration in sight.

AND it looks like my normally minimized Explorer windows didn't get restored either. Which is a bummer, since that is the main reason why I got this application:

![image](https://github.com/kangyu-california/PersistentWindows/assets/11728067/0c2e7ee3-82a2-4fbc-8692-b74d9883d949)

[FlingDidn'tGetRestoredAndNeitherDidExplorerWindows.zip](https://github.com/kangyu-california/PersistentWindows/files/13883874/FlingDidn.tGetRestoredAndNeitherDidExplorerWindows.zip)

**Comment by Templayer** [comment]
Notepads failed to be autorestored as well. From being minimized normally, not into a system tray (i.e. this should be a standalone issue, but maybe the source problem is the same)

![image](https://github.com/kangyu-california/PersistentWindows/assets/11728067/a6f9a5f6-d9b3-457a-b8b1-9e2c3e4a2da4)

**Comment by kangyu-california** [comment]
Please try https://github.com/kangyu-california/PersistentWindows/releases/tag/5.49_patch

**Comment by Templayer** [comment]
> Please try https://github.com/kangyu-california/PersistentWindows/releases/tag/5.49_patch

Haven't tried it yet, but I did tests twice more each morning after turning on a DisplayPort screen.

Yesterday, all of my RBTray system tray minimized applications restored fine, but qbittorrent didn't - then I misclicked on it again in the tŕay, thus minimalizing it back to the system tray. Clicking on it a third time produced a window with a restored size!

Today, everything in the system tray got restored properly, except for Fling.

Also, before those tests, I tested if failure to restore a window will fix itself in time. It didn't, the windows stayed tiny for hours.

**Comment by kangyu-california** [comment]
The issue is rbtray minimize/unminimize operation failed to trigger event required for PW.
here is the fix.
![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/be1cdd8a-d1ee-471b-8929-9e80d51cb6b0)
Please download the fixed rbtray version from
https://github.com/kangyu-california/rbtray/tree/main/x64

**Comment by Templayer** [comment]
> The issue is rbtray minimize/unminimize operation failed to trigger event required for PW. here is the fix. ![image](https://private-user-images.githubusercontent.com/59128756/296517730-be1cdd8a-d1ee-471b-8929-9e80d51cb6b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTIwODgsIm5iZiI6MTcwNTE5MTc4OCwicGF0aCI6Ii81OTEyODc1Ni8yOTY1MTc3MzAtYmUxY2RkOGEtZDFlZS00NzFiLTg5MjktOWU4MGQ1MWNiNmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDAwMjMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxY2JiNTliNWE4YjdhYzBlMTc3MjAxNTRjMWQ5YmFkYWU5NzJmOGMyZmYzMmEwNDM1ZDM2OWI2ODI1NDBkMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._KF5ifWk3Q02RHfNajyck_o9baJZbu1ofT3f13QtghE) Please download the fixed rbtray version from https://github.com/kangyu-california/rbtray/tree/main/x64

Well, that failed spectacularly (on their end, not ours... I hope): https://github.com/benbuck/rbtray/issues/112

**Comment by kangyu-california** [comment]
The feature to "minimize window to system tray" is now available in PW.
Just click the minimize button of the window while holding Ctrl key.

Please try the latest patch2 from https://github.com/kangyu-california/PersistentWindows/releases/tag/5.49_patch

**Comment by kangyu-california** [comment]
Formal release https://github.com/kangyu-california/PersistentWindows/releases/tag/5.50

**Comment by kangyu-california** [comment]
New patch release with improved reliability to ctrl minimize window to notification tray
https://github.com/kangyu-california/PersistentWindows/releases/tag/5.50_patch
