### ISSUE TITLE
Restore Z-Order Not Working

### ISSUE THREAD

**Issue by CorneliousJD** [kangyu-california/PersistentWindows#28]
Hey all, so I know Z-Order is still experimental, but I wanted to share logs from it.

PersistentWindows: Restore zorder succeeded by repositioning window "Inbox - email@redacted.domain - Outlook" (00050FA6) under "Telegram" (00010D30)

Those two programs are on opposite ends of my monitor and those windows are never near eachother. 
I'm not sure how Windows handles the Z-Order of windows that don't even overlap. 
There's even an instance of this talkign about apps on 2 different monitors completely and where it's positioning their Z-order.

This happens on just about everything and I think because so many windows are open across different screens things end up restoring out of order still in the long run. 

If I can be of more assistance here just let me know, subscribed to replies.

**Comment by kangyu-california** [comment]
The bug will be fixed in next release 4.29 as well.

Thanks
