### ISSUE TITLE
The application is not ready for people that have Aero Snap and other garbage features disabled

### ISSUE THREAD

**Issue by Templayer** [kangyu-california/PersistentWindows#280]
The application has problems restoring items that are purposefully off-screen with a single-monitor setup.

Perhaps this should be a checkbox setting somewhere: "Store off-screen coordinates in single-monitor setups". The default value would probably be false, as this is a niche issue.

Anyway, it also spams the logs if there are a lot of such windows. And the option to disable writing about this in the log would be rather nice. Once again - false by default.

Yes, I am an old-timer, and I tend to just put a window mostly offscreen if I want to get rid of it without minimalizing it instead of using virtual desktops, sue me. :D

A rather bizarre example - For Subtitle Workshop Classic, I want the most height available to me for layout practicality reasons. I do not need the window decorations and window header. So I just... move the header upwards, off-screen (in a single-monitor setup, nonetheless). Yup, I'm an old-timey arsehole.

![image](https://github.com/kangyu-california/PersistentWindows/assets/11728067/5bd47ad5-d017-490f-a1a0-d27764d6e11a)

I haven't checked if this gets restored properly into the negative y coordinates as it should (in my niche case), because I always close this application before shutting off the DisplayPort screen. This is an example of what I wish to store and restore.

But poor logs for some of the other stuff. Like Explorer windows. 
[LogSpammingForGitIssue.zip](https://github.com/kangyu-california/PersistentWindows/files/13881055/LogSpammingForGitIssue.zip)

**Comment by kangyu-california** [comment]
You may run PW with -fix_offscreen_window=0

**Comment by Templayer** [comment]
> You may run PW with -fix_offscreen_window=0

Ah, thank you!
