### ISSUE TITLE
PW can't restore explorer windows

### ISSUE THREAD

**Issue by sovalyeler** [kangyu-california/PersistentWindows#282]
Steps to repo:
1. Open up an explorer window(Win+E), go to any directory.
2. Capture windows to disk.
3. Close the window.
4. Restore windows from disk.

However, PW only opens "This PC" explorer window.
(Win10 22H2 19045.3803)
(-fix_zorder=1 -delay_auto_restore 2.5 -foreground_background_dual_position=0 -invoke_multi_window_process_only_once=0)

**Comment by kangyu-california** [comment]
This is expected, PW does not know what directory the explorer window was at.

**Comment by kangyu-california** [comment]
PW does not remember directory information within explorer window. The capability to directory in restored explorer window must be a feature of Windows OS. It seems the feature is deprecated.

**Comment by kangyu-california** [comment]
Will try

**Comment by kangyu-california** [comment]
Fixed in https://github.com/kangyu-california/PersistentWindows/releases/tag/5.50

**Comment by kangyu-california** [comment]
Add a new fix to 5.50 to recover special folder name such as "3D Objects"

**Comment by kangyu-california** [comment]
New fix to improve the reliability of ctrl-minimize window to notification tray
https://github.com/kangyu-california/PersistentWindows/releases/tag/5.50_patch

**Comment by kangyu-california** [comment]
try https://github.com/kangyu-california/PersistentWindows/releases/tag/5.52
