### ISSUE TITLE
Not working with RPD full screen

### ISSUE THREAD

**Issue by 42jerrykim** [kangyu-california/PersistentWindows#285]
There is a bug where if you are using Windows RDP in fullscreen and then switch, it will change to windowed mode.

**Comment by kangyu-california** [comment]
Please provide details on how do you "switch" out of RDP fullscreen mode without normalize or minimize the window first.

**Comment by 42jerrykim** [comment]
I am using a KVM switch and only one of the two monitors is connected to the KVM.

If I change the PC on the kvm, it will recognize the new monitor and this is where the problem occurs.

I'm using 5.50 version

**Comment by kangyu-california** [comment]
PW works by recalling the history.
In your case, when kvm switches, It is Windows OS that decides to put the RDP window to normal mode, and PW has no history data to restore from.
The workaround is to hook another set of keyboard/mouse to the PC, and manually restore RDP window to full screen, and remember to capture the windows to disk as additional history backup. So next time when kvm switches, PW will be able to restore from history data automatically.
