### ISSUE TITLE
CTRL + Click minimize won't work on active window

### ISSUE THREAD

**Issue by AgentKazy** [kangyu-california/PersistentWindows#286]
Love the feature, but I've found that I can't use it if the window is active/in focus. Only when I change focus to another window or click on the task bar/desktop, then it's possible to use CTRL click minimize on the unfocused/non-active window to send it to the notification area.

It should work on all windows, active or not, right?

EDIT: Some info: currently using dual-monitors (1080p & 1440p) with DP on an RTX 3080. PW version 5.50.8797.32500

**Comment by kangyu-california** [comment]
Try https://github.com/kangyu-california/PersistentWindows/releases/tag/5.50_patch

**Comment by AgentKazy** [comment]
That has fixed the issue and now both active and non-active windows can CTRL Minimize to tray! Thank you :)

**Comment by kangyu-california** [comment]
Reopen to avoid duplicated bug report

**Comment by kangyu-california** [comment]
Close with 5.51 release
