### ISSUE TITLE
[Request] alternative icon choice

### ISSUE THREAD

**Issue by behhNa** [kangyu-california/PersistentWindows#287]
Hello,

the new Icon is very obtrusive (for me) and flashy.
Is there a way to enable the old one with a parameter?

If the alternate old icon is no option... would it be possible to load the pwIcon.png (or .ico) directly from the program folder instead of the AppData folder? (In this case an option to add a custom pwIconBusy.png would be nice too.)

Personally I would prefer the choice between old and new icon set. But maybe it's just me.
Nevertheless, thanks for this amazing peace of software! I love it and don't want to miss it anymore. :)

**Comment by kangyu-california** [comment]
Try https://github.com/kangyu-california/PersistentWindows/releases/tag/5.51

**Comment by m4rkh4wk** [comment]
The 5.50 icon was also very similar to the icon for the antivirus product AVG. This new one is definitely safer in the event their legal department found this project. :)
