### ISSUE TITLE
Tray icon gone for PersistentWindows

### ISSUE THREAD

**Issue by Templayer** [kangyu-california/PersistentWindows#288]
PersistentWindows is running, but there is no tray icon.

![image](https://github.com/kangyu-california/PersistentWindows/assets/11728067/9fe9488b-5eea-45d9-b611-4b1de6619450)

Furthermore, I do not know how to kill it with grace instead of killing it forcibly.

This sometimes happens with other tray icons too.

Maybe now that the minimize to tray feature is done, a persistent tray icons feature could be added that is capable of refreshing the system tray? First run 10 seconds after the tray is loaded on startup for the first time, then every minute or so?

Or maybe some other solution would be better.

**Comment by kangyu-california** [comment]
This is caused by Windows OS, especially after a long system upgrade, the only known cure is to reboot the machine.

**Comment by kangyu-california** [comment]
according to https://github.com/kangyu-california/PersistentWindows/issues/263
you may also try to kill & restart explorer from task manager

**Comment by Templayer** [comment]
> This is caused by Windows OS, especially after a long system upgrade, the only known cure is to reboot the machine.

It might be, but not from an update. I'm using Win7 and I haven't updated for half a year. Yet currently PersistentWindows is running and it has no tray icon...

> according to #263 you may also try to kill & restart explorer from task manager

Yes, but I would prefer not to do that repeatedly when it happens (if I were to do that then why would I be using PersistentWindows instead of "simply" resizing all windows manually each time? Same logic applies). It's easier to kill and relaunch the offending application instead, but in this case, I cannot do that graciously, I would have to murder it.

One workaround would be to add a parameter to the exe that enables it to search for an existing instance and issue it a quit command before trying to start (thus restarting it).

**Comment by kangyu-california** [comment]
I don't have Windows 7 machine on hand, please try [PersistentWindows5.51_patch288.zip](https://github.com/kangyu-california/PersistentWindows/files/14159266/PersistentWindows5.51_patch288.zip)

**Comment by Templayer** [comment]
> I don't have Windows 7 machine on hand, please try [PersistentWindows5.51_patch288.zip](https://github.com/kangyu-california/PersistentWindows/files/14159266/PersistentWindows5.51_patch288.zip)

I have restarted my computer in the meantime. Which is something I do bimonthly... thus I am unable to test it properly, for now.

But thanks for doing it. We will have to wait until it happens again, one way or another.

:(
