### ISSUE TITLE
A secondary modal window for Magix Vegas Studio Pro disappeared (but still existed)

### ISSUE THREAD

**Issue by Templayer** [kangyu-california/PersistentWindows#292]
In the middle of the screen, you can see a smaller fake-modal rendering window. To the right of that, a scripted true modal window for batch rendering can be seen.

![image](https://github.com/kangyu-california/PersistentWindows/assets/11728067/5e299d72-fe3e-4a69-b329-5d6e97f834b8)

If you take a look at the taskbar, you can see that the secondary (true, at least in principle) modal window is really part of the main window - it doesn't appear in the task manager, cannot be minimized, etc. While its parent window cannot be clicked into, it is still possible to use the minimize button to minimize both the main window and the modal window (looks hacky as crud, though).

It currently looks like after a prolonged period of being minimized, the PersistentWindows might have put it offscreen (offscreen coordinates are enabled - for other reasons) somehow - I do not have a printscreen of that, because it eventually resets after a render is done. Maybe a log analysis is in order?

I've been using Vegas (formerly known as Sony Vegas Studio Pro) since 2008 daily, and I have never seen this behaviour, up until now (and I haven't been rendering much after getting PersistentWindows). The window still exists, but as it is a hacky modal window (from a batch script that I believe is one of the default preinstalled Vegas scripts), can't see it anywhere to even minimize or unmimize it. After finishing rendering the current video, the modal window closes and reopens - at that moment, everything returns to normal.

This is a low-priority thing. It's merely an inconvenience, as I am unable to pause the render.

Logs:
[A secondary modal window for Magix Vegas Studio Pro disappeared.zip](https://github.com/kangyu-california/PersistentWindows/files/14185911/A.secondary.modal.window.for.Magix.Vegas.Studio.Pro.disappeared.zip)

**Comment by kangyu-california** [comment]
The secondary window can not be modal as you are able to minimize it's parent window, although the parent window can not be clicked into by some magic.
I am not convinced the issue is caused by PW or can be fixed here, please compare PW with rbtray for fairness.

**Comment by Templayer** [comment]
>  I am not convinced the issue is caused by PW 

And neither am I.

> PersistentWindows **might have** put it offscreen

I have been using RBTray since WinXP with Sony Vegas. I do not know what SmartContextMenu is.

How do I "compare" these applications?

Did you check the logs? Is something interesting there?

**Comment by kangyu-california** [comment]
When ctrl click the main window, PW only minimize the main window. PW has no idea of the existence of the two child windows.

**Comment by kangyu-california** [comment]
Please consider buy me a coffee (https://www.buymeacoffee.com/kangyu.california) next time when submitting a new "bug" or new feature request.

**Comment by Templayer** [comment]
> When ctrl click the main window, PW only minimize the main window. PW has no idea of the existence of the two child windows.
> 
> The event log method requires running PW with -debug_process "<SonyVegasStudio....>.exe", which won't help because your definition of modal window is different from "A modal window creates a mode that disables user interaction with the main window but keeps it visible, with the modal window as a child window in front of it."

I have never ever right-clicked a Vegas window's minimize button, nor have I ever used CTRL+left click on it.

This is not a minimize to tray issue, as Vegas was never before minimized to tray on my computer.

**Comment by kangyu-california** [comment]
Whether click the minimize button of main window, PW only minimize the main window. PW does not operate on the two child windows.

**Comment by Templayer** [comment]
> Please consider buy me a coffee (https://www.buymeacoffee.com/kangyu.california) next time when submitting a new "bug" or new feature request.

I was. Until I found out that you close issues faster than the time I took creating them in the first place, without even properly checking them out first.

It's hard liking people who want money from people who are testing and reporting what seems like bugs.
Microsoft does that. And I'm not going to pay them for anything either.

Bye.

**Comment by Templayer** [comment]
> Please consider buy me a coffee (https://www.buymeacoffee.com/kangyu.california) next time when submitting a new "bug" or new feature request.

I was. Until I found out that you close issues faster than the time I took creating them in the first place, without even properly checking them out first.

It's hard liking people who want money from people who are testing and reporting what seems like bugs.
Microsoft does that. And I'm not going to pay them for anything either.

Bye.

> When click the minimize button of main window, PW only minimize the main window. PW does not operate on the two child windows.

The standard left click doesn't act that way, and CTRL+left click was never used before on Vegas (nor the right-mouse button for RBTray) - https://www.youtube.com/watch?v=61x0Ttn1vGo (wait for it to finish uploading and processing, if it didn't)

**Comment by kangyu-california** [comment]
If the child "modal" window has been moved by mouse before, PW will attempt to restore its position when unminimize the main window. This behavior may conflict with the app which also actively reposition its child windows.
To avoid the behavior, hold Ctrl Shift key when moving these windows, this tells PW to not track the position change for them.

**Comment by Templayer** [comment]
> If the child "modal" window has been moved by mouse before, PW will attempt to restore its position when unminimize the main window. This behavior may conflict with the SonyStudio app which also actively reposition its child windows. To avoid the behavior, hold Ctrl Shift key when moving these windows, this tells PW to not track the position change for them.

That's too impractical.
