### ISSUE TITLE
The screen ratio is scaled

### ISSUE THREAD

**Issue by KhalilSecurity** [kangyu-california/PersistentWindows#293]
Filmora has been going crazy after screen comes back on, spamming me the message the screen ratio is scaled. Could that be related to a recent update (it started happening last 3 months)?

![2](https://github.com/kangyu-california/PersistentWindows/assets/51271290/6fa7cba9-0f40-4275-ae55-48bd65bc8f4d)
![1](https://github.com/kangyu-california/PersistentWindows/assets/51271290/861f780b-af54-46bd-8e89-25c76e12bf42)

**Comment by kangyu-california** [comment]
Is this happening on Win11?
Starting from 5.45 release (around 10/2023), PW has DPI (scale ratio) awareness feature to improve text sharpness of its menu & dialog, but that is supposed to affect only PW itself.
You may pause auto restore from menu to test if the issue still exist.

**Comment by KhalilSecurity** [comment]
> Is this happening on Win11 only or affecting Win10 as well? Starting from 5.45 release (around 10/2023), PW has DPI (scale ratio) awareness feature to improve text sharpness of its menu & dialog when monitor has a scale ratio other than 100%. but that is supposed to affect only PW itself. ![image](https://private-user-images.githubusercontent.com/59128756/303439497-75815534-6f34-4492-bdc2-c92ac9ea9ca8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MjEzMTgsIm5iZiI6MTcwNzQyMTAxOCwicGF0aCI6Ii81OTEyODc1Ni8zMDM0Mzk0OTctNzU4MTU1MzQtNmYzNC00NDkyLWJkYzItYzkyYWM5ZWE5Y2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE5MzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZmQ0ZTYzM2M5Yjg2ZjdiMTJiNmZmYTUxMzg0Yzc4MWYzZjA0MDZlNmExMGI3YTA1NGMyMzMyNzg1NDQwZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9ZzdeS5ve-8H04B3wkt4RdXicNyGt3-74t_7MLd_Bgo)
> 
> You may pause auto restore from menu to test if the issue still exist. Or revert to release 5.43

Thanks for your quick response. I'm using Windows 11, and my display is at the default 100%. Could there be another feature causing this? the only affected app is filmora, and I'm going to contact their support as well to see if this is something they can fix in their end.

**Comment by kangyu-california** [comment]
There are several Win11 specific issues likely related to scale ratio (#289, #293 and #276), these may not be a coincidence.
I made a speculative fix to disable calling related DPI awareness function during capture/restore for Windows 11.
You may try
[PersistentWindows5.51_patch289.zip](https://github.com/kangyu-california/PersistentWindows/files/14205294/PersistentWindows5.51_patch289.zip)

Another possibility is that Filmora want to manage window position on its own, so maybe try PW  command line -ignore_process "filmora.exe" to avoid PW touching that window.

**Comment by KhalilSecurity** [comment]
Those are great options provided. Thank you
Testing patch now and will report back.

**Comment by KhalilSecurity** [comment]
Unfortunately, neither solution worked.
Note that I used this as task scheduler arguments
-delay_start 10 -ignore_process "Wondershare Filmora.exe"

**Comment by kangyu-california** [comment]
I think we have skipped the most important step, i.e. verify whether the issue is related to PW or not, 
To do that, the following procedure is recommended
1. capture existing windows to disk
2. exit PW
3. try to reproduce the problem by put monitor/PC to sleep & wake up
4. relaunch PW, restore window position

**Comment by kangyu-california** [comment]
Just created win11 branch to remove the dpi awareness code, the new win11 patch is in 5.51 release page,
https://github.com/kangyu-california/PersistentWindows/files/14227995/PersistentWindows5.51_win11_patch.zip
