### ISSUE TITLE
Multiple work station setups

### ISSUE THREAD

**Issue by galapogos01** [kangyu-california/PersistentWindows#294]
Hi there,

First of all thanks for an awesome app!

My situation is that I run a different monitor setup at work and at home. I'd like PersistentWindows to remember the window sizes & locations for each of these. At the moment when I work from home I need to re-locate all of my windows, then again when I return to work.

Does this make sense? Is it possible?

**Comment by kangyu-california** [comment]
This feature is supported from day one, just try out.

**Comment by galapogos01** [comment]
Can you describe how it works? When I switch setups, it does not restore correctly.

**Comment by kangyu-california** [comment]
One common user issue is to shutdown PC when switching display setups.
The fix is to put PC into sleep instead.

Without further details about the issue, it is hard to offer help here.

**Comment by galapogos01** [comment]
I am putting the laptop to sleep.

Effectively there are three working screen setups:

1. Laptop mode
2. Desk 1 (work - monitor A)
3. Desk 2 (home - monitor B)

When I unplug from Desk 1, sleep the machine then plug into desk 2, I am not getting windows restored to the last position for either Desk 1 or Desk 2.

**Comment by kangyu-california** [comment]
Could be a known issue #267, pls try the latest patch from the 5.51 release page, the download link is
https://github.com/kangyu-california/PersistentWindows/files/14227995/PersistentWindows5.51_win11_patch.zip
