### ISSUE TITLE
program crashes when trying to run "capture windows to disk"

### ISSUE THREAD

**Issue by REMvisual** [kangyu-california/PersistentWindows#296]
the autostart bat doesnt work returns simular errors to what was emntioned, i set up a custom task so thats fine.

my issue is after running the application it crashes when trying to capture windows to disk.

these are the 2 errors from event viewer -
Log Name:      Application
Source:        Application Error
Date:          2/15/2024 3:27:36 PM
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          SVR-011\Demon
Computer:      SVR-011
Description:
Faulting application name: PersistentWindows.exe, version: 5.51.8805.37929, time stamp: 0x65c703d2
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2792, time stamp: 0x3091b6fb
Exception code: 0xe0434352
Fault offset: 0x000000000006567c
Faulting process id: 0x0x47A0
Faulting application start time: 0x0x1DA60667C87C5F0
Faulting application path: C:\STANDALONE\PersistentWindows5.51\PersistentWindows.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8441e8f5-5e39-4893-b4fd-14558eaed12f
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-15T23:27:36.1511594Z" />
    <EventRecordID>4822</EventRecordID>
    <Correlation />
    <Execution ProcessID="2592" ThreadID="14368" />
    <Channel>Application</Channel>
    <Computer>SVR-011</Computer>
    <Security UserID="S-1-5-21-669700717-3829510566-1986451189-1001" />
  </System>
  <EventData>
    <Data Name="AppName">PersistentWindows.exe</Data>
    <Data Name="AppVersion">5.51.8805.37929</Data>
    <Data Name="AppTimeStamp">65c703d2</Data>
    <Data Name="ModuleName">KERNELBASE.dll</Data>
    <Data Name="ModuleVersion">10.0.22621.2792</Data>
    <Data Name="ModuleTimeStamp">3091b6fb</Data>
    <Data Name="ExceptionCode">e0434352</Data>
    <Data Name="FaultingOffset">000000000006567c</Data>
    <Data Name="ProcessId">0x47a0</Data>
    <Data Name="ProcessCreationTime">0x1da60667c87c5f0</Data>
    <Data Name="AppPath">C:\STANDALONE\PersistentWindows5.51\PersistentWindows.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data Name="IntegratorReportId">8441e8f5-5e39-4893-b4fd-14558eaed12f</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          2/15/2024 3:27:36 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      SVR-011
Description:
Application: PersistentWindows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.String.Substring(Int32, Int32)
   at PersistentWindows.SystrayShell.Program.OutputHandler(System.Object, System.Diagnostics.DataReceivedEventArgs)
   at System.Diagnostics.Process.OutputReadNotifyUser(System.String)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(System.IAsyncResult)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-15T23:27:36.0673510Z" />
    <EventRecordID>4821</EventRecordID>
    <Correlation />
    <Execution ProcessID="18336" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>SVR-011</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: PersistentWindows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.String.Substring(Int32, Int32)
   at PersistentWindows.SystrayShell.Program.OutputHandler(System.Object, System.Diagnostics.DataReceivedEventArgs)
   at System.Diagnostics.Process.OutputReadNotifyUser(System.String)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(System.IAsyncResult)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

</Data>
  </EventData>
</Event>

and these are the 9990 , 9999:

Log Name:      Application
Source:        Application
Date:          2/15/2024 3:29:31 PM
Event ID:      9990
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      SVR-011
Description:
The description for Event ID 9990 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows:  5.51.8805.37929; OS version: Microsoft Windows NT 10.0.22621.0; .NET version: 4.0.30319.42000

The message resource is present but the message was not found in the message table

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application" />
    <EventID Qualifiers="0">9990</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-15T23:29:31.4271812Z" />
    <EventRecordID>4827</EventRecordID>
    <Correlation />
    <Execution ProcessID="11392" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>SVR-011</Computer>
    <Security />
  </System>
  <EventData>
    <Data>PersistentWindows:  5.51.8805.37929; OS version: Microsoft Windows NT 10.0.22621.0; .NET version: 4.0.30319.42000
</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application
Date:          2/15/2024 3:27:28 PM
Event ID:      9990
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      SVR-011
Description:
The description for Event ID 9990 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows: Snapshot 1 is captured

The message resource is present but the message was not found in the message table

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application" />
    <EventID Qualifiers="0">9990</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-15T23:27:28.2157486Z" />
    <EventRecordID>4820</EventRecordID>
    <Correlation />
    <Execution ProcessID="18336" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>SVR-011</Computer>
    <Security />
  </System>
  <EventData>
    <Data>PersistentWindows: Snapshot 1 is captured
</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application
Date:          2/15/2024 3:27:05 PM
Event ID:      9990
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      SVR-011
Description:
The description for Event ID 9990 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows:  5.51.8805.37929; OS version: Microsoft Windows NT 10.0.22621.0; .NET version: 4.0.30319.42000

The message resource is present but the message was not found in the message table

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application" />
    <EventID Qualifiers="0">9990</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-15T23:27:05.3862467Z" />
    <EventRecordID>4819</EventRecordID>
    <Correlation />
    <Execution ProcessID="18336" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>SVR-011</Computer>
    <Security />
  </System>
  <EventData>
    <Data>PersistentWindows:  5.51.8805.37929; OS version: Microsoft Windows NT 10.0.22621.0; .NET version: 4.0.30319.42000
</Data>
  </EventData>
</Event>

thanks!

**Comment by kangyu-california** [comment]
try [PersistentWindows5.51_296_patch.zip](https://github.com/kangyu-california/PersistentWindows/files/14309088/PersistentWindows5.51_296_patch.zip)

**Comment by kangyu-california** [comment]
released in https://github.com/kangyu-california/PersistentWindows/releases/tag/5.52
