### ISSUE TITLE
Snapped windows are not always restored to their original position.

### ISSUE THREAD

**Issue by vnicolici** [kangyu-california/PersistentWindows#3]
Thanks for your work on this Kang Yu, if you have a PayPal account I would be happy to send a few bucks.

The latest version, 2.5, seems to work better compared to previous versions regarding restoring snapped windows, but unfortunately sometimes it still fails to restore them properly.

Not sure what about my particular hardware triggers it, but this is what usually happens:

I have two windows snapped left and right on my secondary display. I let the displays enter sleep mode then, after a minute or two, I move the mouse to wake the displays from sleep.

First the main display wakes up, and I can temporarily see the two windows snapped left and right on it, while the secondary display where they were originally still wakes up.

When the secondary display finally finishes waking up the windows disappear from the main display, then they show on the taskbar of the secondary display (I configured that taskbar to only show the windows on that display), but they are not actually visible. They seem minimized.

If I click on their icon on the task bar the two windows become visible, on the secondary display, but they are not snapped left and right anymore, instead they seem to be in the position they were before snapping them.

Sometimes both windows are restored properly. Sometimes only one of the two windows. Looks like some kind of race condition.

If it matters my setup is NVidia RTX 2080, Asus ROG PG348Q 3440x1440 primary display, Samsung U23H850 4K secondary display, both connected through DisplayPort.

If there is anything I can do to help debug this let me know. While I'm not very familiar with Windows programming, I'm a software developer myself, and I might be able to help.

**Comment by kangyu-california** [comment]
Thanks for the detailed feedback.
Looks like display port and 4K is the key factor to trigger the issue, I will try to reproduce the issue with similar setup.
While i am working on debug the issue, one alternative you can try is to add a login/wake password for Windows, my hunch is that this will add some delay and force the two monitor to work in sync.

**Comment by kangyu-california** [comment]
I can consistently reproduce the issue using remote desktop session. Debug shows that Windows OS undos what PersistentWindows is trying to do, especially for snapped windows.
I have no clue why Windows want to do that, and not sure what is the right solution for this.
In V2.6, this issue is mitigated by double calling restore routine, in 1 second interval.
This workaround is not perfect, but it seems working for me.
Let me know how it works

**Comment by kangyu-california** [comment]
I believe V2.7 fixed snapped window issue.

**Comment by vnicolici** [comment]
I'm still on 2.6, and I haven't been able to reproduce the issue for the last 2 days. I'll try 2.7 as well.

**Comment by kangyu-california** [comment]
2.6 basically resolved snapped window issue, but introduced a bug causing task manager window to flicker every one second when trying to correct unexpected WindowPlacement change but fails every time.
2.7 fixed that flicker window bug by trying to fix sudden WindowPlacement change only once, then accept the status quo without further attempt to correct it.
So 2.7 is preferred version with less bug, without sacrificing the snapped window capability.

**Comment by vnicolici** [comment]
I used 2.7 for a few days, I didn't experience any issues with it either. Thanks for fixing this.
