### ISSUE TITLE
Feature Request: Remember Taskbar Locations 

### ISSUE THREAD

**Issue by Djinnistorm** [kangyu-california/PersistentWindows#30]
Real quick, thank you for this. I've been looking for a solution to this, on and off, for...years? 

Anyway, as title. The displayport windows issue also takes the taskbar and returns it to the primary monitor, even when locked. If it's possible to remember the position of the taskbar and put it back as well, that would be fantastic. Thanks regardless though!

**Comment by kangyu-california** [comment]
Hi,

Restore taskbar is supported in V4.x versions. There are some requirement to use this feature

1. make sure taskbar is unlocked  (i.e. movable by mouse)
2. do not move mouse during window restore, usually taskbar is the first window to be restored,

**Comment by Djinnistorm** [comment]
Oh I see, the bar didn’t return because I had locked it in that position. In that case this does everything to circumvent the issue, thanks again!
