### ISSUE TITLE
Hiding windows-quake-terminal creates new tray icon every time

### ISSUE THREAD

**Issue by jannispl** [kangyu-california/PersistentWindows#300]
It seems that there is some weird behavior when running PersistentWindows along with [windows-quake-terminal](https://github.com/flyingpie/windows-terminal-quake/releases) (version 1.6)

Whenever I use the provided hotkey (ctrl+`) to hide the quake terminal, a new tray icon appears in my notification area:

![307791656-df128b0f-8f7f-41f4-a6a7-99565c1ed35d](https://github.com/kangyu-california/PersistentWindows/assets/838818/c9c82fce-2e2a-436f-af4b-80349d44afd6)

Taskbar settings reveal that it comes from PersistentWindows:

![grafik](https://github.com/kangyu-california/PersistentWindows/assets/838818/725d63a0-8e61-4f58-ad3c-93f8da1b857e)

Also reported with windows-quake-terminal here: https://github.com/flyingpie/windows-terminal-quake/issues/121

**Comment by kangyu-california** [comment]
Ctrl + ` causes Terminal window to minimize, which in turn triggers PW to receive Ctrl + window minimization event combination, which is interpreted as hide the window icon to System tray (a new PW feature since 5.5x)

The workaround is change the hot key to something like Alt + `
![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/526fb937-47a5-460a-bfa1-18910b5c3494)

**Comment by jannispl** [comment]
@kangyu-california I don't really want to change my hotkeys as that would cause conflicts in other apps I use. Is there a way to disable the "hide to system tray" feature?

**Comment by kangyu-california** [comment]
In the next release I will add a new command option to allow user to reconfigure the hotkey (among Ctrl, Alt or Shift).

**Comment by kangyu-california** [comment]
Try [PersistentWindows5.52_patch289300.zip](https://github.com/kangyu-california/PersistentWindows/files/14468211/PersistentWindows5.52_patch289300.zip) with new command option
-ctrl_minimize_to_tray=0

**Comment by jannispl** [comment]
> Try [PersistentWindows5.52_patch289300.zip](https://github.com/kangyu-california/PersistentWindows/files/14468211/PersistentWindows5.52_patch289300.zip) with new command option -ctrl_minimize_to_tray=0

Working as expected!
