### ISSUE TITLE
Why does it move my taskbar when moving my mouse after terminating abandonware?

### ISSUE THREAD

**Issue by masterofobzene** [kangyu-california/PersistentWindows#301]
What does this do with the mouse cursor? everytime I end playing an abandonware lower res game and I don't wait 3, 4 seconds after finishing it, it breaks havok on my desktop

**Comment by kangyu-california** [comment]
Please try latest patch [PersistentWindows5.52_patch289_301.zip](https://github.com/kangyu-california/PersistentWindows/files/14621044/PersistentWindows5.52_patch289_301.zip)
