### ISSUE TITLE
PersistentWindows cannot restore Webex window position

### ISSUE THREAD

**Issue by igorlord** [kangyu-california/PersistentWindows#302]
PersistentWindows works great for all Windows on my laptop except for Webex window.  I can Save a snapshot, and then I move the Webex window and Restore the snapshot, but the Webex window does not even move.  (I do not care about Z-order -- I just care about the position.)

I've tried with with the regular 5.52 update and the "nodpi" version.

FWIW, I've three monitors, each with different resolution. One is 90-degrees rotated.

The event log is attached.
[PersistentWindows_March15.zip](https://github.com/kangyu-california/PersistentWindows/files/14621095/PersistentWindows_March15.zip)

**Comment by kangyu-california** [comment]
Could not reproduce, webex window restores fine on my PC, snapshot restores also works fine
Please try run PW with admin privilege.

**Comment by igorlord** [comment]
Thank you!  That worked.  It looks like my work installed some "security" system, and now PersistentWindows stopped being about to run at startup with admin privs. I'll see what I can do to persuade it to do it anyway. (After starting it manually with admin, it moves and resizes WebEx, so we are good.)
