### ISSUE TITLE
Skip positioning an OS startup

### ISSUE THREAD

**Issue by csm10495** [kangyu-california/PersistentWindows#307]
Hey folks,

I've noticed that a few seconds after Windows startup, it tries to position my Windows how I last had them before shutdown. Can there be a setting to skip auto-positioning specifically after Windows startup (or I guess initial application startup?)

**Comment by kangyu-california** [comment]
The command option is 
-auto_restore_new_display_session_from_db=0

**Comment by csm10495** [comment]
Thanks!
