### ISSUE TITLE
Latest version has hijacked my Alt-Q shortcut for Chrome

### ISSUE THREAD

**Issue by elimjohnson** [kangyu-california/PersistentWindows#308]
Not sure how to remedy this.  Just recently upgraded PW and whenever I use the Alt-Q command in chrome to switch tabs, I get an extremely annoying popup to navigate tabs in a horrible manner...through push buttons of all things.  It has a PW logo in the top/left corner.  When I turn PW off, the unwanted behavior goes away.  Turn PW back on, the behavior is back.  Can't seem to find where the option to turn this off is.

**Comment by kangyu-california** [comment]
the command option to turn off hotkey window new feature is 
-hotkey_window=0

**Comment by elimjohnson** [comment]
And where do I input this command?

**Comment by kangyu-california** [comment]
Depending on how you launched PW,
If you launch PW from task scheduler, you may modify the command option of the task from Actions dialog.
Or you may create a .bat or a shortcut from the PW exe, where you can enter command options.

**Comment by elimjohnson** [comment]
Thank you, modifying the target in the startup folder worked.  I am curious now though, why would this feature be on by default.  It really should be off by default.  Experienced users will know how to turn it on if they even want it I would think.  Be great if features that hijacked other installations were off by default.

**Comment by kangyu-california** [comment]
PW has the potential to offer much more features than originally planned. 
Taking the hotkey feature for example, one of its goal is to offer an universal way to manipulate web tabs across ALL browsers, using a single key stroke.
Your case to switch the recent used tab is a perfect enhancement for next PW release.

I believe real experts should find it interesting, instead of false accusation of "hijack"

**Comment by elimjohnson** [comment]
It was not an accusation...it was just a statement of fact.  The latest release of PW, all the sudden, did hijack a shortcut I have had setup in Chrome for many years.  It just did, I was given no options at the time of upgrade or afterwards to turn it off.  Hence the term, hijack.  I do not say this with malice.  I love PW, you have done a great job.  But major software manufacturers get ripped apart time and time again for unsolicited changes like this.  "Unsolicited" meaning the collective user base, not just the users who did request the feature.  Introducing new features that may interfere with people's ability to function as they normally do without being asked...not such a great idea.  I'm sure the feature is great for someone's purposes that I don't understand as I am not an "expert," but should not be "ON" by default.  Or, at the very least be accessible from a GUI where it can easily be switched on or off.  Even I would have been able to figure that much out without having to bother you.  And evidently offending you which was not my intent.

As an electrical engineering consultant, I have many clients.  Although similar, no two have all the same requirements and I would be making a huge mistake in assuming as much.  Software design works on much the same principle basically.

I am not sure what you mean by "experts" and I would take no offense regardless, but I just counted and I have nearly 30 hotkey combinations in Chrome alone.  Many of the same in Brave and Firefox and a few more.  Regardless, I am no expert in whatever it is you are speaking of (I really don't even know)...just adapted each browser and other programs to my needs which has taken a lot of time and effort.

PW is great and I at least have a better understanding of it now.  Thanks

**Comment by schlangz** [comment]
Would be awesome if the shortcut could be set in the configuration file. My favorite game utilizes ALT+Q

**Comment by kangyu-california** [comment]
With 5.53 release, the default hotkey has been changed to Alt + W, which can be configured with command line, for example
-hotkey "X"             (this will change the hotkey to Alt + X)
