### ISSUE TITLE
Taskbar recovery not working since version 5.53

### ISSUE THREAD

**Issue by Stefan1200-de** [kangyu-california/PersistentWindows#309]
Older versions was able to move back the taskbar to its old position. Since upgrading to Persistent Windows 5.53.8857 this is not working anymore.

Using Windows 10 22H2

**Comment by kangyu-california** [comment]
Please try [PersistentWindows5.53_patch1.zip](https://github.com/kangyu-california/PersistentWindows/files/15055104/PersistentWindows5.53_patch1.zip)

**Comment by Stefan1200-de** [comment]
Just did a short/single test, but with Patch 1 it is working again.

**Comment by Stefan1200-de** [comment]
Even after a week, Patch 1 is working great here.
