### ISSUE TITLE
Unable to run - The system cannot execute the specified program.

### ISSUE THREAD

**Issue by caliban17** [kangyu-california/PersistentWindows#31]
Hello.  I've just downloaded & unzipped your program onto my windows10 64-bit machine, but when I run it I get the rather cryptic error: "The system cannot execute the specified program."  When I run as adminstrator I get the equally cryptic "the parameter is incorrect".
Hoping you can shed light.
Cheers

**Comment by kangyu-california** [comment]
Hi,

I would guess some dll file is outdated or missing in your OS, such as .Net framework 4.5 etc
please open event viewer, and check for errors under "Window Logs" -> "Application"

The latest version is 4.33, let me know whether it works or not

**Comment by caliban17** [comment]
Thanks for fast reply.  No I checked the logs and the only error "svchost (12980,R,98) TILEREPOSITORYS-1-5-18: Error -1023 (0xfffffc01) occurred while opening logfile C:\WINDOWS\system32\config\systemprofile\AppData\Local\TileDataLayer\Database\EDB.log." recurs about 10 times every day, so nothing to do with this?

**Comment by caliban17** [comment]
Just downloaded the master zip (4.33) and am totally mystified as the file/folder structure totally different and no executable persistentwindows.exe?

**Comment by kangyu-california** [comment]
I downloaded 4.33 from github and it unzips and runs fine,
Do you have anti-virus software on your PC which could silently quarantines unknown .exe file.

you may confirm this by trying other forks of PersistenWindows on github, such as https://github.com/lukefor/persistentwindows/releases

Anyway you may rebuild .exe on your own by download source code and compile it using Microsoft Visual Studio

**Comment by kangyu-california** [comment]
Just realized that you might have downloaded incorrect .zip file (4.33.zip or 4.33.tar.gz) which is purely source code.
You want to download the first one named PersistentWindows.4.33.zip which contains only binary release files.

**Comment by caliban17** [comment]
yes you are right, downloaded correct version but ver 4.33 has same problem "The system cannot execute the specified program." 
 or "the parameter is incorrect" when run as admin.
cheers

**Comment by kangyu-california** [comment]
Sounds like the file system is corrupted.
Here is what I got from googling

https://answers.microsoft.com/en-us/windows/forum/all/fix-this-parameter-is-incorrect-windows-10/79f8cc97-7395-4053-a99f-646f902b4820

**Comment by caliban17** [comment]
I tried this, it did say it repaired my system but still no luck.  Thanks a heap, for all your help, you've gone far beyond the bounds of what I expected, I won't waste your time any further, I'll continue to tinker myself in an effort to sort out my system - thanks and cheers.
