### ISSUE TITLE
After the computer wakes up, the brightness is very bright

### ISSUE THREAD

**Issue by pfugwtg** [kangyu-california/PersistentWindows#310]
When my computer wakes up from screen lock, the screen brightness becomes very bright. Then, if I try to change the brightness, it becomes normal.

System: Windows 10.0.19045

**Comment by kangyu-california** [comment]
Are you serious?
I have never thought calling the window moving APIs would have the side effect of boosting screen brightness.
It must be caused by something else, some software that is designed to control the screen brightness.
