### ISSUE TITLE
[Request] Option to auto skip missing windows

### ISSUE THREAD

**Issue by InMirrors** [kangyu-california/PersistentWindows#312]
A command line option to auto _restore_ missing windows is available currently, but there is no option to auto _skip_ missing windows. Could you please add an option to do so?

**Comment by kangyu-california** [comment]
Try [PersistentWindows5.43_patch2.zip](https://github.com/kangyu-california/PersistentWindows/files/15058576/PersistentWindows5.43_patch2.zip)
When invoking "Restore windows from disk" menu, holding both Ctrl and Shift keys down.

Command line option is inappropriate as that would totally defeat the purpose of restore from disk (i.e. restore missing windows)

**Comment by kangyu-california** [comment]
Alt key will make menu disappear.
I think it is easier to just press the "No to All" button once to skip all missing windows than to remember ctrl-shift combination for users.

**Comment by kangyu-california** [comment]
If you constantly restore from disk, and yet do not want to restore missing windows, you would be better served by using snap short capture/restore instead.
