### ISSUE TITLE
PersistentWindows won't run with 3rd party taskbar customization (StartAllBack, RetroBar etc)

### ISSUE THREAD

**Issue by Skyyblaze** [kangyu-california/PersistentWindows#318]
Ever since I got a 4k monitor as my primary display running at 150% scaling along with a 1080p display at 100% I've been searching for a way to stop different windows to resize randomly, especially when resolution changes happen or my primary monitor goes in Standby.

Someone suggested me PersistentWindows as a last resort and it sound promising however the program doesn't seem to run no matter if I run it as Administrator or not. It instantly disappears from TaskManager and the event log only shows these two things:

`Name der fehlerhaften Anwendung: PersistentWindows.exe, Version: 5.54.8887.42511, Zeitstempel: 0x6633348e
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22621.3447, Zeitstempel: 0x3d876852
Ausnahmecode: 0xe0434352
Fehleroffset: 0x00000000000653ac
ID des fehlerhaften Prozesses: 0x0x7D84
Startzeit der fehlerhaften Anwendung: 0x0x1DAA0EBFD4AB05A
Pfad der fehlerhaften Anwendung: J:\Downloads\Persistent Windows\PersistentWindows.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: f368d849-014b-4fcd-a7ff-3c69aa1f46ca`

`Anwendung: PersistentWindows.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.IO.DirectoryNotFoundException
   bei System.IO.__Error.WinIOError(Int32, System.String)
   bei System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   bei System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   bei System.IO.StreamWriter.CreateFile(System.String, Boolean, Boolean)
   bei System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding, Int32, Boolean)
   bei System.IO.File.InternalWriteAllText(System.String, System.String, System.Text.Encoding, Boolean)
   bei PersistentWindows.SystrayShell.Program.WaitTaskbarReady()
   bei PersistentWindows.SystrayShell.Program.Main(System.String[])` 

I'm running Windows 11 22631.3447 along with StartAllBack and ExplorerPatcher if it makes any difference. If I can provide any more info to help resolving this please let me know.

**Comment by kangyu-california** [comment]
PersistentWindows checks taskbar status to make sure its icon can be displayed normally.
It seems SmartAllBack replaced or altered system default taskbar implementation, causing PW to crash.

The workaround is to run PW with this command line option,
-wait_taskbar

For how to enter command options, check out #313

**Comment by Skyyblaze** [comment]
Thank you, just manually creating that directory seemed to do the trick for me, I'll play around with PersistentWindows later, thanks for the hard work!
