### ISSUE TITLE
RDP window positions are restored in correct location but out of order

### ISSUE THREAD

**Issue by kuriandungu** [kangyu-california/PersistentWindows#319]
While this is not a serious issue I thought i'd mention it.

This utility has been working superb for me over the years. However there is an update that was done and after it, persistentwindows doesnt remember the correct order after positioning of RDP windows. I have 3 Screens and on one screen I keep all my server windows open to monitor therm.
On this screen There are 3 RDP windows in a vertical format with Server1Window on top then Server2 and finally server3. that is the order they should appear in. 

However on reboot it will put the RDP server windows in the correct window positions but out of order such that its then Server1,Server3, Server 2. or sometimes 2,3,1 etc. 
This basically means that the first thing I do on rebooting is reorder my rdp windows.

I've tried renaming the windows hoping it was ordering them alphabetically. I also tried capturing the windows in different orders hoping one of them would result in them being restored in order. no attempt worked and it simply restores them on reboot, seemingly randomly.

Is there any fix,hack etc or do I just live with it as is.
Thanks again for such a wonderful utility.

**Comment by kangyu-california** [comment]
You may add -fix_zorder=1 to the command line when launching PW, here is how #313

**Comment by kuriandungu** [comment]
Many,many thanks for responding so quickly. I'll update as advised and monitor it. 
Thank you for this app, it's very useful.

**Comment by kuriandungu** [comment]
is this correct. 
D:\PersistentWindows\PersistentWindows.exe -fix_zorder=1
 its not worked consistently so i'm thinking i've put in the action bit incorrectly.
![ad3841c7-6879-4a62-8f23-c5e99bcd7c81](https://github.com/kangyu-california/PersistentWindows/assets/3868961/de12b252-7018-471b-8d1f-8422bcc6414a)

**Comment by kangyu-california** [comment]
I have attempted to improve the consistency of z-order fix in the past for several times.
my conclusion is that the issue is rooted from the Win32 APIs, which PW is unable to solve.

That is also the reason why the -fix_zorder=1 switch is off by default.
