### ISSUE TITLE
Windows Service

### ISSUE THREAD

**Issue by fraktal-sb** [kangyu-california/PersistentWindows#32]
would it be possible to run this program as a windows service?

**Comment by kangyu-california** [comment]
This is a matter of convenience and confidence.

I think standard user would prefer current simple "green" implementation, just unzip to run, delete folder to uninstall.

On the other hand, windows service requires admin privilege to install and uninstall.
From developer's point of view,  windows service imposes more restrictions on GUI implementation choices.

You can always run the program as startup job,  please see Readme for instructions.

**Comment by kangyu-california** [comment]
I have updated Readme document to recommend creating auto start task in Task Scheduler. 
That would be close enough to windows service.
Make sure to specify the task trigger as Begin the task "At log on"
