### ISSUE TITLE
Logging no longer works.  

### ISSUE THREAD

**Issue by AJolly** [kangyu-california/PersistentWindows#320]
Old versions - at least 2018 ones would create a PersistentWindows.log file.
New versions dont, even if im not using an argument to disable logging.

TBH, I'm not quite sure the new versions are working right, and was  trying to look at hte logs to help confirm.  

Also, any idea how this compares with windows's option to Remember location based on monitor connection?

**Comment by kangyu-california** [comment]
The log file mechanism was obsolete,  user should check event log in event viewer.
Besides event log, user can test the effectiveness of PW by trying snapshot capture/restore, or pause/resume auto restore.

"Remember location based on monitor connection" is only available on Win11. While PW has been tested to work for Win 7/10/11.
