### ISSUE TITLE
Firefox fulscreen youtube window resizes window after relogin

### ISSUE THREAD

**Issue by glebonator** [kangyu-california/PersistentWindows#322]
This might be a niche case, but it's driving me nuts in your otherwise amazingly helpful program.

Perhaps there's an easy way to address this, so my scenario is:

Win 11 x64, I watch youtube videos full screen in the browser (firefox, but not sure it matters) and when done, I either lock the screen, or windows times out itself and go do something else. The computer doesn't really go to sleep, but i believe it's called "turn off displays" where everything goes dark, there is no log-on window. I come back to it, press the keyboard, eventually log back in - bam that firefox window has been resized by PW to be the size of my entire display. This window's size is, of course, not workable, so I have to manually resize and drag it down.

Is there a way to detect that the browser window isn't REALLY that size, just that it was fullscreened by youtube? Is there an api to get to its "real" size? If you esc out of the player, it definitely pops back to the proper window size, so it's in there somewhere.

Thanks a lot!

**Comment by kangyu-california** [comment]
In full screen player mode, both the child window and the parent (root) browser window are expanded to full screen size, PW is unable to restore only the child window without affecting the parent window.

Instead user can play video in "picture in picture" mode, which launches a child independent of the parent window, then PW would be able to restore the child window alone without affecting parent window.

![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/1d18a06a-4248-413e-bff2-b02bb60691c1)

**Comment by glebonator** [comment]
Ah sad to hear. There is no picture-in-picture option or such icon in either FF or Chrome, not sure what you mean...

There is the "mini-player" icon which generates a tiny pop-up in the corner of just the browser, but if you press expand on it, it goes back to a regular window and there are no other controls.

**Comment by kangyu-california** [comment]
most videos have this pip feature on youtube
![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/28397ba2-dd9d-49c9-9952-71dedf4cb2a0)

**Comment by glebonator** [comment]
Don't have that at all... googling around you apparently have to right click on the video, then right click again, only then it shows "watch picture in picture" and plenty of results for it no longer working etc. Wouldn't rely on this, but thanks again!

**Comment by kangyu-california** [comment]
The pip icon is a dynamic one, you want to click into the video window to let it play,  then you will see the pip icon.
