### ISSUE TITLE
Forgets program window position/size after reopening it

### ISSUE THREAD

**Issue by samgubernick** [kangyu-california/PersistentWindows#326]
After opening a program, I can set the window position and size for each resolution, but when I close the program, PersistentWindows forgets all of those values. Is there any way to persist the window properties after reopening a program? Specifically, I'm seeing this issue after rotating the screen.

**Comment by kangyu-california** [comment]
you want to capture window to disk first to persist window properties before kill it, then you will be able to restore from disk.
Checkout readme for basics and online help for advanced topics.

**Comment by samgubernick** [comment]
I don't know if I have time to check this weekend but it isn't persisting it after rotating the screen. Restore from disk only captured the original rotation resolution (1920x1080), not the portrait one (1080x1920). If I have time, I'll take a look at the code to see what's going on, but figured you might know. Thanks!

![Screenshot 2024-06-07 104804](https://github.com/kangyu-california/PersistentWindows/assets/28270917/27d50b53-d91b-45c1-8717-ff0eff1dbe5d)

**Comment by kangyu-california** [comment]
Assuming rotate screen is done using Display Setting=>Display Orientation, the rotated display config also need be captured to disk before kill the chrome window.

**Comment by kangyu-california** [comment]
5.55 pre-release support auto inheritance of position history from killed window

**Comment by samgubernick** [comment]
I'm sorry I didn't have a chance to look into this earlier. 5.56 looks like it's working great. Thank you very much!
