### ISSUE TITLE
Holding down ALT key in Death Stranding causes persistent  window to flicker on and off rapidly.

### ISSUE THREAD

**Issue by the-real-vortex-v** [kangyu-california/PersistentWindows#331]
When I'm playing Death Stranding, I get a weird popup window appearing. I'm holding down ALT and moving my mouse and also holding the left mouse button. This stops me from playing my game as it steals the focus of the mouse and keyboard.

I found this in the help file: -webpage_commander_window=0   Turn off Alt+W hotkey for webpage commander window

Can we get this as a toggle option in the menu for people that want to enable/disable this? I had no idea about this "feature". Why is it in this program in the first place?

![image](https://github.com/kangyu-california/PersistentWindows/assets/93835445/dd1da0d9-fffd-4ea8-b022-aa59e54125a8)

**Comment by kangyu-california** [comment]
In latest patch [PersistentWindows5.54_patch6.zip](https://github.com/user-attachments/files/15934090/PersistentWindows5.54_patch6.zip),  user can deactivate Alt + W hotkey reserved for the webpage commander feature by pressing both Ctrl and left Win key when selecting Toggle webpage commander menu.

I would like to imagine internet surfing as the most common "game" for PC users, the new webpage commander feature helps user to play the internet surfing game in a renovated way.

If you would like to know more about the history of webpage commander, please take a look at #314

**Comment by the-real-vortex-v** [comment]
Thanks for the reply. This isn't an intuitive way to disable the "feature". It'd still be nice to have it in a clearly visible context menu. This feature will just get forgotten about or will remain unknown unless people search for the issue and may find this bug report.

Either way. Thanks for the information.
----
I just tried this and it isn't doing anything for me.

Left windows key + control and clicking on the menu item isn't doing anything. Alt+w still brings up the annoying "menu".

![image](https://github.com/kangyu-california/PersistentWindows/assets/93835445/461587da-0f77-42b3-9b42-f0649f5360cb)

**Comment by kangyu-california** [comment]
Menu is renamed to "Turn off webpage commander", without requirement to press Ctrl + LWin key
[PersistentWindows5.54_patch7.zip](https://github.com/user-attachments/files/15938020/PersistentWindows5.54_patch7.zip)

**Comment by kangyu-california** [comment]
Command option -webpage_commander_window=0 would totally disable the Alt + W hotkey hook, and removes the webpage commander menu option as well.
