### ISSUE TITLE
Using Batch instead of PowerShell to create task?

### ISSUE THREAD

**Issue by Hope-UwU** [kangyu-california/PersistentWindows#332]
Newbie technical support here.
I've been experimenting with PersistentWindows for a while in order to deploy it in my work environment.

Just recently, I stumbled upon this issue where PowerShell would refuse to run out of nowhere on some machines.
Upon a bit of investigation, it seems like Sangfor is the most likely culprit, as my company is in the process of switching from Kaspersky to Sangfor.

My current solution is to use Batch to create the scheduled task instead of PowerShell.
Is there any particular reason PowerShell is used in PersistentWindows instead of Batch to create scheduled tasks?

**Comment by kangyu-california** [comment]
It is a known issue (#284) that PW autostart PowerShell script may fail due to certain username get rejected by Windows OS, I don't think it is related to switching from Kaspersky to Sangfor as you guessed.

It seems to me the SCHTASKS dos command is less powerful (expressive) than the New-ScheduledTaskAction command in PowerShell.

If PowerShell script does not work, you may try startup folder method mentioned in #284 or the vb script method mentioned in README.

**Comment by Hope-UwU** [comment]
> It is a known issue (#284) that PW autostart PowerShell script may fail due to certain username get rejected by Windows OS, I don't think it is related to switching from Kaspersky to Sangfor as you guessed.
> 
> It seems to me the SCHTASKS dos command is less powerful (expressive) than the New-ScheduledTaskAction command in PowerShell.
> 
> If PowerShell script does not work, you may try startup folder method mentioned in #284 or the vb script method mentioned in README.

Thanks for your reply. I did some more testing today (running .ps1 script on a machine before and after installing Sangfor) and have confirmed that the issue is due to Sangfor blocking Powershell .ps1 file. I'll probably need to fallback to batch in my environment.

Here's my script to create the scheduled task to keep Google Chrome window on the POS's pickup screen. Anything you'd change/add here?

```
schtasks /create /sc onlogon /delay 0000:30 /tn "Pickup\StartPersistentWindows" /f /tr "'%~dp0PersistentWindows.exe' -splash=0 -check_upgrade=0 -auto_restore_missing_windows=1 -webpage_commander_window=0" /rl HIGHEST
```

**Comment by kangyu-california** [comment]
It seems task scheduler would stop the task silently after running for 3 days by default
![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/7a24956e-0a34-4b45-9177-9e3af7dca361)

The PowerShell script turns off that inconvenient "feature". Not sure if schtasks can do that.

**Comment by kangyu-california** [comment]
To workaround the 3 day limit, you may run the latest patch with command option -delay_start 20
there is no more need for /delay 0000:30 option in schtasks

[PersistentWindows5.54_patch9.zip](https://github.com/user-attachments/files/15962553/PersistentWindows5.54_patch9.zip)

**Comment by Hope-UwU** [comment]
Oh, I didn't know about that 3 day limit
I found /XML parameter might be able to work around that but haven't test it myself

`/delay 0000:30` is an arbitrary amount of time I figured might be enough for Windows to detect the order pickup screen (TV)

What does the argument `-delay_start 20`do? How would it work around the 3 day limit?

Also the POS is supposed to be shut down everyday after the retail closes. If that's the case maybe the 3 day limit won't affect my use case anyway?

**Comment by kangyu-california** [comment]
The -delay_start 20 would relaunch PW in 20+10 seconds, so the original task will finish and its status in task scheduler would be "Ready" instead of "Run", therefore would not suffer from the 3 day limit.

**Comment by kangyu-california** [comment]
I have updated README to add the schtasks Batch method as the second option, which also addressed the 3 day limit issue as well.

**Comment by Hope-UwU** [comment]
@kangyu-california 

Seems like you didn't add an instruction to override DPI scaling if the user uses schtasks to create a task. May I suggest adding that too?

In my case I use

```
REM Override High DPI Scaling
REG ADD "HKCU\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "%~dp0PersistentWindows.exe" /t REG_SZ /d "~ HIGHDPIAWARE" /f
```

**Comment by kangyu-california** [comment]
Thanks for the dpi setting patch, README has been updated

**Comment by Hope-UwU** [comment]
I don't see the `-delay_start` command line option in the Quick Help page. Is it an undocumented command line option?

**Comment by kangyu-california** [comment]
-delay_start was introduced in old PW releases to address failure to show icon on task bar. The command option is now obsolete, the original failure is now solved by auto restarting PW if task bar is not ready when starting PW.

**Comment by Hope-UwU** [comment]
@kangyu-california 
Did you happen to remove `delay_start` or rename it to `delay_restart` in 5.57?
I noticed the task status will be set to "Ready" only with `delay_restart` but not with `delay_start`

**Comment by kangyu-california** [comment]
@Hope-UwU yes, -delay_start is replaced with -delay_restart in 5.57

**Comment by Hope-UwU** [comment]
Is the behavior the same?
As in, if I want PersistentWindows to start 30 seconds after user logon, I need to subtract 10 seconds and use `delay_restart 20`

**Comment by kangyu-california** [comment]
-delay_restart 30 should do
