### ISSUE TITLE
Weird console window while starting

### ISSUE THREAD

**Issue by leo-liar** [kangyu-california/PersistentWindows#333]
Hello,

with version 5.55 there is now a console window visible every time PersistentWindows is started because (apparently) it starts, waits a few seconds and then creates some file `pw_restart.cmd`, terminates itself and executes said _cmd_ file. Is this intentional?

(I'm using a shortcut to `PersistentWindows.exe` in my auto start menu.)

Also said _cmd_ file prepends another command line parameter (`-wait_taskbar`) before all those configurations I've included in the start menu link to `PersistentWindows.exe`.

I don't see any information regarding this behaviour or this new command line parameter in the changelog and I'm not quite understanding the relevant(?) [code](../blob/d2a5f206e497fe901192a28e91e9bccf48838a0a/Ninjacrab.PersistentWindows.Solution/SystrayShell/Program.cs#L92).

**Comment by kangyu-california** [comment]
The restart behavior was added to enhance the -delay_start command implementation,  when trying to addressing user need in #332.

The -delay_start command option is mainly used to solve PW startup failure, for example PW icon may disappear from taskbar if started too early.

Restart PW would be a nice addition to make sure PW auto start works reliably.

**Comment by leo-liar** [comment]
Ah, I see. If the restart ability is needed, may I propose to use a _VBScript_ file to call `pw_restart.cmd` so that the console is hidden, e.g. something like this: ([source](http://superuser.com/questions/140047/how-to-run-a-batch-file-without-launching-a-command-window/390129))
```VBScript
If WScript.Arguments.Count >= 1 Then
    ReDim arr(WScript.Arguments.Count-1)
    For i = 0 To WScript.Arguments.Count-1
        Arg = WScript.Arguments(i)
        If InStr(Arg, " ") > 0 or InStr(Arg, "&") > 0 Then Arg = chr(34) & Arg & chr(34)
      arr(i) = Arg
    Next

    RunCmd = Join(arr)
    CreateObject("Wscript.Shell").Run RunCmd, 0 , True
End If
```

See attached [`Noshell.vbs`](https://github.com/user-attachments/files/16035974/Noshell.vbs.txt) which I grabbed from _WinPython_. (Had to append `.txt` as extension, otherwise the upload wasn't allowed.)

**Comment by kangyu-california** [comment]
Instead of running PW with -delay_start, you may try a new method to create delayed task using DOS schtasks command, as the result of discussion in #332
```
schtasks /create /delay 0000:10 /sc onlogon /tn "StartPersistentWindows" /f /tr "'%~dp0pw.bat'" /rl HIGHEST
```
the /delay 0000:10 command option specifies 10 second delay before running pw.bat (for more details on pw.bat, please refer to README page)

**Comment by leo-liar** [comment]
Thanks for suggestion! Maybe I'll give it a try without the `-delay_start` parameter and just check if this works. (I was just using this since the beginning.)

Your proposal to create a scheduled task sounds okay, but firstly I'm using PersistentWindows on my work laptop where I'm not having admin rights and do want to not clobber the scheduled task menu (personal preference). Secondly this way is rather complicated (manually creating an `pw.bat` file and then said scheduled task). And thirdly I think you missed my point – meaning that it's just confusing and unexpected to suddenly have a 10s console window popping up where there previously was none. That's why I recommended to automatically hide this (e.g. via VBScript) if there's no better way to do this programmatically.

For now my workaround is to directly start `pw_restart.cmd` using the _Noshell_ script which prevents the (for me at least) annoying console window.

**Comment by kangyu-california** [comment]
release 5.56 reduced console window waiting time from 10 seconds to 2 seconds. Hope you are satisfied with this improvement.
Please bear in mind -delay_start is an obsolete no longer officially supported.

**Comment by leo-liar** [comment]
Hello and thanks for the update. Though I still haven't got my point across: A desktop application should (IMHO) not suddenly pop out console windows! (Doesn't matter if it's 2s or 10s.)

That being said _I_ failed to properly understand that `-delay_start` has been deprecated. Sorry for that, I absolutely missed this change (From [Feb 6](4a2de1a)!) Therefore I've removed the obsolete command line option and PersistentWindows doesn't show up any console windows as expected.

As it's been obsolete for quite some time please don't put any effort into a workaround. I think this issue can be closed.
