### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by WizADSL** [kangyu-california/PersistentWindows#334]
Running version 5.55. I'm a new user and really love this program. I'm using it with a Samsung G95SE 40" OLED display. This display has Samsung's "MultiView" feature where you can connect two video sources and have them displayed side-by-side; in this mode the computer sees two separate 2560x1440 displays. The problem (and the reason I use the software) is that when the monitor goes to sleep the MultiView function turn off and the computer now sees a single 5120x1440 display and of course the window layout goes to hell. I'm running with these parameters "-splash=0 -fix_zorder=1 -delay_auto_capture 1.0". My issue is that the program will occasionally crash. I've attached a copy of the event log events for you review. The events span multiple reboots but you can see in the most recent event (and probably others) there was a crash.
[PWEvents.zip](https://github.com/user-attachments/files/16040876/PWEvents.zip)

**Comment by kangyu-california** [comment]
This is a exception which is safe to ignore
![image](https://github.com/kangyu-california/PersistentWindows/assets/59128756/7d3891de-fa62-461a-a6f9-5edae40ef969)
