### ISSUE TITLE
Release 5.55 : System Tray Right Click Menu Not Functioning

### ISSUE THREAD

**Issue by MySpecialSauce** [kangyu-california/PersistentWindows#335]
Updated to ver 5.55 and now the right click menu in the system tray no longer shows up and after a few minutes the system tray icon disappears all together, but the process is still running. I've tried a clean install with no luck. Downgrading to ver 5.54 brings the right click menu back. 

I've attached the event log from launching ver 5.55
[Event Log.txt](https://github.com/user-attachments/files/16042414/Event.Log.txt)

**Comment by kangyu-california** [comment]
Thanks for the timely feedback, this has been fixed in 5.56
