### ISSUE TITLE
Chrome window set as "Always on Top"?

### ISSUE THREAD

**Issue by WizADSL** [kangyu-california/PersistentWindows#337]
One of my Chrome windows seems to be getting set as "always on top" or at least it's behaving that way. I say "one of my Chrome windows" because the issue will happen even after a reboot or if I close all Chrome windows. Separately (but maybe related) I will frequently have an RDP session running in full screen mode when the computer locks/monitors go into standby and when I wake it back up that window will be very small (maybe 250x250) which it didn't do before using PW, I've also tried putting mstsc.exe on the ignore list but that does not seem to have an efffect. I'm on version 5.56. The arguments I am using are: -splash=0 -ignore_process "mstsc.exe" -delay_auto_capture 1.0 I've attached a screenshot of the windows properties of the Chrome window that is behaving like it's always on top in case it helps.

![Screenshot 2024-07-03 132821](https://github.com/kangyu-california/PersistentWindows/assets/2955060/93714b1a-75d7-42ff-8180-df3caee57673)

**Comment by kangyu-california** [comment]
I am not able to reproduce the issue on my side.

You may want to remove the -ignore_process "mstsc.exe" command option if you really want to preserve rdp window pos.
Also i would recommend remove the  -delay_auto_capture 1.0 command option, default delay should be good enough.
