### ISSUE TITLE
fail to restore HWinfo64

### ISSUE THREAD

**Issue by OGNetheri** [kangyu-california/PersistentWindows#338]
..is already running. " Getting this after last update after sleep mode, lock screen. Rebooting or exting and restarting the app doesn't help.

**Comment by kangyu-california** [comment]
In case you are running PW with -delay_start command option, which is obsolete now, 5.56 made some experimental change on that obsolete option, please remove it.

**Comment by OGNetheri** [comment]
I removed that and it helped for the "another instance"-problem. However now the HWinfo64 windows are unaffected by Persisten Windows and even won't restore their position after sleep mode. I tried to add starter instance in schedules for the "when logging in" but this doesn't help. Hwinfo's windows are on the 2nd monitor but this can't be the reason, as the Discord's window works fine on the 2nd remembering it's (persistent windows's) position setting.

**Comment by kangyu-california** [comment]
HWinfo64 windows restore fine on my PC.
PW provides multiple methods to disable restore for particular window. The issue is more likely due to the non-standard usage of PW.

**Comment by OGNetheri** [comment]
> HWinfo64 windows restore fine on my PC. PW provides multiple methods to disable restore for particular window. The issue is more likely due to the non-standard usage of PW.

I'm not looking to DISABLE the restore of this program. I'm asking why ISN'T  the PW restoring them while it restores other windows's just fine, also on 2nd monitor. Hwmonitors' sensor and graph windows stay at the main monitor after Windows is locked and unlocked again with log-on. And yes, I tried to add schedule to run PW after user login but it just adds the "anotherr instance already running" dialog without applying the saved position.

**Comment by kangyu-california** [comment]
It is recommended to run PW with admin privilege to restore windows with special permission.
Or you may use portable version of HWinfo64 instead of installer version.
