### ISSUE TITLE
Program needs to be exited and restarted for it to work. 

### ISSUE THREAD

**Issue by Trex187** [kangyu-california/PersistentWindows#34]
Hello,

I installed the program a couple of days ago and it worked fine. I set it up to autostart after observing it move the windows back to the original position after the monitors are woken from sleep. However after the first restart I noticed it no longer would reposition windows after the monitors are taken out of sleep mode.  I tried the capture windows to disk and that didn't work.  The only thing that worked is exiting the program and restarting it.  I tested it again and then it worked.

**Comment by GusMacG** [comment]
I have the exact same problem, is this solution coming to a new release soon?

**Comment by kangyu-california** [comment]
The problem might be caused automatic login without entering password. In that case, PersistentWindows might be started too early (before monitors are ready), you may confirm this by looking into Event Viewer, search in Windows Logs => Application for .Net Errors as well as event id 9990, 9999.

A speculative workaround is to add some delay before starting PersistentWindows. For example, you may create a .bat file within the unzipped directory as following

timeout 10
start persistentwindows.exe
 
then redirect the PersistentWindows shortcut in startup menu to point to the  .bat wrapper file instead.

**Comment by kangyu-california** [comment]
Please double check to make sure you are running the latest version 4.34. 

Then try the workaround mentioned in my last post.

**Comment by Trex187** [comment]
> Please double check to make sure you are running the latest version 4.34.
> 
> If the issue persists in version 4.34, then try the workaround mentioned in my last post.

I've added a delay of 30 since 10 was still too short.  That worked. And just for the record my Event Viewer doesn't have any 9990, 9999 events in it.

**Comment by kangyu-california** [comment]
Version 4.35 added a new feature to automatically delay start until display is ready. If that does not work, then try the new command option -delay_start \<seconds\> which would be equivalent to the .bat wrapper.

**Comment by kangyu-california** [comment]
I have updated Readme document to recommend creating auto start task using Task Scheduler instead of startup menu. Make sure to specify the task trigger as Begin the task "At log on"
