### ISSUE TITLE
PW 5.57 minor issue - restoring "This PC" window

### ISSUE THREAD

**Issue by sovalyeler** [kangyu-california/PersistentWindows#341]
Steps to reproduce:
1. Open up "This PC" and some othe windows
2. Capture windows to disk
3. Close some of the windows or all of them
4. Restore windows from disk

PW mistakenly restores user folder instead of "This PC" window. If only "This PC" windows is closed, PW doesn't restore it.

Windows 10 Enterprise 22H2 19045.4412
-webpage_commander_window=0
-fix_zorder=1
-foreground_background_dual_position=0
-invoke_multi_window_process_only_once=0
-legacy_icon
-delay_auto_restore 2.5

**Comment by kangyu-california** [comment]
Fixed in [5.57 patch1](https://github.com/user-attachments/files/16421897/PersistentWindows5.57_patch1.zip)
