### ISSUE TITLE
-legacy_icon setting doesn't work when there is an upgrade available

### ISSUE THREAD

**Issue by Marconius6** [kangyu-california/PersistentWindows#342]
Normally the -legacy_icon setting works just fine for me, but when there is an upgrade available, it switches over to the new icon anyway. Actually installing the upgrade to the new version, so there is no longer one available, seems to once again bring back the legacy icon.

**Comment by kangyu-california** [comment]
Fixed in [5.57 patch1](https://github.com/user-attachments/files/16421897/PersistentWindows5.57_patch1.zip)
you will be able to verify the fix when 5.58 is released which is scheduled for Sep.
