### ISSUE TITLE
program crashes when trying to run "capture windows to disk"

### ISSUE THREAD

**Issue by Neobond** [kangyu-california/PersistentWindows#351]
Searched for this but saw it was closed with a patch to 5.52. I am getting it in 5.57 and 5.58

I'm using the auto_start_pw,bat It gives a Dos dialog on boot, I don't remember seeing that until I clean installed this system either, any way to hide that?

There's a question mark on the Restore option too

![Screenshot 2024-09-06 101000](https://github.com/user-attachments/assets/fa923af3-3c82-49e4-ab5e-83b0981326e3)

Event logs

Error (Application Crashing Events)

Faulting application name: PersistentWindows.exe, version: 5.58.9005.35680, time stamp: 0x66ce9031
Faulting module name: KERNELBASE.dll, version: 10.0.26100.1301, time stamp: 0x14ba01fa
Exception code: 0xe0434352
Fault offset: 0x00000000000cc95a
Faulting process id: 0x896C
Faulting application start time: 0x1DB00338A546157
Faulting application path: D:\Programs\PersistentWindows\PersistentWindows.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 08bfc1fe-a8e8-4c21-a2c8-721658f22275
Faulting package full name: 
Faulting package-relative application ID: 

Error (None)

Application: PersistentWindows.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Diagnostics.Process.StartWithCreateProcess(System.Diagnostics.ProcessStartInfo)
   at PersistentWindows.SystrayShell.Program.GetProcessInfo()
   at PersistentWindows.SystrayShell.Program+<>c.<CaptureToDisk>b__37_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by kangyu-california** [comment]
It sounds like the powershell component on  win11 installation is not functioning, or maybe pw does not have admin privilege to launch certain command. Please understand it is very hard for me to guess what happened when non-typical thing like this happened. Advanced users like you should be able to build a debug version of pw and find out the exact cause.

**Comment by Neobond** [comment]
i'm not advanced, it's just a new clean install of Windows 11 24H2.

**Comment by kangyu-california** [comment]
The bug is due to a bad checkin on 4/21 causing inaccurate Windows 11 version detection.
Please try [PersistentWindows5.58_patch1.zip](https://github.com/user-attachments/files/16937170/PersistentWindows5.58_patch1.zip)

**Comment by Neobond** [comment]
Thanks for the update, it seems to work properly now.
