### ISSUE TITLE
Doesn't Work For Rider/IntelliJ Floating Windows

### ISSUE THREAD

**Issue by JonnyTsGitHub** [kangyu-california/PersistentWindows#352]
Windows constantly moves my floating Rider/IntelliJ windows.  PersistentWindows fixes all my other woes with windows being moved but it doesn't work on these.

I'm not surprised.  They aren't normal windows.  But it would be super awesome if it could work for them.

Repro:  Install Rider or IntelliJ.  Click the hammer on the bottom left to show the build window.  On the top right of the popped up window there are three dots.  Click that and select  View Mode -> Float.  Now you have a floating window.  These windows will get messed around by windows but PersistentWindows doesn't fix them.

Note.   In the same Rider/IntelliJ menu as "Float" there is also "Window".  You might ask why I don't use "Window".  "Window" does work with PersistentWindows because it has its own full window.  However it has other workflow problems.  It makes separate items on the taskbar you have to click between every time, and if you click the main window the other windows don't also pop up.  So its quite a bit MORE annoying than having your windows move.

Anyway, this is more a quirk of Rider/IntelliJ's bad layout system, but it would be awesome if PersistentWindows could handle it.  :)

**Comment by kangyu-california** [comment]
Try new command option -capture_floating_window with the patch
[PersistentWindows5.58_patch2.zip](https://github.com/user-attachments/files/16937684/PersistentWindows5.58_patch2.zip)

**Comment by JonnyTsGitHub** [comment]
Awesome!  I will, thank you.

I'm at a work conference this week so I won't be able to try it out until I return on Saturday.

Thanks!

________________________________

**Comment by JonnyTsGitHub** [comment]
Thanks for doing this!

I'm seeing inconsistent behavior.

For easy testing I tried Capture Snapshot/Restore Snapshot.  It worked last night.  However tonight it was not working.  I killed PersistentWindows and started it again and it began working again.

It does not seem to successfully restore after losing my monitors via a kvm switch.  My other windows pop back to the proper place after windows messes them up, but these don't.  Even using Restore Snapshot of the snapshot I took immediate before kvming that I had just tested did not work after coming back from the kvm.  I had to capture another snapshot before restoring it worked.

I'm running 5.59 downloaded from github, since I saw it got updated and my command line is: -splash=0 -capture_floating_window

I've attached my event log.

Thanks,
Jon

________________________________

**Comment by kangyu-california** [comment]
I dont feel like to spend more time on this.
If at least one snapshot works, the issue can be closed.

**Comment by JonnyTsGitHub** [comment]
Ok.  No problem.  That's for looking at it at all!  🙂

________________________________

**Comment by kangyu-california** [comment]
5.60 pre-release now captures child window by default
