### ISSUE TITLE
Refresh after moving windows back

### ISSUE THREAD

**Issue by fraktal-sb** [kangyu-california/PersistentWindows#36]
some windows moved to the primary screen are blank or show only a part of the contents after they were moved. Then they also are blank when moved back (see attached screencopy of a browser window) 
Could it be possible to add an optional "refresh window" by parameter? At the moment I do this manualy with the shortcut F5

![2020-08-30 15_18_37-Clipboard](https://user-images.githubusercontent.com/69430537/91660411-f6eecc00-ead5-11ea-932f-bedd7426e803.png)

**Comment by kangyu-california** [comment]
Pls run version 4.36 with -redraw_desktop

**Comment by kangyu-california** [comment]
@altsomnoros you have downloaded source code gz file instead of binary release which has .zip suffix in the name

**Comment by altsomnoros** [comment]
@kangyu-california Thank you for the fast reply. So I found the PersistentWindows4.36.zip in the release section of this page, is this what you are referring to? I unzipped it and see PersistentWindows.exe in the folder, is this what I need to insert in the Task Scheduler?
Thank you for your assistance, I don't have any programming skills and all of this seems confusing to me

**Comment by kangyu-california** [comment]
@altsomnoros you are right, there is only one .exe to choose from when selecting executable

**Comment by kangyu-california** [comment]
@altsomnoros Don't forget to create a trigger started when user log on when adding task
![image](https://user-images.githubusercontent.com/59128756/92146401-82b27200-edce-11ea-8b63-8b0935f28f5b.png)

After that you need to manually start the task, or reboot

**Comment by altsomnoros** [comment]
@kangyu-california Thank you so much for taking the time to help me, the program does what I was hoping it would do 🥇
