### ISSUE TITLE
All windows being minimized when logging back into pc

### ISSUE THREAD

**Issue by YouveGotMeowxy** [kangyu-california/PersistentWindows#362]
After locking my pc (Win + L) and having to input either my PIN or thumbprint to log back in, (I'm assuming this is just a "wake"), all of my windows being restored flash on screen for a sec, then minimize, which is great for those that were previously minimized, but not as great for the ones that weren't previously minimized. :)

Is this some bug, or working as intended?

**Comment by kangyu-california** [comment]
The temporary window flash is a side-effect of restoring minimized window to correct taskbar.
As long as minimized windows (before Win + L) is correctly restored to minimized, the flash should be tolerable.
