### ISSUE TITLE
VS Code + WSL causes frequent issues

### ISSUE THREAD

**Issue by ryobg** [kangyu-california/PersistentWindows#363]
Hi team,

I have noticed that the tray icon very frequently turns red after the monitors wake up and I have already opened VS Code with WSL terminals opened up. I think, I have seen this issue mentioned somewhere else too. Basically, after that all my windows have been moved around and I have to quit the app and launch it again.

**Comment by kangyu-california** [comment]
As mentioned in readme as known issues, Pending vscode update causes PW to pause restore. The workaround is just update vscode to new version, so that PW can resume the restore.

**Comment by ryobg** [comment]
Okay, thank you for the blazingly fast response, and sorry about my trivial question. I have just updated again to the newest VSC and I will give it some time for testing before coming back.

**Comment by ryobg** [comment]
After some testing, it all looks fine. Occasionally, an window does not end up where it should be, but this is rare, I cannot reproduce it and the application is not stuck. Therefore, it is not the same issue.
