### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by Lalaberri** [kangyu-california/PersistentWindows#38]
Just wanting to know if I'm missing something. Using windows 10 with whatever the near latest update is and the app will not run or launch. No splash window nor background task nor notification icon anywhere to be found after some days of trying. Any ideas?

**Comment by kangyu-california** [comment]
Hi,

Not sure how to reproduce your issue. 
After unzip, there are 10 files in the resulting directory, I guess you just copied PersistentWindows.exe alone to somewhere else, therefore it will not run.
If that is not the case, you may still get some clue by looking into Event Viewer, search for possible Errors in application section.

![image](https://user-images.githubusercontent.com/59128756/92318559-da193380-efc2-11ea-8db4-3a7e7d419276.png)

**Comment by Lalaberri** [comment]
you were absolutely correct, I didn't think to look back at the original file. I'm almost embarrassed I had to resort to asking, unsure why winrar only took that file, i just selected to extract all. All the same, it launched now, and will begin testing and hopefully put this issue that has plagued me for years behind me
