### ISSUE TITLE
PersistentWindows never re-opens the "Windows Terminal" app

### ISSUE THREAD

**Issue by SoCalDude** [kangyu-california/PersistentWindows#39]
PersistentWindows (PW) never re-opens the "**Windows Terminal**" app. However, once it is manually opened, PW will reposition it as it should. I have PW running with "highest privileges" (via Task Scheduler). The non-opening of "Windows Terminal" also occurs if I run PW manually, with or without "Run as administrator".

**Comment by kangyu-california** [comment]
Hi
The issue has been fixed by release 4.37

Thanks!

**Comment by SoCalDude** [comment]
You are very welcome. Thank you for fixing the issue. I can confirm that this works now.
