### ISSUE TITLE
PersistentWindows opens the Windows "Settings" app instead of the "Microsoft To Do" app

### ISSUE THREAD

**Issue by SoCalDude** [kangyu-california/PersistentWindows#40]
PersistentWindows (PW) opens the Windows "Settings" app instead of the "Microsoft To Do" app.

I have included the "Microsoft To Do" window in the "Capture Windows to Disk" function. If I perform the "Restore windows from disk", the windows "Settings" app launches and is placed in the exact position where I want the "Microsoft To Do" to be. 

However, if "Microsoft To Do" is manually opened and then I choose "Restore windows from disk", PW correctly positions the app.

Notes: I have PW running with "highest privileges" (via Task Scheduler). The incorrect opening of "Microsoft To Do" also occurs if I run PW manually, with or without "Run as administrator". This is on Windows 10 v2004 Build 19041.508.

**Comment by kangyu-california** [comment]
Fixed by v4.38

**Comment by SoCalDude** [comment]
Thanks, KangYu!
