### ISSUE TITLE
New windows open off screen

### ISSUE THREAD

**Issue by jimboca** [kangyu-california/PersistentWindows#41]
I love this program, thank you so much for the effort you have put into it.  It saves me so much time!

This is not an issue, but a feature request.  I have 3 different monitor configurations I use with my laptop, and with some configurations when opening a new window it will open off screen and I can't get it moved to the current screen..  Java apps seem to be the worst, and I have one Java app I use a lot...  Would it be possible for PersistentWindows to see a window was opened off screen and automatically move it?  Or an option in the menu to move off screen windows to a real screen?  I've tried all the tricks using key combinations to get it to move, but with some programs that does not work.

**Comment by kangyu-california** [comment]
The workaround is to capture all windows (including the java one) to disk, and when the issue shows up later on, just restore from disk.

A formal fix will be released by next weekend.

**Comment by kangyu-california** [comment]
Try 4.38 which is a speculative fix as I don't have a test case to reproduce this issue.

**Comment by jimboca** [comment]
Works great! Thanks you very much!!!  It  pulled it back on screen, the size was small but at least I can find it!!!

**Comment by jimboca** [comment]
It does work as I mentioned, but resizes the windows pretty small? Is it possible to keep the same window size but move it on a screen?

**Comment by jimboca** [comment]
Does it only resize of all points are off screen?  I think it resized one window that was not off-screen, but had points across 2 screens as it started up.  Also, you might want to make this an option selectable like you do for "pause auto restore"?

**Comment by kangyu-california** [comment]
The off-screen detection only checks visibility of top title bar of a window, which is the most critical control to enable manual move. If you have a window spanning across two screens but one of the screen is off (invisible to user), the window is still considered as off-screen and triggers auto position fix.

In the next release I will try to preserve original window size when fixing off-screen window, the problem of that implementation  is that previous window size might not fit current monitor. So there is no ideal solution for this issue.

**Comment by jimboca** [comment]
Ok, but it seems to keep grabbing and resizing a window that starts up across 2 screens which are both visible.

**Comment by kangyu-california** [comment]
Fixed in release 4.39,
1. off-screen detection criteria is improved
2. off-screen window is accurately restored to last known good location

**Comment by kangyu-california** [comment]
Further improved fix in release 4.40
Thanks!
