### ISSUE TITLE
Feature) Save multiple windows preset

### ISSUE THREAD

**Issue by moonjoungyoung** [kangyu-california/PersistentWindows#42]
Thank you for the fantastic util.
It is so useful.

Should this util will update to save multiple windows preset and set name to each preset?

**Comment by kangyu-california** [comment]
Sounds like a cool feature.
I plan to implement it in the next two weeks.
Stay tuned.

**Comment by ramzahn** [comment]
I'm utterly impressed. It does what it has to. And it does it well, without fuss. 
I use 3 monitor setup (openLayers programming) and i couldn't be happier right now.

Thank you.

**Comment by kangyu-california** [comment]
Release 5.0 has added limited support for multi preset (which is referred to as snapshot)

double click PW icon to take a snapshot; 
click PW icon to restore the snapshot; 
alt + click PW icon to undo restore snapshot

Named snapshot will be supported in later release.

Enjoy!

**Comment by kangyu-california** [comment]
Release 5.6 added support for additional snapshots (up to 3), now PW can support switching between 4 snapshots in total.
Please check [Online help](https://github.com/kangyu-california/PersistentWindows/blob/master/Help.md) for usage.

**Comment by moonjoungyoung** [comment]
@kangyu-california It is Sooo perfect. Thanks for support. Have a nice new year.
