### ISSUE TITLE
Presistent windows now showing in task bar

### ISSUE THREAD

**Issue by AtmaDarkwolf** [kangyu-california/PersistentWindows#43]
I run with task scheduler if that matters, might show up very briefly if I attempt to start a 2nd instance of PW(this is likely only the 2nd instance attempt which is really just the error message) 

Cannot alter settings or change how it works.

**Comment by kangyu-california** [comment]
Not sure why you want to run 2nd instance, because one instance is sufficient.
If you have old version running as task, just terminate it, then change task setting to run the new version

**Comment by kangyu-california** [comment]
Program icon start to show on task bar upon running, this is the default behavior of any Windows application,
not a PW specific issue.

**Comment by kangyu-california** [comment]
Fixed in 4.38
