### ISSUE TITLE
Move windows, click back to full screen app on other screen, windows immediately moved back

### ISSUE THREAD

**Issue by Djinnistorm** [kangyu-california/PersistentWindows#44]
As title. I move windows (Discord, firefox) where I want them, so I can best see them on my secondary monitor. Then I click back into the full-screen app in question, and it moves them back to some previous location that it seems to be stuck on. Maybe something I mistakenly saved to disk at some point? Let me know where that is stored and I can delete it if that might help.

Downloaded latest version, doesn't resolve issue. Windows 10, being run as admin. Here's the 9990 event log that occurs when this happens: 

```
Log Name:      Application
Source:        Application
Date:          9/19/2020 9:53:45 PM
Event ID:      9990
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      MStation
Description:
The description for Event ID 9990 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows: Start restoring window layout back to 9/19/2020 9:53:11 PM for display setting Display_LocM1920x0_Res1920x1080__Display_Loc0x0_Res1920x1080

The message resource is present but the message was not found in the message table

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application" />
    <EventID Qualifiers="0">9990</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-09-20T01:53:45.878179600Z" />
    <EventRecordID>9354</EventRecordID>
    <Channel>Application</Channel>
    <Computer>MarcStation</Computer>
    <Security />
  </System>
  <EventData>
    <Data>PersistentWindows: Start restoring window layout back to 9/19/2020 9:53:11 PM for display setting Display_LocM1920x0_Res1920x1080__Display_Loc0x0_Res1920x1080</Data>
  </EventData>
</Event>
```

**Comment by Djinnistorm** [comment]
I should have tried this first, sorry. I went to AppData and removed the two .db files there, "PersistentWindows.1.1.0.0.db" and "PersistentWindows.1.1.0.0-log.db". The windows now stick to their changed locations and sizes. Not sure how it got into a state, but it does seem to be related to saving a setup to disk. May be worth adding a button to clear saved disk location? I'm no expert.

**Comment by kangyu-california** [comment]
The issue is not supposed to happen.

The database on disk is applied to current window layout only when user explicitly select "restore windows from disk", i.e. there is no chance for PW to restore window layout using on-disk database during automatic restore.

Let me know if you can reproduce the issue.

As for suggestion to add button to clear on-disk database,  my suggestion is to use "Capture windows to disk" to flush out outdated data.

**Comment by kangyu-california** [comment]
I rethink the scenario, the issue could happen if the full screen program is a video game,  when the game changes display resolution, an automatic restore is triggered which revert your recent window moves.

The workaround is exiting both PW and the full screen app, then restart PW, then move firefox and Discord to second screen, and finally launch the full screen app.

**Comment by kangyu-california** [comment]
Another workaround is select "pause auto restore" menu before resume full screen game play

**Comment by Djinnistorm** [comment]
hmm, maybe. I have the fullscreen game in this case at the same resolution as the monitor normally is, does that not matter? 

Regardless, the app works normally now that I deleted the saved to disk configuration, not "restoring" my windows incorrectly when I switch back. So it doesn't seem to be triggering a restore...
