### ISSUE TITLE
Breaks screenshot hotkey Win+Shift+S

### ISSUE THREAD

**Issue by dclamage** [kangyu-california/PersistentWindows#45]
With PersistentWindows enabled (version 4.38.7568.26621), when I use Win+Shift+S to take a screenshot, PersistentWindows causes a black square to appear on my screen instead, and dragging to take a screenshot is impossible. Disabling PersistentWindows makes it work again, so I'm pretty sure that it's the culprit.

**Comment by kangyu-california** [comment]
Win+Shift+S works fine on my PC. 
I am not sure PW would draw black square on screen either.
Let me know if you see any Application event with id 9990 and 9999 in Event Viewer (with time stamp related to the screen shot)

**Comment by kangyu-california** [comment]
Reproduced the issue, will fix it by this weekend.
Thanks

**Comment by kangyu-california** [comment]
Fixed by release 4.39
