### ISSUE TITLE
Win+Shift+S window gets moved

### ISSUE THREAD

**Issue by dclamage** [kangyu-california/PersistentWindows#47]
Thanks for fixing the initial Win+Shift+S issue so quickly! However, I have tested it out and am having a different issue with it now.

When pressing the hotkey, it seems to present a window with a full greyed-out screenshot of both my monitors, but positioned such that it's supposed to cover up both monitors, and then lets you drag a box to crop it for the final screenshot.

However, my left monitor is a lower resolution that my right one, and in my display settings I've lined them up so that the top of my right monitor is above the top of my left monitor:
![image](https://user-images.githubusercontent.com/10701249/94295595-4d54fc00-ff16-11ea-9c7c-fa03213849ff.png)

I believe this triggers your new "off screen" detection because it moves this grey window to my right monitor instead:
![image](https://user-images.githubusercontent.com/10701249/94295712-80978b00-ff16-11ea-86d3-6de0064a1a17.png)

Perhaps the "off screen" detection shouldn't be so aggressive?

**Comment by kangyu-california** [comment]
Issue reproduced, 
Nice finding!

**Comment by kangyu-california** [comment]
Fixed in release 4.40
cheers!
