### ISSUE TITLE
Window moved back to main screen (4.40)

### ISSUE THREAD

**Issue by Patapum** [kangyu-california/PersistentWindows#49]
I have secondary screen on the left side of the main.
If I move some windows on secondary monitor they gets moved back in a second. 
Tested on Visual Studio Code, Discord, Slack - looks like chromium based apps affected.
Other windows seams to be unaffected.

Event logs:

> The description for Event ID 9999 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> PersistentWindows: top left of Rect (-1932, 489), 1846 x 1104 is off-screen
> 
> The message resource is present but the message was not found in the message table

> The description for Event ID 9999 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> PersistentWindows: Auto fix invisible window "004722EC"
> 
> The message resource is present but the message was not found in the message table

**Comment by kangyu-california** [comment]
Please try release 4.41
If the issue still exists, you may totally turn off automatic off-screen window position fix by running PW with option -disable_offscreen_fix

**Comment by kangyu-california** [comment]
4.41 is canceled due to crash, please try 4.42

**Comment by Patapum** [comment]
Thank you!
