### ISSUE TITLE
V2.6 not auto running and/or shutting down

### ISSUE THREAD

**Issue by DavidG-Aus** [kangyu-california/PersistentWindows#5]
Since loading V2.6 I have had several occasions when windows have not been restored correctly after a sleep. I checked and Persistent Windows was not running at the time.

It seems to not be auto running on Windows start (which it used to) and I think I noticed a couple of times when I had manually run it and then it wasn't running some time later.

**Comment by kangyu-california** [comment]
Thanks for the detailed description.

I suspect there are invalid window handle or other memory issue which might be causing the program to crash.

Please test the latest 2.8 release, which improves program robustness by fixing memory leak and guard against invalid window handle and other exceptions.

Thanks

**Comment by kangyu-california** [comment]
Please try V2.9 which resolved a potential timing conflict between window capture and window restore.
