### ISSUE TITLE
[feature request] create chocolatey.org package / implement auto update ?

### ISSUE THREAD

**Issue by MisterT87** [kangyu-california/PersistentWindows#52]
Hello Folks :)

Is it possible to create a chocolatey.org package for PW - To get the feature for auto-update PW ?
(I am not sure: I Heard from auto-scripts using githubs API to create chocolatey packages ?)

Or implement an auto-update feature in PW itself ? Would be really nice :)

Please keep up the great work ! Really helpful App :)

**Comment by MisterT87** [comment]
Addendum for @kangyu-california about the auto scripts for building chocolatey packages out of github...

sadly not possible until now :'( 
See: [https://www.reddit.com/r/chocolatey/comments/hwdrki/can_github_packages_be_used_as_a_chocolatey/](https://www.reddit.com/r/chocolatey/comments/hwdrki/can_github_packages_be_used_as_a_chocolatey/)

**Comment by kangyu-california** [comment]
Thanks for the suggestion, 
The auto-upgrade feature will be implemented in the next major release by the end of Oct, together with some other features I am working on.

I did some research on available auto-update solutions, and found they are too complicated for this light-weight app.
My plan is let PW periodically check github release url for any new release, and manage to update PW binaries and then restart PW.

This should be sufficient for standard PC user who has normal internet access to github.

For corporate users with restricted internet policy, their system admin probably will have to modify app config file by themself to redirect download url to corporate intranet.

**Comment by MisterT87** [comment]
yeah sounds fine too mee to - thank you :)

**Comment by kangyu-california** [comment]
The issue is partially solved in release 5.0, where an upgrade notice tooltip will pop up when newer release is available.

I would let users to drive the installation process.

Thanks

**Comment by salvattore001** [comment]
hi. i upgraded to version 5. 
is there a switch available to disable auto upgrade at startup?
thanks!

**Comment by kangyu-california** [comment]
@salvattore001 

The missing switch (disable upgrade check at startup) will be added in next release by this weekend

Thanks for the feedback

**Comment by kangyu-california** [comment]
@salvattore001 
please test release 5.1 using switch -check_upgrade=0

**Comment by salvattore001** [comment]
thanks a lot for this app! it's hard to believe that the OS doesn't behave this way natively

**Comment by MisterT87** [comment]
@kangyu-california thank you also again for this great app and also for implementing update check :)

if you have time can you also update this github with the new commandline options ? otherwise its hard to keep track with all options :D

**Comment by kangyu-california** [comment]
@MisterT87 

In next release I will change "about" menu to "Help" which will redirect to an html file summarizing all command line options.

**Comment by MisterT87** [comment]
@kangyu-california nice thats even better :) Thank you again

I am closing this issue for better overview - feel free to reopen otherwise :)
