### ISSUE TITLE
PersistentWindows not fully starting? 

### ISSUE THREAD

**Issue by neodata686** [kangyu-california/PersistentWindows#53]
I unzipped the entire directory and ran it as the current user but no splash screen opens. It loads into the task bar but only shows these two options: 
![image](https://user-images.githubusercontent.com/30646455/95666386-433a1c80-0b16-11eb-8f5e-8656288536f6.png)

Latest version of Windows 10.

Also if my monitors go to sleep and wake up the window positions are not saved. Nothing shows up in diagnostics and the Windows event log has no 9999 or 9990 events.

**Comment by kangyu-california** [comment]
It seems the downloaded version is pretty old (2.x), you may verify that by checking the property of PersistentWindows.exe

Make sure you are downloading the latest version (currently 4.44)
![image](https://user-images.githubusercontent.com/59128756/95666736-834ad080-0b11-11eb-8257-0fbd08c591a2.png)

**Comment by neodata686** [comment]
That was it! I'm not sure why I got the older version. Trying 4.4 now!

**Comment by neodata686** [comment]
It appears to be working!! Thank you! We can close this issue.
