### ISSUE TITLE
Upgrade Instructions

### ISSUE THREAD

**Issue by MonstarSuperS** [kangyu-california/PersistentWindows#54]
HI there,

I'm recently new to using Persistent Windows, but it's been a lifesaver with my 4K laptop and the multiple different monitors I end up plugging in to.

However, I see that v5 is released and I want to upgrade from v4.44. I just wanted to confirm the correct upgrade steps. Should I be copying over the new files to my "install" location? Or is there a DB/preferences file I should not copy (or merge) so that the history of devices and how my windows were setup are maintained?

Thanks!

**Comment by kangyu-california** [comment]
Just overwrite install directory with new files should do.
PersistentWindows does not use install directory to store DB.
