### ISSUE TITLE
V2.8 not working

### ISSUE THREAD

**Issue by DavidG-Aus** [kangyu-california/PersistentWindows#6]
Bad news I'm afraid.  I have loaded V2.8 and after several sleeps, it is not working :-(
It is still running but I have not restarted the PC so I can't say whether it auto runs or not.

**Comment by kangyu-california** [comment]
Please try V2.9, which resolved timing conflict between capture and restore.

**Comment by kangyu-california** [comment]
Found major issue in V2.9, please hold

**Comment by kangyu-california** [comment]
please try V3.0

**Comment by kangyu-california** [comment]
A new bug was introduce in V3.0. Please try V3.1

**Comment by kangyu-california** [comment]
closing due to no response
