### ISSUE TITLE
Version 5.3 has upgrade notice about 5.2

### ISSUE THREAD

**Issue by camsung** [kangyu-california/PersistentWindows#60]
I have version 5.3, but when I launch, it tells me there is an update available, and that update is version 5.2.

**Comment by kangyu-california** [comment]
Sorry for the confusion, 5.3 is flagged as a pre-release intended for testing by #57 reporter,
so that users of 5.2 won't get auto upgrade notice.

If you are already running 5.3, just ignore the notice.

**Comment by kangyu-california** [comment]
The bogus upgrade notice will be fixed in next release

**Comment by kangyu-california** [comment]
Fixed in 5.4

**Comment by Hardtarget24** [comment]
Ha, I was wondering what was going on with 5.3 saying version 5.2 was available!
