### ISSUE TITLE
screen-saver messes things up

### ISSUE THREAD

**Issue by piotr5** [kangyu-california/PersistentWindows#61]
not an issue to me, since you can save/restore window-positions. others might suffer though:
I have main screen with taskbar on hdmi and secondary on vga-connector. put windows on secondary, turn off main and wait till windows goes into hibernating that main screen. then turn on main screen so it turns itself off again automatically due to no signal. if before doing that you pressed a key or otherwise ended the screen-hibernation PersistentWindows works as usual, but the procedure I describe here moves all windows irreversibly to main screen once the screen-hibernation ends. (vga-connector has no signal-detection possibility for windows, so it doesn't matter if it's on or off, to windows my secondary screen is always on.)

**Comment by kangyu-california** [comment]
It seems to be a new type of issue I have not met before. Please go through Readme "Tips to digest before reporting a bug" section, and post PersistentWindows event log to help diagnosis.

Here is a screen shot of required information.

![image](https://user-images.githubusercontent.com/59128756/99221754-0527bc80-2796-11eb-94f6-843548396a52.png)

**Comment by kangyu-california** [comment]
Could not reproduce the issue,
Please try latest 5.7 release,
If the issue still exist, please elaborate the terms in bug description,
I found following terms confusing 
screen-saver, screen hibernate, windows hibernate screen etc
