### ISSUE TITLE
Occasional failure to restore any windows

### ISSUE THREAD

**Issue by JohnChristmann** [kangyu-california/PersistentWindows#62]
After returning to my PC, occasionally, Persistent Windows will fail to perform a restore operation entirely.  Using a debug build to investigate using the log file, I've discovered that when this happens, the transition from 2->1 monitors is logged, but the transition from 1->2 monitors is not.  On my system, both of these happen in rapid succession when I wake the PC up, so I suspect that this issue is a result of the two events happening too close together.  Windows are then saved in incorrect positions and must be manually moved back.

**Comment by kangyu-california** [comment]
Please pull latest commit, and build debug version to see if it helps.

**Comment by JohnChristmann** [comment]
The latest commit has had no effect on this issue.

**Comment by JohnChristmann** [comment]
I'm going to say that this is tentatively fixed.  It hasn't happened again since the linked commit though it's hard to say for sure due to the inconsistent nature of the problem.

**Comment by kangyu-california** [comment]
Thanks for testing. Feel free to reopen if issue is reproduced later on.
