### ISSUE TITLE
doesn't work when machine starts from SLEEP

### ISSUE THREAD

**Issue by amravs** [kangyu-california/PersistentWindows#65]
Doesn't seem to remember scren positions after SLEEP.

**Comment by kangyu-california** [comment]
Please take following steps to confirm the issue,

1. Before letting computer sleep, take a note of current time (with precision down to second),
2. After computer wake up, wait for 10 seconds for all windows to settle down to their final places, then search for following message in Event Viewer, "Start restoring window layout back to time X"

If time X value is later than your recorded time, the bug is confirmed.

![image](https://user-images.githubusercontent.com/59128756/101537808-f5446800-3950-11eb-9b50-848d23b64b3b.png)

**Comment by amravs** [comment]
I put the computer to sleep 12:37:00 and restarted a few minutes later but no info on event 9990

![image](https://user-images.githubusercontent.com/71774295/101631751-c1367900-3a1c-11eb-8852-f4b032a65e99.png)

**Comment by kangyu-california** [comment]
Could be a very old release?
Make sure to run my latest release 5.7

**Comment by amravs** [comment]
It is 5.7

**Comment by amravs** [comment]
The odd thing is that it is running

![image](https://user-images.githubusercontent.com/71774295/101751810-a1f52580-3ac8-11eb-8c87-35ba5c0d6e46.png)

**Comment by amravs** [comment]
but, it doesn't appear in the trya so I can interact with it - any ideas? I have a task scheduled to run the job as follows

![image](https://user-images.githubusercontent.com/71774295/101752149-0fa15180-3ac9-11eb-85f8-0ef787f6fd14.png)

![image](https://user-images.githubusercontent.com/71774295/101751956-d2d55a80-3ac8-11eb-8ee2-f533b764284a.png)

![image](https://user-images.githubusercontent.com/71774295/101752060-f4364680-3ac8-11eb-9109-42c8499be215.png)

![image](https://user-images.githubusercontent.com/71774295/101752115-00ba9f00-3ac9-11eb-9b94-6e116c52c602.png)

**Comment by kangyu-california** [comment]
In task property settings, choose "Run only if user is logged on" instead of "Run whether user is logged on or not". Otherwise, PW might be launched too early to be functional (GUI subsystem might not be ready yet).

**Comment by amravs** [comment]
is this now the correct response  - don't understand the first part though?

****The description for Event ID 9990 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.****

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows: Session opening: reason SessionUnlock

The message resource is present but the message was not found in the message table

The description for Event ID 9990 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows: Start restoring window layout back to 11/12/2020 16:36:21 for display setting Display_Loc0x0_Res1920x1080__Display_Loc1920x0_Res1920x1080

The message resource is present but the message was not found in the message table

The description for Event ID 9990 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows: Restore finished in pass 4 with 3 windows recovered for display setting Display_Loc0x0_Res1920x1080__Display_Loc1920x0_Res1920x1080

The message resource is present but the message was not found in the message table

**Comment by kangyu-california** [comment]
Microsoft is complaining about unregistered 9990 & 9999 event IDs,
However in order to register event ID, user would have to run with admin privilege which is unnecessary.

To workaround this, just switch to "Detailed" view in event viewer, 

Again it is not a bug of PW.

**Comment by amravs** [comment]
Hi

Windows still not resuming to original position before going to sleep - am I missing a setting?

![image](https://user-images.githubusercontent.com/71774295/102087486-8a43d700-3e11-11eb-9229-045d44edeb75.png)

**Comment by kangyu-california** [comment]
I have recommended in README file to create a trigger to launch PW when user log on in task scheduler.

If task scheduler still does not for you, just run PW manually.

It may take some time to figure out how to use Microsoft  task scheduler properly, which is beyond the scope of PW project

**Comment by amravs** [comment]
Hi

I have read that and set up task scheduler - all I need to know is which switch to use so that my winows automatically revert back? at the moment outlook keeps returinng to screen 1 when I want it in screen 2

should I use -fix_zorder? or another switch?

**Comment by kangyu-california** [comment]
PW should just work without any switch.
