### ISSUE TITLE
Files remain protected and "in use" after closing PersistentWindows

### ISSUE THREAD

**Issue by Tamalero** [kangyu-california/PersistentWindows#67]
Hello Folks.
I downloaded  5.6.X version of PersistentWindows and noticed 2 issues.

Problem 1:
1) Upon closing the program, the files remain active and cannot be deleted.
Noticed this when I tried to update and overwrite the files with the newer version.
2) The program def not loaded and does not appear in the Task Manager. So .. what is locking these files?
I have extracted the files in a secondary hard disk, so its not a system disk issue.

Problem 2:
Saving Windows and restoring will only restore certain windows.
Example. I have 7 Explorer browsers. When rebooting and restoring. It only opens a single default window, and not maximized like the screens were saved.
Microsoft Word has the same issue. I had saved 4 instances with different files, only the first is opened but it opens correctly to one of the files opened.

Firefox, Chrome and Thunderbird do correctly open in the correct screen ( I have 2 4k screens and 1 drawing tablet, for a total of 3 screens).

My Specs:
Windows 10 x64
AMD 3960X 24 core Threadripper TRX40 
Aorus PRO WIFI TRX40
32GB DDR4 3600 Extreme memory
Zotac 2070 Super 
Sound Blaster Z

**Comment by kangyu-california** [comment]
All files can be deleted after exiting PersistentWindows,  It would be helpful if you provide more clue as which file get locked.

I also could not reproduce the 2nd problem, multiple explorer/winword windows can be restored from disk. Maybe try capture to disk one more time to make sure the latest data is saved?

Lastly, please try latest release 5.7, which fixed some random crash issue. Your machine config is good enough.

**Comment by Tamalero** [comment]
> 
> 
> All files can be deleted after exiting PersistentWindows, It would be helpful if you provide more clue as which file get locked.
> 
> I also could not reproduce the 2nd problem, multiple explorer/winword windows can be restored from disk. Maybe try capture to disk one more time to make sure the latest data is saved?
> 
> Lastly, please try latest release 5.7, which fixed some random crash issue. Your machine config is good enough.


I',m now using 5.7

Regarding first error ( Not being able to delete) After reboot it resolved itself.

Regarding 2nd problem. I'm using MICROSOFT WORD, not winword. Could this be the issue? I also saved to disk again.
It only restores a single Microsoft Word instance, not the 4 I have open.
The rest seem ok.
It no longer opens an additional default Explorer window when restoring like 5.6 did.

**Comment by kangyu-california** [comment]
It could be that my version of Microsoft Word  is lower than yours.
Would you mind send the db file back for me to take a look.
The db file is located at C:\Users\<userid>\AppData\Local\PersistentWindows\PersistentWindows.1.1.0.0.db

you only need to open two Word windows and capture them to disk.

**Comment by Tamalero** [comment]
Here you go!

To resume:

1. 2 Firefox Windows 
2. 1 Chrome window
3. 6 Explorer Windows (different directories)
4. 4 Microsoft Word instances ( 4 documents )
5. Mozilla Firefox
6. Harvest 
7. Toggle
8. Steam






[PersistentWindows.1.1.0.0.zip](https://github.com/kangyu-california/PersistentWindows/files/5680307/PersistentWindows.1.1.0.0.zip)

**Comment by kangyu-california** [comment]
Multiple office 2016 word windows are restored correctly from db file on my test machine.
Anyway please try latest 5.8 release which has a speculative fix for a corner-case failing scenario.

You may check following messages in Event Viewer to validate multiple restore commands were issued.
![image](https://user-images.githubusercontent.com/59128756/102003934-ab48e280-3cc0-11eb-8dd8-4ce4ca1b15ce.png)

You may also go to the folder where .db file is stored and checkout all the pw_exec*.bat files and manually run them to validate.

**Comment by Tamalero** [comment]
> 
> 
> Multiple office 2016 word windows are restored correctly from db file on my test machine.
> Anyway please try latest 5.8 release which has a speculative fix for a corner-case failing scenario.
> 
> You may check following messages in Event Viewer to validate multiple restore commands were issued.
> ![image](https://user-images.githubusercontent.com/59128756/102003934-ab48e280-3cc0-11eb-8dd8-4ce4ca1b15ce.png)
> 
> You may also go to the folder where .db file is stored and checkout all the pw_exec*.bat files and manually run them to validate.

Hi Kangyu!
I can confirm that it is restoring, but curiously, it tried to recover 4 instances of the same MICROSOFT WORD file.
Both instances have the exact same parameters.
`The description for Event ID 9990 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows: launch process "C:\Program Files (x86)\Microsoft Office\Root\Office16\WINWORD.EXE"           /n "F:\DATOS\F\F2\Cesarin\OR-files\FILES\TMNTHardMetal.docx" /o ""

The message resource is present but the message was not found in the message table
`

This is what the eventviewer says, all 4 of them.
It is incorrectly detecting only  ONE file from Microsoft Word and not the 4 different documents.
In this case, because the eventviewer shows the same command and file. It only opens a single instance of Microsoft Word.


Also..
If I close all the instances of Windows Explorer and then restore from disk with PersistantWindows
similarly, it will spawn 7 Windows Explorer windows. But they will ALL spawn on the default view ( in my case, on the default MY PC view, where all your hard disks are visible)

There is also one event with seems to be an error...

`The description for Event ID 9990 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows: launch process C:\Windows\system32\ApplicationFrameHost.exe -Embedding

The message resource is present but the message was not found in the message table`

Then the last event viewer message showing the process complete:

`The description for Event ID 9990 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

PersistentWindows: Restore finished in pass 2 with 16 windows recovered for display setting Display_Loc0x0_Res2560x1440__Display_Loc3840x0_Res2560x1440__Display_Loc7680x0_Res1920x1080

The message resource is present but the message was not found in the message table
`

**Comment by kangyu-california** [comment]
What you observed is a "feature" of office 2016, rather than a bug of PW.

What happens is that when you open multiple word documents in office 2016, all the windows share the same process,
and as there is no way for PW to know which document is actually opened, PW query the command line of owner process of each window, and all 4 word windows get the same command line "winword.exe somefile.docx", here somefile.docx represents the first opened file.

Office 2016 also has a feature to prevent user from opening multiple copies of the same file, therefore you only got one window recovered, all other 3 windows are instantly eat away by office itself. Office 2010 does not have this feature though.

After all, restore from disk is a bonus feature of PW, user should not expect it to recover original desktop 100% accurately after reboot. You should push Microsoft instead, do you agree?
