### ISSUE TITLE
Windows icons are shifting around

### ISSUE THREAD

**Issue by Archeol** [kangyu-california/PersistentWindows#68]
After waking the computer up from sleep, it seems to be that all the icons are moving around randomly and all onto one monitor. You guys seem to be able to counter Windows messing around with resizing/rearranging open windows, think you can make a fix for this too?

I've tried the basic fixes on the web and the rest seem to be very complicated and unverified fixes, so I'm hoping you guys might be capable given what you already can do.

**Comment by kangyu-california** [comment]
With all desktop area already covered by open windows, I found desktop icons less useful nowadays.
In windows 10, user can launch any program from taskbar by typing a few initial letters about key word anyway.
I feel that preserving desktop icon position is not a must have feature.

Plus there are already some tool addressing this issue, like icon keeper etc, some of them are opensource available on github. Take some time to try.

**Comment by kangyu-california** [comment]
Here is my workaround: 
1. Create a folder to store all shortcuts to frequently used programs (equivalent to desktop icon)
2. Use explorer window to manage these shortcuts
3. Using PW to preserve the explorer window
