### ISSUE TITLE
[Request] Rick-Click -> Edit Snapshot

### ISSUE THREAD

**Issue by ziplock9000** [kangyu-california/PersistentWindows#71]
I'm not sure what format you store the snapshots in (hopefully JSON or XML?). But an option to right click and select "Edit Snapshot in default editor" would be nice so I could manually tweak what/where the windows appear etc.

**Comment by kangyu-california** [comment]
on-disk storage format is db (LiteDB opensource project), which support limited offline-edit capability, checkout LiteDB studio on github.

currently quick "snapshot" data is saved in memory instead of db file, eventually everything will be able to be archived to db file

**Comment by ziplock9000** [comment]
That's a shame, I was hoping it was in a human readable format that doesn't require a 3rd party tool. But ok, thanks.
