### ISSUE TITLE
[Request] Backup Windows Before Sleep & Autostart/Autoclose

### ISSUE THREAD

**Issue by znbaboy** [kangyu-california/PersistentWindows#74]
Please add an option to save the windows locations right before my PC goes to sleep.

Also add a feature to auto start the application on login then close it automatically after windows have been restored. (This might interfere with my first request, but maybe have the application run right before sleep? Not sure if that's possible.)

Thank you!

**Comment by kangyu-california** [comment]
The Capture/Restore operation is fully automatic in PW and most other similar tools,
PW also provided Pause/Resume function for user who prefers manual operation.

I really don't see the benefit of manually starting PW and yet automatically exit.
It appears [TAN Window Manager](https://github.com/Todd1561/TANWindowMgr) would be exactly what you need.

**Comment by znbaboy** [comment]
Okay...

Is there a bat file I can make with a command that automatically backups the window locations? This way, I might be able to have task scheduler auto run this bat when the PC is about to go to sleep.

**Comment by kangyu-california** [comment]
Sorry I do not understand your use model of automatically start PW and then let it kill itself.

**Comment by znbaboy** [comment]
I am not talking about that anymore. I will leave the application running, that is fine.

I want to create a script file. When it runs, I want the script file to "Capture windows to disk" like your program allows.

This way, I can point task scheduler to that script file every time my computer is about to go to sleep.
