### ISSUE TITLE
dialog box not restored

### ISSUE THREAD

**Issue by kangyu-california** [kangyu-california/PersistentWindows#75]
Track issue raised by hdprene in Discussion area.

![image](https://user-images.githubusercontent.com/59128756/104882607-2f256880-5918-11eb-82fe-0a7abb7a33e7.png)

**Comment by kangyu-california** [comment]
@hdprene
Should be fixed in release 5.16, please test it.

**Comment by hdprene** [comment]
Again thank you very much, I will test it today!!

**Comment by hdprene** [comment]
Ok I cant find it in the help section. What is the best startup parameter to let persistent windows do a restore windows from disk right after startup of the pc

**Comment by kangyu-california** [comment]
The parameyer does not exist yet.
Will add it in later release

**Comment by hdprene** [comment]
First of all! Thank you very much for following this up so fast!! This my link command line now is C:\Tools\PersistantWindows\PersistentWindows.exe ‑auto_restore_missing_windows
Persistantwindows 5.17 does start, no failure messages, but the auto restore doesn't work (yet). Also starting the link as admin or not doesn't change anything. Then I made it a scheduled task with the highest prio but here it still works the same as 5.16. Maybe I don't understand this new option right. According to my question the addition should be named as -auto restore_windows_from_disk. Thanks again for looking into this. It's a great tool!

**Comment by kangyu-california** [comment]
The new switch is introduced to resolve side effect of fixing another issue, will enhance it to address this issue

**Comment by hdprene** [comment]
Wonderful :-)

**Comment by kangyu-california** [comment]
Try release 5.19 with -auto_restore_missing_windows=3

**Comment by hdprene** [comment]
Mooi!
