### ISSUE TITLE
Windows reset position multiple times.

### ISSUE THREAD

**Issue by ziplock9000** [kangyu-california/PersistentWindows#79]
Very often I'll turn my monitors back on, the windows move back to the location they were last at (which is good)
But for the next 20 second or so when I try to move them they keep getting rest back to the same location.
This happens maybe 6 or so times. I have to just leave it for 30 seconds for it to settle down before I can move or resize windows

I'm wondering if there's an entry for some windows in the database multiple times? (A human-readable database would allow others to debug this instead of having to come to you)

**Comment by kangyu-california** [comment]
The restore time is proportional to the total number of windows need recovery,  
user is not expected to move window when PW icon is red (busy restore), as this is creating conflict between capture and restore.

**Comment by kangyu-california** [comment]
as explained in your earlier ticket, PW uses liteDB format to store location information, you need to resort to liteDB related tool to convert it to human readable text file.
