### ISSUE TITLE
Interference with "TidyTabs"

### ISSUE THREAD

**Issue by C0Nd3Mnd** [kangyu-california/PersistentWindows#80]
I'm using [TidyTabs](https://www.nurgo-software.com/products/tidytabs) (I use the paid version, but that shouldn't make a difference) and when using it together with PersistentWindows, windows move unintentionally shortly after switching tabs when another window on the same tab bar was moved:

https://user-images.githubusercontent.com/47672946/107050189-3a5b0e00-67cb-11eb-9898-97a878830d0b.mp4

The way that TidyTabs works (I think) is that is just adds this tab bar and hides all windows that aren't the active tab. When you move one window, only this one gets moved and after switching tabs, the other one gets moved (without the user noticing it). PersistentWindows seems to restoring the window to its original position afterwards though, which is not what's wanted here.

Is there a way to limit window position restoration to when a screen was actually turned off/back on again? Or some workaround for this issue with TidyTabs specifically?

**Comment by ziplock9000** [comment]
@C0Nd3Mnd Just a side note here, I use Groupy which is similar to TidyTabs and it has no issues with PW that I've noticed

**Comment by C0Nd3Mnd** [comment]
> @C0Nd3Mnd Just a side note here, I use Groupy which is similar to TidyTabs and it has no issues with PW that I've noticed

I can confirm this since I tried both tools. I decided to stick with TidyTabs however, since WindowGrid wouldn't work well with Groupy, and I also like the "less intrusive" tab bar more.

**Comment by ziplock9000** [comment]
> WindowGrid

Is that like PowerToys FancyZones ?

**Comment by C0Nd3Mnd** [comment]
> > WindowGrid
> 
> 
> 
> Is that like PowerToys FancyZones ? 

Yeah...well it has the same goal, but it's different in that it displays a grid (i.e. 12x6 tiles) and you can resize windows to any amount of tiles (i.e. 4x3 or whatever).

**Comment by kangyu-california** [comment]
Fixed in release 5.15
