### ISSUE TITLE
[Request] Option to auto restore windows as before #73

### ISSUE THREAD

**Issue by herekittycomekitty** [kangyu-california/PersistentWindows#81]
I was using the feature of automatically spawing missing windows when restoring a capture as some sort of a manual multi-autostart alternative. #73 changed that behaviour so now I always have to click "Yes to all" first and restore again after to get the windows into the right size and position.

My suggestion is to just add another command line argument that overrides the `yes_to_all` flag introduced in #73 to be always `true` as suggested in my pull request.

**Comment by kangyu-california** [comment]
Merged and release in 5.17, thanks for the enhancement!
