### ISSUE TITLE
Hidden Keepass autotype window

### ISSUE THREAD

**Issue by steberk** [kangyu-california/PersistentWindows#85]
Hello,

When I press ctrl-alt-a hot key to auto-type a Keepass entry, the Keepass displays a Window to select the correct entry (when multiple entries match). 

From v5.12 this window is moved behind of all windows (Z order last). So the window is not visible until I press alt-tab and alt-tab again.
This problem exists with v5.17 too.

**Comment by kangyu-california** [comment]
Fixed in 5.18
