### ISSUE TITLE
Taskbar position will not be restored

### ISSUE THREAD

**Issue by Stefan1200-de** [kangyu-california/PersistentWindows#9]
Tested **PersistentWindows 3.6** today, it restored the window positions perfectly. But it does not restore the Windows Taskbar position.

My setup:
Windows 10 - 1909 - 64 bit
2 screens:
- My primary screen: 2560x1440x144
- My secondary screen: 1920x1080x60

I have my primary Taskbar on my secondary screen, to be able to access the application icons to the left of the clock while having a full screen application on my primary screen. But every time my two screens switch to standby (energy saving options), my primary Taskbar is on the primary screen again.

Is it possible, that PersistentWindows restore the Taskbar position too?

**Comment by kangyu-california** [comment]
The taskbar issue has been fixed in V3.7.

**Comment by Stefan1200-de** [comment]
I still have this issue with PersistentWindows 3.7.

**Comment by kangyu-california** [comment]
After a few failed attempts, It seems to me that taskbar is managed by Windows OS. Although it can be moved by program, the moved taskbar won't show icons, also the temporary result won't last, it would jump back to default position upon mouse click.

I would suggest following workaround, 
1. enable  "show taskbar on all displays" in taskbar settings
2. enable "automatic hide taskbar" on the monitor that prefers full screen mode.

Hope this helps

**Comment by kangyu-california** [comment]
In version 3.8, taskbar recovery issue is fixed by simulating mouse drag action in code.
However taskbar position change by user can not be tracked automatically, user needs to click a newly added "Capture" menu item to record such a change.
Also the new fix is not quite robust, as it requires user to not move mouse during restore.
