### ISSUE TITLE
Avast - IDP.Generic

### ISSUE THREAD

**Issue by danuvian** [kangyu-california/PersistentWindows#93]
I tried to create a task in task scheduler to auto-start Persistent Windows ... and I got an Avast popup: "We've moved PersistentWindows.exe to your Virus Chest because it was infected with IDP.Generic"

What is going on here???

**Comment by kangyu-california** [comment]
I do not use any anti-virus software other than Microsoft Defender Antivirus.
I would guess the warning is false alarm.

**Comment by kangyu-california** [comment]
It might be that your PC has multiple account, and Avast restrict setting task for non-current user.
If that is the case, just change the trigger of the task from 'any user' to 'specific user'

**Comment by danuvian** [comment]
In the task scheduler, I did select a specific user (me). That's when Avast showed me the warning.

**Comment by kangyu-california** [comment]
This post might help
https://forum.avast.com/index.php?topic=237416.0
