### ISSUE TITLE
Issue with RDS instance

### ISSUE THREAD

**Issue by glitchhh** [kangyu-california/PersistentWindows#94]
Hello,

I have been using PersistentWindows for over a year now and I wanted to thank you for all your hard work and regular updates.

I noticed that for the latest update v5.19, when I use remote desktop for work. It displays both my monitors on my main monitor with scroll bars even though I have "use all my monitors for the remote section" checked and no changes were made besides updating from v5.18 to v5.19.

![image](https://user-images.githubusercontent.com/65319653/110367999-479f2e80-7ffd-11eb-9f4f-a17cce221931.png)

I tried restarting my work computer and relogging in and out a couple of times to see if that would fix it but that did not work. In the meantime I had to close down PersistentWindows and log into RDS and then start it up.

Please let me know if you require anything additional from me.

Thank you.

**Comment by kangyu-california** [comment]
Thanks for the prompt feedback, 
the bug is introduced by 5.19.
Please keep using 5.18 before next release (5.20) is out.

**Comment by glitchhh** [comment]
Thank you for your prompt response. I will revert back to v5.18 for the meantime.

**Comment by kangyu-california** [comment]
Fixed in 5.20
