### ISSUE TITLE
won't start up on boot up or signin

### ISSUE THREAD

**Issue by darchon7** [kangyu-california/PersistentWindows#95]
i've placed a shortcut in shell:startup (C:\Users\<user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup)

but persistent windows won't start up automatically on bootup or sign in.

its listed in Startup Apps and marked active.

other apps in that folder startup fine.

**Comment by kangyu-california** [comment]
The startup menu method is not suggested due to failure mentioned in readme.

Try task scheduler instead.
I am assuming you can manually run PW successfully.

**Comment by darchon7** [comment]
ah silly me, should've paid more attention to the readme. tried the -delay_start method with 10 and 30 secs. both didn't work. i have a pretty decent machine AMD Threadripper 1950x 32gb ram. but task scheduler method worked so thanks.
