### ISSUE TITLE
Feature Request: In-place and automatic upgrade

### ISSUE THREAD

**Issue by MFHFozzy** [kangyu-california/PersistentWindows#97]
It would be great to be able to upgrade without re-downloading/installing manually.
Although, there should also be an option to turn off automatic upgrades and continue to upgrade manually.

**Comment by kangyu-california** [comment]
The in-place upgrade feature will be provided in next release, estimated release date is 3/28

**Comment by kangyu-california** [comment]
Feature implemented in 5.20.
In-place upgrade can be done by click menu "Upgrade to version x.xx" once a new upgrade is detected.
Fully automatic upgrade can be done through command option  -auto_upgrade=1
